### ISSUE TITLE
Make Columns draggable and resizable

### ISSUE THREAD

**Issue by Ruffz** [casperstorm/ajour#101]
_**Is your feature request related to a problem? Please describe.**_
I would like to have "Status" column right after "Addon" column and have ability to set the space between columns.

_**Describe the solution you'd like**_
Make Columns draggable and resizable.

**Comment by casperstorm** [comment]
Thank you so much for your feedback, @Ruffz.
I have no added it to our roadmap: https://github.com/casperstorm/ajour/projects/2#card-45550101.

**Comment by Ruffz** [comment]
Thanks for this update²

Columns resize is perfect, but I can't drag/reorder these

**Comment by casperstorm** [comment]
> Thanks for this update²
> 
> 
> 
> Columns resize is perfect, but I can't drag/reorder these

Great!
Reorder will come later. It requires quite a refactor.
