### ISSUE TITLE
Add more, optional, columns like Latest version / Game version / Author / Last update date

### ISSUE THREAD

**Issue by Ruffz** [casperstorm/ajour#102]
_**Is your feature request related to a problem? Please describe.**_
Not an issue, just a personal preference.

_**Describe the solution you'd like**_
Add more, optional, columns like Latest version / Game version / Author / Last update date / Any users other idea.

**Comment by casperstorm** [comment]
This has been added to the [roadmap[(https://github.com/casperstorm/ajour/projects/2#card-45790708).
