### ISSUE TITLE
Optimize rendering time, view, and layouting. 

### ISSUE THREAD

**Issue by casperstorm** [casperstorm/ajour#128]
When running a debug build and hitting `f12` we are able to inspect different metrics from `iced`:

<img width="1307" alt="Screenshot 2020-09-24 at 15 41 23" src="https://user-images.githubusercontent.com/2248455/94153066-9d7f8000-fe7c-11ea-9816-e113598bcc99.png">

I think it would be nice to look into if we could get these numbers even lower. We don't have any performance issues, but we always want to be as performant as possible so I am sure there are optimizations to be done in out `update.rs` and `element.rs` file.

I don't see this as an important issue. I see it as a reminder to us.
Any comments on this, @tarkah?

**Comment by tarkah** [comment]
Yeah this is something we definitely need to dig into at some point. I've done some rust profiling with `perf` before, but on much simpler programs. I wonder how well it'll work with the Iced framework making a lot of noise.

I have no context for how fast each of these metrics should be, plus we are running a debug build so it'll be much lower than the release profile. But it's a good benchmark to compare versions or new features to see if things slow down at all. Or when figuring out optimizations, if it improves any of them.

I'll definitely start utilizing this when adding features to make sure nothing impacts performance over the current release. And I'll try to play around with `perf` or other profiling tools to see if we can uncover any expensive operations that we can focus on.

**Comment by tarkah** [comment]
Interestingly, on windows, the Update speed is orders of magnitude faster! I average somewhere around 500-600ns. Layout is a bit quicker too. I wonder what the main driver for that difference is. I assume those operations are completely CPU bound?

![image](https://user-images.githubusercontent.com/10239377/94168851-eb779200-fe42-11ea-9fa0-16d098026354.png)

**Comment by tarkah** [comment]
Or could just be when you took the screenshot... It appears the Update starts high when first launched, then drops pretty quickly after moving the cursor around for a bit.

**Comment by casperstorm** [comment]
To be honest I haven’t debugged it TOO much. It’s just a thing I had in my mind for some time that it would be nice to do some debugging on.

Also we have this in our main.rs:
https://github.com/casperstorm/ajour/blob/a515c4c84e87eee29e92a3bbb8a54516951074fa/src/gui/mod.rs#L347

**Comment by tarkah** [comment]
> Also we have this in our main.rs:
> 
> https://github.com/casperstorm/ajour/blob/a515c4c84e87eee29e92a3bbb8a54516951074fa/src/gui/mod.rs#L347
> 
> I just added this initially when I started the project but not even sure it does something for us.

From the docs... might not do much for us since we don't use Canvas or have too many complex shapes outside text
```
If set to true, the renderer will try to perform antialiasing for some primitives.

Enabling it can produce a smoother result in some widgets, like the Canvas, at a performance cost.

By default, it is disabled.

```

**Comment by tarkah** [comment]
:o apparently you can use Firefox Profiler with `perf` data

https://www.reddit.com/r/linux/comments/g0mx3z/til_firefox_profiler_makes_an_awesome_gui_for_perf/

**Comment by tarkah** [comment]
Here is the profile after running for just ~20 seconds, opening settings, changing theme, switching flavors, clicking refresh a couple times

https://share.firefox.dev/2RXHTMt

**Comment by casperstorm** [comment]
> Here is the profile after running for just ~20 seconds, opening settings, changing theme, switching flavors, clicking refresh a couple times
> 
> https://share.firefox.dev/2RXHTMt

Wow, this is really really cool. This could be very useful.

**Comment by tarkah** [comment]
Yeah, its tough because all of our commands get spawned on the async runtime, so they are scattered across all the threads, but if you search each function name, you can see what thread it was on and look into it. For example, I looked at the `load_user_themes` function and it appears to have taken `73.6ms`

**Comment by tarkah** [comment]
I'm thinking of how we can restructure the entire code base to make benchmarking and profiling a lot easier to do. I'm thinking the `gui` module should be our actual bin crate. Everything else should move into a lib crate so we can easily create tools around our logic and profile those. I'd love to throw `read_addon_directory` into a 1 liner program and profile / benchmark just that process. What do you think?

**Comment by tarkah** [comment]
Actually, might as well just have `gui` under `lib.rs` then `main.rs` just imports from `ajour` instead of `crate`

**Comment by casperstorm** [comment]
I kinda like that idea.
We should work towards that, @tarkah.

**Comment by mlablah** [comment]
> 
> 
> I'm thinking of how we can restructure the entire code base to make benchmarking and profiling a lot easier to do. I'm thinking the `gui` module should be our actual `bin` crate. Everything else should move into a `lib` crate so we can easily create tools around our heavy calculations and profile those. 

I imagine this work will also make something like a headless mode easier to implement down the road. :)

**Comment by tarkah** [comment]
@mlablah exactly!

**Comment by tarkah** [comment]
So I just timed the `read_addon_directory` function and here are my results on my Addons folder of 67 folders / 200MB. Note that this is also fingerprinting 100% of the folders, no caching.

```
tarkah on solus-home in ajour on  feat/split-lib [?] is 📦 v0.3.3 via 🦀 v1.45.2
❯ du -h --max-depth=1 ~/Documents/World\ of\ Warcraft/_classic_/Interface/
200M    /home/tarkah/Documents/World of Warcraft/_classic_/Interface/AddOns
200M    /home/tarkah/Documents/World of Warcraft/_classic_/Interface/

tarkah on solus-home in ajour on  feat/split-lib [?] is 📦 v0.3.3 via 🦀 v1.45.2
❯ time target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/
17 addons parsed
real    0m1.556s
user    0m0.251s
sys     0m0.053s
```

**Comment by tarkah** [comment]
What's weird is that time seems like an outlier on the benchmark. I was getting more like 4-5 seconds on average. Which is strange because when I launch the app, addon parsing rarely ever takes longer than what seems to be 1-2 seconds. So I wonder why the `read_addon_directory` takes longer when run by itself than within the app? Wonder if it has to do with the overhead of the async runtime starting up, which you don't perceive when launching the app?

**Comment by tarkah** [comment]
Checkout https://github.com/sharkdp/hyperfine

Here's my results on 10 tests:

```
tarkah on solus-home in ajour on  feat/split-lib [?] is 📦 v0.3.3 via 🦀 v1.45.2
❯ hyperfine --warmup 3 'target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/'
Benchmark #1: target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/
  Time (mean ± σ):      1.743 s ±  0.170 s    [User: 258.3 ms, System: 32.5 ms]
  Range (min … max):    1.524 s …  2.042 s    10 runs
```

**Comment by tarkah** [comment]
And here is a comparison of with & without leveraging the fingerprints cache... doesn't seem like fingerprinting is expensive at all. It actually barely beat out the use of the fingerprint cache... weird.

```
Benchmark #1: target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/
  Time (mean ± σ):      1.629 s ±  0.088 s    [User: 265.5 ms, System: 31.9 ms]
  Range (min … max):    1.535 s …  1.783 s    10 runs

Benchmark #2: target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/ --fingerprints ~/.config/ajour/fingerprints.yml
  Time (mean ± σ):      1.694 s ±  0.173 s    [User: 274.1 ms, System: 38.7 ms]
  Range (min … max):    1.499 s …  2.009 s    10 runs

Summary
  'target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/' ran
    1.04 ± 0.12 times faster than 'target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/ --fingerprints ~/.config/ajour/fingerprints.yml'
```

**Comment by tarkah** [comment]
And if I remove all addons so it's just processing an empty directory:

```
Benchmark #1: target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/
  Time (mean ± σ):     527.6 ms ±  55.3 ms    [User: 52.7 ms, System: 15.1 ms]
  Range (min … max):   465.5 ms … 604.4 ms    10 runs

Benchmark #2: target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/ --fingerprints ~/.config/ajour/fingerprints.yml
  Time (mean ± σ):     556.6 ms ±  95.2 ms    [User: 52.2 ms, System: 17.6 ms]
  Range (min … max):   456.7 ms … 707.6 ms    10 runs

Summary
  'target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/' ran
    1.06 ± 0.21 times faster than 'target/release/parse_addon_directory ~/Documents/World\ of\ Warcraft/_classic_/Interface/AddOns/ --fingerprints ~/.config/ajour/fingerprints.yml'
```

**Comment by tarkah** [comment]
Created a test for the `file_parsing_regex` function and it's about half of that:

```
❯ hyperfine -m 25 target/release/file_parsing_regex
Benchmark #1: target/release/file_parsing_regex
  Time (mean ± σ):     225.4 ms ±  53.3 ms    [User: 37.5 ms, System: 11.9 ms]
  Range (min … max):   179.8 ms … 353.4 ms    25 runs
```

**Comment by casperstorm** [comment]
With #130 we should also update README, or maybe the Wiki, with information about how to benchmark. It is very very intersting, and this can help us becoming even faster.

**Comment by casperstorm** [comment]
Let's close this for now and reopen once we get more into optimizing rendering time. I feel like the code splitting you did was a good start @tarkah.
