### ISSUE TITLE
Add icon to Windows executable

### ISSUE THREAD

**Issue by casperstorm** [casperstorm/ajour#13]
Ajour only displays an icon on the executable. However, start-menu and the application border does not have an icon.
This is dependent on https://github.com/hecrj/iced/pull/285. Currently awaiting a new release of `iced` so the API is available.

![ajour-no-icon](https://user-images.githubusercontent.com/2248455/89740754-e5447680-da8b-11ea-8640-e803d1ac1226.PNG)

- [X] Executable icon https://github.com/casperstorm/ajour/pull/30/commits/777f628c8544f34c0ab11c9e2311cc74ae5aafd9
- [x] Status bar icon
- [x] Start bar icon

**Comment by WeaponMan** [comment]
You can use `embed_resource` for embeding icons into exe's. I did same thing with `gtk-rs` and the main window had the icon that was embedded. Not sure if it will work with iced, but you can give it a shot.

**Comment by casperstorm** [comment]
Ive just added the following commit: https://github.com/casperstorm/ajour/pull/30/commits/777f628c8544f34c0ab11c9e2311cc74ae5aafd9.
This now shows Ajour with an icon on the .exe file, but still no icon in the status bar, or in the start bar.
