### ISSUE TITLE
Provide Ubuntu/Linux port

### ISSUE THREAD

**Issue by Feichtmeier** [casperstorm/ajour#137]
**Is your feature request related to a problem? Please describe.**
I am playing WoW with lutris/wine which works perfect. 
I tried running your .exe with wine but it crashed

**Describe the solution you'd like**
Could you provide a port of your app for Ubuntu/Linux?

**Describe alternatives you've considered**
Make it work with wine but I would clearly prefer a real port. Maybe you could provide a snap or deb installation file

**Comment by casperstorm** [comment]
Thank you for this request, @Feichtmeier.
I'll look into providing a snap or deb installation file going forward. What you can do right now is build it from source on your Linux machine, it does require you to install a few dependencies but isn't that complicated: https://github.com/casperstorm/ajour/blob/master/INSTALL.md#debianubuntu

**Comment by Feichtmeier** [comment]
Alright, thank you for looking into this :)
I tried to install the dependencies on Ubuntu 20.04 but at some point something was missing. Anyways, looking forward to a snap/deb and thanks for taking the time to code this

**Comment by prosenboim** [comment]
Hi. Tried to build it from source on Fedora 31, rust 1.46. When running it immediately crashes with following backtrace:
```    Finished release [optimized] target(s) in 0.14s
     Running `target/release/ajour`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AllocationError(OutOfMemory(Device))', /home/pasha/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.6/src/device/mod.rs:324:14
stack backtrace:
   0:     0x5574b1201fd4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h707590392471721d
   1:     0x5574b122d15c - core::fmt::write::hb9c48a6b6485ef7a
   2:     0x5574b11fa402 - std::io::Write::write_fmt::hdcc1cf7fbca6265f
   3:     0x5574b1204c65 - std::panicking::default_hook::{{closure}}::h761fdcb7a7bbe8bd
   4:     0x5574b12049a2 - std::panicking::default_hook::hccc16564029255d0
   5:     0x5574b12052b4 - std::panicking::rust_panic_with_hook::h7eb3bb02037dc9db
   6:     0x5574b1204eab - rust_begin_unwind
   7:     0x5574b122aeb1 - core::panicking::panic_fmt::h2d8192b0fa814e5c
   8:     0x5574b122acd3 - core::result::unwrap_failed::h289133a76ccf6765
   9:     0x5574b0f22d41 - wgpu_core::device::Device<B>::create_buffer::h416f6aa3fe323c5f
  10:     0x5574b0f7339c - wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_buffer_mapped::h2d631ea396b26a1c
  11:     0x5574b0f114ef - wgpu_device_create_buffer_mapped
  12:     0x5574b0f0dabb - wgpu::Device::create_buffer_mapped::h59e5962d5da47f45
  13:     0x5574b0f0dc0a - wgpu::Device::create_buffer_with_data::h622d29699d6c04f3
  14:     0x5574b0f0b99d - wgpu_glyph::pipeline::Pipeline<()>::new::h94b82ee455b1894c
  15:     0x5574b0edffc5 - iced_wgpu::backend::Backend::new::hf32301102ac1f394
  16:     0x5574b0ed920e - <iced_wgpu::window::compositor::Compositor as iced_graphics::window::compositor::Compositor>::new::h441300f9588f6aa1
  17:     0x5574b0d6dc39 - iced_winit::application::run::hfc286af4b32fbd22
  18:     0x5574b0c5552a - ajour::gui::run::h62b9c857e64afc5a
  19:     0x5574b0ccc3a0 - ajour::main::h50094075cf662e49
  20:     0x5574b0c441c3 - std::rt::lang_start::{{closure}}::h66e5adaca1246943
  21:     0x5574b1205763 - std::rt::lang_start_internal::h97b335b971c44443
  22:     0x5574b0ccdc32 - main
  23:     0x7f24afe081a3 - __libc_start_main
  24:     0x5574b0c0c32e - _start
  25:                0x0 - <unknown>
```

**Comment by ARx6WtNN7Z7em** [comment]
> Thank you for this request, @Feichtmeier.
> I'll look into providing a snap or deb installation file going forward. What you can do right now is build it from source on your Linux machine, it does require you to install a few dependencies but isn't that complicated: https://github.com/casperstorm/ajour/blob/master/INSTALL.md#debianubuntu

Hi mate, wanted to second the request for an official Linux option. As soon as Linux users sees "open source" in the wowhead article we jump on this. You have the possibility now to become the sole addon manager for Linux at the moment 😃 The other managers don't really work that great. Looking forward to using ajour! Great work!

**Comment by tarkah** [comment]
I just want to chime in that I use Ajour on Linux (Solus) with no issue, so it's definitely possible! I can help look into packaging for Snap so things are a bit easier.

@prosenboim, what GPU are you using? Ajour uses Vulkan under the hood, I'm curious what the `AllocationError(OutOfMemory(Device))` means... A quick Google search didn't show much. I think it's technically possible to use OpenGL with our gui framework, so maybe I can create a quick branch for that and see if that works for you.

**Comment by prosenboim** [comment]
> what GPU are you using?
I'm using GeForce GTX 960 with proprietary NVidia drivers. I believe I have vulkan libs installed, but to be sure, can you specify vulkan dependencies ?

**Comment by tarkah** [comment]
Hmm, on Fedora the main package might just be `vulkan`. See if installing that helps.

**Comment by prosenboim** [comment]
vulkan-loader provides vulkan. Both vulkan-loader and vulkan-tools are installed. Version is 1.2.131. Might be too old?

**Comment by tarkah** [comment]
Worth updating if you can. I'll try to get the OpenGL branch pushed out today so you can test that. If that works, we can add instructions for building from source to use OpenGL in case other users have issues with Vulkan.

**Comment by prosenboim** [comment]
Ouch. My fault. Tried to run it while game was running. After quitting world of warcraft it displayed window. Thanks!

**Comment by tarkah** [comment]
Oh, nice! Glad you got it working. I'll keep the OpenGL idea in my back pocket if we see more users having issues by default.

**Comment by moggybaer** [comment]
Installed it today on Pop_OS! 20.04 (basically Ubuntu) Just works fine. 
Like @casperstorm said. I followed the instructions and it worked directly

**Comment by lostsoulsnemesis** [comment]
Hey! I made a couple of PKGBUILDs for arch, one from source and one from binary ( for the lazy ones )

https://github.com/lostsoulsnemesis/ajour
https://github.com/lostsoulsnemesis/ajour-bin

They seem to work, but I don't play on arch anymore, so feel free to fork/steal/adopt them

**Comment by Tarnadas** [comment]
Really cool to see a Rust project using Iced in the trending charts!
I have also such a project and I can recommend automating your releases by uploading draft releases via Github Actions. You can see an example in my repo:

https://github.com/Tarnadas/smmdb-client/blob/master/.github/workflows/rust.yml

**Comment by tarkah** [comment]
Thanks, @Tarnadas! Yeah we are planning to do exactly that through github actions. I've also got AppImage working so we plan to start shipping that on each release for linux.

**Comment by tarkah** [comment]
@Tarnadas It appears you are releasing for linux already on your app. Did you find that pretty much all the shared libraries needed for `iced` exist on any major popular distro? I assume anyone running one of the main Desktop Environments is going to have all those installed already. So I'm thinking it's safe for us to just ship the standalone binary?

**Comment by tarkah** [comment]
For example, here's the libraries identified as required when I put together the AppImage:

```
libbz2.so.1.0
libcrypto.so.1.1
libgraphite2.so.3
libpcre.so.1
libpng16.so.16
libssl.so.1.1
libXau.so.6
libXdmcp.so.6
```

**Comment by tarkah** [comment]
I think I'll still plan to ship an `AppImage` file just in case. And I guess it'll be more clear that it's a standalone executable that can be used anywhere

**Comment by Tarnadas** [comment]
I actually haven’t checked the required dependencies for the popular Linux distros. I didn’t have to install any dependencies on my PopOS installation, but that should not be very representative.
How did you get that list of dependencies? I would try something like `cargo tree | grep sys` and check their cargo.rs readmes for any system dependencies. I never built an AppImage before however

**Comment by tarkah** [comment]
Easiest way is to just `ldd` the binary. But quite a few of those are things 100% always available. I got that list specifically when I built the AppImage, it has a tool that automatically finds the shared libs needed.

I tested the AppImage on fresh Ubuntu 20.04 image and a live usb of Solus that's like a year old and it worked perfectly on both. So I'm just going to play it safe and ship the AppImage. You can see #189 for how I'm doing that, using their `linuxdeploy` tool.

**Comment by tarkah** [comment]
Closing now that we have AppImage on our 0.3.5 release

https://github.com/casperstorm/ajour/releases/tag/0.3.5

**Comment by Feichtmeier** [comment]
Thank you very much @tarkah and everyone involved :+1:  Checking this out right now!
