### ISSUE TITLE
Release Version Selection for Addons

### ISSUE THREAD

**Issue by eldir** [casperstorm/ajour#139]
Especially early in an expansion being able to switch between stable and alpha release versions of addons can be vital.
Attaching a screenshot of how it was handled in the Twitch client.
![image](https://user-images.githubusercontent.com/5166778/94551589-7eeb0180-024d-11eb-94a6-36b22950f8c5.png)

**Comment by casperstorm** [comment]
This is done, and has been merged to master: https://github.com/casperstorm/ajour/issues/92
It will be shipped when I am doing the next release. Should be ready end of this week!
