### ISSUE TITLE
[Website] Misleading Open Graph Information

### ISSUE THREAD

**Issue by bitbruder** [casperstorm/ajour#140]
**Describe the bug**
When your share https://getajour.com/, most social networks and chat applications use open graph attributes. In case of ajour, its still using the ones provided by webflow. This creates misleading link previews.

**To Reproduce**
1. Share https://getajour.com/ 
2. Check the Link Preview.

![image](https://user-images.githubusercontent.com/15855432/94556894-1f492200-025e-11eb-8760-39c96951a651.png)

![image](https://user-images.githubusercontent.com/15855432/94557056-56b7ce80-025e-11eb-8deb-4bca7660449c.png)

**Expected behavior**
A clear and concise description of https://getajour.com/ 

**Software involved**
Please complete the following information:
 - Twitter, Slack, Rocket.Chat, Facebook, basically any software that uses Open Graph to Display additional information provided by these meta tags

**Comment by casperstorm** [comment]
This has now been fixed. Thanks for reporting.
