### ISSUE TITLE
From ajour.exe to Ajour

### ISSUE THREAD

**Issue by Plougz** [casperstorm/ajour#141]
As of right now, if you click your windowskey and search for the program, its named "ajour.exe". This could simply be changed to Ajour for a more professional look
![Screenshot_1](https://user-images.githubusercontent.com/71008749/94558195-ef9b1980-025f-11eb-9e14-e8bff9aff06c.png)

**Comment by mlablah** [comment]
Adding a shortcut to the start menu will make that shortcut show up in search results as well, looking like this:

![image](https://user-images.githubusercontent.com/68285419/94613149-69ed8d00-02a4-11eb-8629-e4b5e83e122c.png)

This is done by creating an "Ajour" folder here: %ProgramData%\Microsoft\Windows\Start Menu\Programs\Ajour and placing a shortcut to the executable in it, titled Ajour.

Normally this is done by wrapping the executable in an installer that then offers the user to create the program menu folder.

**Comment by casperstorm** [comment]
For now @mlablah's answer will be the answer here.
Eventually in the future we might consider wrapping the executable in a installer to get such features.
