### ISSUE TITLE
GW2 UI not detected

### ISSUE THREAD

**Issue by Deynix** [casperstorm/ajour#142]
Using version Ajour 0.34 on Windows 10, installed version of GW2 UI (retail) is not detected by Ajour. Addon is working normally, installed in Addons\GW2_UI  and is detected by the Twitch client. All other installed addons are detected.

Curseforge page for GW2 UI is: https://www.curseforge.com/wow/addons/gw2-ui

Log output:

09:59:04.000 [ajour][DEBUG] Ajour 0.3.4 has started.
09:59:04.009 [ajour::config][DEBUG] loading config
09:59:04.009 [ajour::theme][DEBUG] loading user themes
09:59:04.009 [ajour::utility][DEBUG] checking for application update
09:59:04.010 [ajour::fs::theme][DEBUG] loaded 0 user themes
09:59:04.300 [ajour::gui::update][DEBUG] Message::Parse
09:59:04.300 [ajour::gui::update][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "E:\\Battle.net\\World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        ignored: {
            Retail: [],
        },
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: None,
    scale: None,
    backup_directory: Some(
        "E:\\WowUI Backups",
    ),
}
09:59:04.300 [ajour::gui::update][DEBUG] preparing to parse addons in "E:\\Battle.net\\World of Warcraft\\_retail_\\Interface/AddOns"
09:59:04.300 [ajour::gui::update][DEBUG] preparing to parse addons in "E:\\Battle.net\\World of Warcraft\\_classic_\\Interface/AddOns"
09:59:04.300 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
09:59:04.300 [ajour::gui::update][DEBUG] Message::NeedsUpdate(None)
09:59:04.301 [ajour::parse][DEBUG] retail - parsing addons folder
09:59:04.301 [ajour::parse][DEBUG] classic - parsing addons folder
09:59:04.302 [ajour::parse][DEBUG] retail - 67 folders in AddOns directory to parse
09:59:04.308 [ajour::gui::update][DEBUG] Message::LatestBackup(Some(2020-09-29T09:54:21))
09:59:04.308 [ajour::gui::update][ERROR] Message::ParsedAddons(classic) - Addon directory not found: "E:\\Battle.net\\World of Warcraft\\_classic_\\Interface/AddOns"
09:59:04.565 [ajour::parse][ERROR] fingerprinting failed for "E:\\Battle.net\\World of Warcraft\\_retail_\\Interface/AddOns\\GW2_UI": Unable to find file: "E:\\Battle.net\\World of Warcraft\\_retail_\\Interface\\AddOns\\GW2_UI\\libs\\libs/LibStub/LibStub.lua"
09:59:04.565 [ajour::parse][DEBUG] retail - 66 fingerprints: 66 cached, 0 calculated, 0 added, 0 removed
09:59:04.583 [ajour::parse][DEBUG] retail - 66 successfully parsed from '.toc'
09:59:04.583 [ajour::parse][DEBUG] retail - 0 addons with tukui id
09:59:04.583 [ajour::parse][DEBUG] retail - 0 addons applied with tukui id package metadata
09:59:04.583 [ajour::parse][DEBUG] retail - 66 unique fingerprints to check against curse api
09:59:04.705 [ajour::parse][DEBUG] retail - 9 exact fingerprint matches against curse api
09:59:04.706 [ajour::parse][DEBUG] retail - 9 addons applied with fingerprint metadata
09:59:04.706 [ajour::parse][DEBUG] retail - 9 addons with curse id
09:59:04.833 [ajour::parse][DEBUG] retail - 9 addons applied with curse id package metadata
09:59:04.833 [ajour::parse][DEBUG] retail - 9 addons successfully parsed
09:59:04.833 [ajour::gui::update][DEBUG] Message::ParsedAddons(retail, 9 addons)

**Comment by tarkah** [comment]
Thanks for the bug report! Can you try a fresh install of the addon from curse and then delete your fingerprint cache located at `%APPDATA%/ajour/fingerprints.yml` and then relaunch Ajour and see if it still doesn't appear?

**Comment by casperstorm** [comment]
It seems like it fails to generate a fingerprint. I'll look into this.

**Comment by Deynix** [comment]
Same result after a fresh install and deleting the fingerprint cache. And looks like it's returning the same error:

12:48:52.881 [ajour::parse][ERROR] fingerprinting failed for "E:\\Battle.net\\World of Warcraft\\_retail_\\Interface/AddOns\\GW2_UI": Unable to find file: "E:\\Battle.net\\World of Warcraft\\_retail_\\Interface\\AddOns\\GW2_UI\\libs\\libs/LibStub/LibStub.lua"

Hm. Did check and that file does exist, but I noticed that the last two backslashes in the path are forward slashes in the error message. Would that cause the error?

**Comment by tarkah** [comment]
Thanks for trying those steps. No, that shouldn't be the cause.

@casperstorm it seems like it's failing here: https://github.com/casperstorm/ajour/blob/3dd767f55a7969b0185daa616d9711f63e8d5f1b/crates/core/src/parse.rs#L621-L626

**Comment by casperstorm** [comment]
This will be handled in #147.
