### ISSUE TITLE
Missing addon: GW2 UI and others

### ISSUE THREAD

**Issue by moggybaer** [casperstorm/ajour#147]
**Describe the bug**
A list of missing addons from my setup

**To Reproduce**
1. Install the missing addons marked in the screenshot

**Expected behavior**
The addons should appear in ajour

**Screenshots**

![image](https://user-images.githubusercontent.com/7250921/94586211-406f3a00-0281-11eb-9f59-3a90ed0552bd.png)

**Software involved**
Please complete the following information:
 - OS: Pop_OS! 20.04 (Ubuntu)
 - Ajour version: 0.3.4 Installed manually as described at https://github.com/casperstorm/ajour
 - Missing addons: Guild Wars 2 UI, masque_shadow, ouf_hank, ouf_ruri

**Additional context**
I am not sure if i got the ouf addons from curse but i think so. concerning guild wars 2 ui: this is 100% from the curse website

**Comment by tarkah** [comment]
Thanks for the bug report! Can you try a fresh install of the addons from curse and then delete your fingerprint cache located at `$HOME/.config/ajour/fingerprints.yml` and then relaunch `Ajour` and see they still don't appear?

**Comment by moggybaer** [comment]
> Thanks for the bug report! Can you try a fresh install of the addons from curse and then delete your fingerprint cache located at `$HOME/.config/ajour/fingerprints.yml` and then relaunch `Ajour` and see they still don't appear?

i will do this when i have the time and tell you asap

**Comment by casperstorm** [comment]
I tried this and the follow is a problem:
- Masque_Shadow
- GW2_UI
- oUF_Hank


This is the log error:
```
Finished dev [unoptimized Finished dev [unoptimized + debuginfo] target(s) in 0.29s
08:25:07.542 [ajour_core::parse][ERROR] fingerprinting failed for "/Applications/World of Warcraft/_retail_/Interface/AddOns/oUF_Hank": Unable to find file: "/Applications/World of Warcraft/_retail_/Interface/AddOns/oUF_Hank/config.lua"
08:25:07.543 [ajour_core::parse][ERROR] fingerprinting failed for "/Applications/World of Warcraft/_retail_/Interface/AddOns/Masque_Shadow": stream did not contain valid UTF-8
08:25:07.678 [ajour_core::parse][ERROR] fingerprinting failed for "/Applications/World of Warcraft/_retail_/Interface/AddOns/GW2_UI": Unable to find file: "/Applications/World of Warcraft/_retail_/Interface/AddOns/GW2_UI/libs/libs/LibStub/LibStub.lua"
```
Issue with `Masque_Shadow` is the authors name is not UTF-8 valid: `## Author: Fedorenko R.D. √Ä√¥√•√¨-√ó√•√∞√≠√ª√©√ò√∞√†√¨`.

Issue with `oUF_Hank` is that we try to find `/oUF_Hank/config.lua` but its called `/oUF_Hank/config.default.lua`
Issue with `GW2_UI` is that we try to find `/GW2_UI/libs/LibStub/LibStub.lua` but its located here `/GW2_UI/libs/libs/LibStub/LibStub.lua`

I think with this information we have enough to fix these bugs. Thanks for reporting @moggybaer.

**Comment by tarkah** [comment]
Hmm, obviously curse would have the same issues fingerprinting those files with the regex. Do you think they just skip over failed files and continue to fingerprint? I'm curious if we do that can we get a fingerprint match for those 2.

**Comment by brendanblackwood** [comment]
I maintain oUF_Hank and there are a couple issues there. First is that the original creator has oUF_Hank on curse, but hasn't been active since 2014 (why I've been updating it), but I don't own that project so I can't push to it. I've got it hosted on [curse](https://www.curseforge.com/wow/addons/ouf_hank_update), but that does present some naming issues. Secondly, as noted, there is a `config.default.lua`, but for the addon to run, you need to change that to `config.lua`. That's to prevent local customizations from being overwritten. I could move that to a db, but that's a ton of work and not really the idea behind oUF in the first place. Open to ideas, but it may not be a good fit for automatic updates 😢

**Comment by tarkah** [comment]
@brendanblackwood Thanks for commenting. I actually just tested out the fix I suggested right before your comment and it works! The fingerprint for `8.3.1-release` is `3241504627`

By skipping any files we can't find, such as the `config.lua`, I successfully generated the fingerprint `3241504627` instead of hitting an error. I'll open up a PR to get this patched.

**Comment by tarkah** [comment]
This appears to also work for GW2_UI, which I now get the correct fingerprint of `109141261`

**Comment by tarkah** [comment]
And I've fixed the error of fingerprinting failing on invalid UTF-8 and got the fingerprint of `4254243648` for Masque_Shadow which is correct! Pushing these changes now.

**Comment by moggybaer** [comment]
> I maintain oUF_Hank and there are a couple issues there. First is that the original creator has oUF_Hank on curse, but hasn't been active since 2014 (why I've been updating it), but I don't own that project so I can't push to it. I've got it hosted on [curse](https://www.curseforge.com/wow/addons/ouf_hank_update), but that does present some naming issues. Secondly, as noted, there is a `config.default.lua`, but for the addon to run, you need to change that to `config.lua`. That's to prevent local customizations from being overwritten. I could move that to a db, but that's a ton of work and not really the idea behind oUF in the first place. Open to ideas, but it may not be a good fit for automatic updates

Hello.  I am really sorry but i forgot the following when i opened the ticket:
The ouf hank installation is actually a fan update on wow interface https://www.wowinterface.com/downloads/info21474-oUF.
I suppose it is the version that you maintain?

My fault. Sorry :(

**Comment by brendanblackwood-transloc** [comment]
No worries. I've been maintaining it on wowinterface for a number of years, but recent put it up on curseforge to (hopefully) better handle shadowlands beta vs live in the same place.

**Comment by brendanblackwood** [comment]
No worries. I’ve been maintaining it on wowinterface for a number of years, but recent put it up on curseforge to (hopefully) better handle shadowlands beta vs live in the same place.
