### ISSUE TITLE
Missing 4 mods in my list.

### ISSUE THREAD

**Issue by Az0na** [casperstorm/ajour#148]
I looking for new mod manager sins twitch mod part gonna be gone to somewhere els.

Now in twitch mod manager I see 4 more addons then your manager sees.

Ajour says 68 Retail addons loaded.
Twitch shows 72 mods installed.

These for are not shown.
Simple Item Levels
Routes
LUI Core
ChatAlerts

I know Chat alerts is one I let be modified to fix a bug I dont know if that is reason but others rare orginal releases.

there some form wowinterface but I assume as they not picked up by twitch this one is not either.

**Comment by tarkah** [comment]
Thanks for the bug report! Yeah, currently any modifications to the addon will cause our fingerprinting to fail and no match to the curse API. Can you try a fresh install of the addons from curse and then delete your fingerprint cache located at `$HOME/.config/ajour/fingerprints.yml` macos/linux or `%APPDATA%/ajour/fingerprints.yml` windows, and then relaunch Ajour and see they still don't appear?

If they don't, can you then please paste the contents of `ajour.log` (same folder as fingerprints file) so we can inspect further?

**Comment by Az0na** [comment]
That explains alot. I know 2 of mods mentioned are edited to fit my UI or fix to addons because orignal out of date and buggy. Maybe there is way like twitch currently does show them as modified?

Currently gonna eat so Ill check those other 2 if they indeed modded to els ill try reinstall them.

**Comment by Az0na** [comment]
Okey I looked into the 4 mods.

3 are indeed modified with fixes as author probley dint play anymore to update. 1 got recently updated with alpha version so thats probley why that one isnt seen correctly.

So I gues if possible at status of mod you could set modified if addon is fount but doenst match with curse id? and can you setup somewhere you can pick alpha or checking for alpha/beta version of mods?

Looking forward for improvement and I bet this gonna be fine replacement for twitch when its gone over to overwolf.

**Comment by casperstorm** [comment]
You can follow along with the "unidentified/unknown" addition in the [Roadmap](https://github.com/casperstorm/ajour/projects/2#card-46592147).
