### ISSUE TITLE
Add Backup Directory Option for each WoW version ( Retail AND Classic)

### ISSUE THREAD

**Issue by moggybaer** [casperstorm/ajour#149]
**Is your feature request related to a problem? Please describe.**
No this is not a problem

**Describe the solution you'd like**
It would be very nice to be able to save the addons for retail and classic  in different directories 

**Describe alternatives you've considered**
An another solution would be to be able to identify the backups by their zip name. 
A prefix based on the version would be the a quick-win

**Comment by casperstorm** [comment]
Thanks for the feature request, @moggybaer.
Why exactly do you want to have two different directories? I am afraid of making a otherwise simple feature too complex.

**Comment by moggybaer** [comment]
I totally understand you point.  The quick-win we be 100% sufficient i think

**Comment by casperstorm** [comment]
For now I would like to keep it as is. To keep the simplicity, and make it easy understandable.
We might revisit this if it pops up multiple times. Again, thanks for reporting and please keep coming with these suggestions for making Ajour better.

I'll be marking this as closed for now.
