### ISSUE TITLE
Disable autoupdate of Ajour

### ISSUE THREAD

**Issue by Neurotoxin001** [casperstorm/ajour#150]
**Is your feature request related to a problem? Please describe.**
Yes, I want to control programs that I have on my PC

**Describe the solution you'd like**
Make option to disable autoupdate and button "Check for updates" that will ask "Do you want to update program?" (with changelog)

**Comment by casperstorm** [comment]
Ajour is not currently doing any auto update.
You have to press either `Update all` or `Update` on a single addon before we do any action.

Do you you want to have a confirmation before performing the action, when you have pressed one of the buttons?

**Comment by casperstorm** [comment]
Ajour won't autoupdate it self. When there is a new version it will say `New Ajour version available` and the present a Download button. If you press that button it will open a webpage with a download link you manually have to press in order to get the newest version.

**Comment by Neurotoxin001** [comment]
Ah, ok then
