### ISSUE TITLE
Missing Addon: Tip Tac

### ISSUE THREAD

**Issue by Cynfire** [casperstorm/ajour#151]
**Describe the bug**
The addon called TipTac is not visible in the addon list. 

**To Reproduce**
No steps needed. 

**Expected behavior**
The addon to be there?

**Screenshots**
![Missing addon TipTac](https://user-images.githubusercontent.com/72098585/94597626-cb3d3e00-025b-11eb-8172-c20ba14fc41a.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10 Pro
 - Ajour version: 0.3.4
 - (if applicable) Addon name, flavor (classic or retail) and version: Tip Tac, Retail, TipTac19.03.31

**Additional context**
Not that I can think of. 

**Log Output**
I don't think I need to post this, but let me know if I do.

Thank you!!

**Comment by casperstorm** [comment]
I just downloaded TipTac from [here curseforge](https://www.curseforge.com/wow/addons/tip-tac) and it shows up:
<img width="721" alt="Screenshot 2020-09-29 at 20 11 23" src="https://user-images.githubusercontent.com/2248455/94598904-f6da1b80-028f-11eb-97c6-eae46f1351ec.png">

You could try the following:
- Delete the addon
- Manually download the newest from [here](https://www.curseforge.com/wow/addons/tip-tac)
- Delete `fingerprints.yml` from `APPDATA%\ajour\fingerprints.yml`
- Start Ajour

**Comment by Cynfire** [comment]
That fixed it, Thank you!
