### ISSUE TITLE
Add ptr and beta folders support

### ISSUE THREAD

**Issue by jacobsenj** [casperstorm/ajour#152]
Currently only retail and classic folders get scanned. Would be nice if ptr and beta could be added.

![Screenshot 2020-09-29 211336](https://user-images.githubusercontent.com/399303/94605173-03af3d00-0299-11eb-8e1b-10ae88bd3f6d.png)

**Comment by casperstorm** [comment]
Thanks for the suggestion, @jacobsenj. This is actually on the roadmap: https://github.com/casperstorm/ajour/projects/2#card-45347975. I'll close this for now because of this.
