### ISSUE TITLE
Backup settings (interval/only wtf folder/etc)

### ISSUE THREAD

**Issue by AltBridge** [casperstorm/ajour#155]
**Is your feature request related to a problem? Please describe.**
Making a backup of the Interface and WTF folders both takes too long and eats up too much space. (250MB for me)

**Describe the solution you'd like**
Adding settings to the backup option: 
- Automatic backup on interval (daily/weekly/monthly)
- Only WTF folder or both Interface and WTF folders.
- Backup Retail or Classic or both.

**Comment by casperstorm** [comment]
Thanks for the suggestion @AltBridge.
I have added your feature to our Inbox in the roadmap: https://github.com/casperstorm/ajour/projects/2#card-46524241
