### ISSUE TITLE
Add the ability to install new addons from ajour

### ISSUE THREAD

**Issue by Darktortue** [casperstorm/ajour#159]
Would it be possible to have the ability to install addons directly from ajour ? I know that for now the main purpose is the updates but it would be cool to install, update and remove directly from it.

**Comment by casperstorm** [comment]
Hi @Darktortue,
This is a great feature, and it is something we have on our [roadmap](https://github.com/casperstorm/ajour/projects/2#card-44974362). I can't promise you when it's ready but we are working hard.
