### ISSUE TITLE
Automatic update of addons.

### ISSUE THREAD

**Issue by krazyito65** [casperstorm/ajour#161]
**Is your feature request related to a problem? Please describe.**
No, only a quality of life feature.

**Describe the solution you'd like**
Automatic updates of addons.  I think the main question to as would be *when*.  Do we do it every time we see an update? on a timer? I'm not that picky. 

I just want to be able to start the computer up, have ajour turn on with desktop start up, and automatically update addons before I get into the game.

**Comment by casperstorm** [comment]
Hey @krazyito65. Thanks for the suggestion.
So we had this discussion yesterday, and we are doing a two step rocket here where initially we are introducing system tray support: (https://github.com/casperstorm/ajour/projects/2#card-46420287). I think this addition will make the discussion about **when** to update all your addons easier.

**Comment by krazyito65** [comment]
I'm not sure how ethical it is for you to watch if wow process is running, im a lunix, do what I want on my machine programmer.. But if you could track when wow closes to make sure any updates are kicked off before it's open again, oukd be cool. 


Or everytime there's an update, that's fine, but then I know there's a lot of day1 bugs that mess people up. 

Saying that, let's make sure that option is off by default....

**Comment by casperstorm** [comment]
I have decided that now is not the time we want to introduce automatically update. I wont say it will never be implemented, but for now there are more important things to implement and enhance.
