### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by Ishayu** [casperstorm/ajour#162]
**Is your feature request related to a problem? Please describe.**
I didn't know how to install it on Manjaro (which is based on Arch Linux).

**Describe the solution you'd like**

```sh
sudo pamac install rustup 
```

If it points out there's a conflict with rust, install rustup anyway, removing rust.

Next, install a toolchain.

```sh
rustup install stable
```

```sh
rustup default stable
```

Then follow the standard build steps.

**Additional context**
By default all the necessary libraries seem to be installed, at least on Manjaro. This isn't too surprising as you do a lot of self-compiling on Arch and derivatives. Not 100% certain though, so a review might be good.

Can't figure out how to send the branch for a pull request. I just get a 403. But you can have this, hope that's OK.

**Comment by tarkah** [comment]
What error are you running into when you `cargo build --release` ?

**Comment by Ishayu** [comment]
rustup is not installed. This is a feature request to add that instruction to the readme file, not a bug. :)

It's a brilliant program and it works well on Linux. Good job!

**Comment by gageracer** [comment]
you can build it using aur

**Comment by fishxz** [comment]
how about a flatpak build?
would be the best way to cover linux

 https://flatpak.org/

**Comment by tarkah** [comment]
I've added an `AppImage` release #189 . I'll try to get the AppImage for 0.3.5 published to that release once @casperstorm is back online. I can link it in discord in the meantime

**Comment by masonnl** [comment]
fwiw, on Manjaro I was able to build from source using rustup (v1.22.1-1 [Official Repositories]) and its optional dependencies (lldb and gdb. The final bins installed for me looked like this:

![step 3](https://user-images.githubusercontent.com/4482337/94983724-ccdc5f80-0502-11eb-8ad4-0fa588d5978d.png)

Excited to have an AppImage! Thanks @tarkah

**Comment by tarkah** [comment]
Closing now that we have AppImage on our 0.3.5 release

https://github.com/casperstorm/ajour/releases/tag/0.3.5
