### ISSUE TITLE
Where is the executable location in Windows?

### ISSUE THREAD

**Issue by aucald** [casperstorm/ajour#169]
What is the default install location/folder in Windows (specifically Windows 10), I recently installed Ajour but it did not appear to create a Desktop or Start Menu shortcut, and I cannot seem to find it by searching either the Start Menu or my primary volume containing my Windows install.  A search for Ajour.exe returned no results, and even searching for "ajour datecreated:9/30/2020" reveals only the folder in AppData\Roaming that seems to be the various configuration files.

![AjourCapture](https://user-images.githubusercontent.com/46383958/94752475-5a7c4b80-0359-11eb-83f1-4c12d2f9761c.PNG)

**Comment by tarkah** [comment]
It currently doesn't install itself anywhere. So most likely it goes to your Downloads folder. Unless your browser didn't save the file and just ran it, then it's probably in some temp folder / deleted. I'd just re-download it and make sure it's saved somewhere you can run it.

**Comment by aucald** [comment]
That is indeed where it was, didn't know it was a standalone application, so to speak.  Thanks for the info and quick turnaround.
