### ISSUE TITLE
Import/export listing of installed addons

### ISSUE THREAD

**Issue by AltBridge** [casperstorm/ajour#172]
**Describe the solution you'd like**
A way to import/export the installed addons. (using a file that contains a list or so)
Would also be nice to **additionally** have the export be included in the backup option. (one zip file with the WTF folder and addon list file)

E.g.: accidentally lose all addons --> being able using the exported file and the WTF folder backup to get everything back without the need for having all addons backed up locally.

**Comment by Walkerbo** [comment]
Doesn't the current backup do this?
When I set the backup folder onto my Ddrive it zipped the interface and WTF folders for both the classic and retail.

**Comment by AltBridge** [comment]
> Doesn't the current backup do this?
> When I set the backup folder onto my Ddrive it zipped the interface and WTF folders for both the classic and retail.

That's the point, avoiding having to backup the addons when it could just be saved as a list to be imported later to save hdd space. Plus it enables people to share their installed addons easily.
