### ISSUE TITLE
Windows: Close to tooltip

### ISSUE THREAD

**Issue by jef** [casperstorm/ajour#174]
**Describe the solution you'd like**

Not necessary by any means, but it would be cool to run the process in the background and put as a tooltip (e.g. Discord, Twitch, etc.).

I believe this behavior is by default when you "close" the window in macOS, but not quit (<kbd>Cmd</kbd> + <kbd>Q</kbd>)

**Additional context**

This could also enable us to do automated updates.

**Comment by casperstorm** [comment]
We have sys tray support added to the [Roadmap](https://github.com/casperstorm/ajour/projects/2#card-46420287) @jef.
There are some upstream apis missing, but eventually we should be able to implement it.
