### ISSUE TITLE
Add a confirmation dialog when attempting to delete an addon.

### ISSUE THREAD

**Issue by kiraleos** [casperstorm/ajour#176]
**Is your feature request related to a problem? Please describe.**
Most software right now include a confirmation dialog when attempting to delete something, so it's become second nature to expect one, and it avoids potential unwanted deletions.

**Describe the solution you'd like**
When clicking the delete button for an addon, a dialog window pops up asking for confirmation.

**Comment by casperstorm** [comment]
There is currently no really good way of implementing a small tooltip/confirmation dialog in [Iced](https://github.com/hecrj/iced/).

I'll leave this open, because eventually we want this implemented.
If anyone have an idea, feel free to send me a PR with the solution.

**Comment by mattpson** [comment]
Maybe make a backup of the addon that is deleted so it can be reinstalled easily.

This will require a backup directory to be configured. If there isn't one then just keep the current behavior.
