### ISSUE TITLE
Ajour 0.3.5 for Windows is not signed

### ISSUE THREAD

**Issue by JasonDias** [casperstorm/ajour#183]
Please sign the executable

**Comment by casperstorm** [comment]
This unfortunately costs money, so is out of our scope right now.

Thanks for reporting.

**Comment by JasonDias** [comment]
The previous version did not trigger these warnings.

**Comment by JasonDias** [comment]
@casperstorm there must be something different about the way this exe was compiled, because the previous version 0.3.4 does not have this issue.

**Comment by casperstorm** [comment]
This was compiled on the same machine, with the same command.
You can try to compile it yourself to check if that changes anything. Description is located here [INSTALL.md](https://github.com/casperstorm/ajour/blob/master/INSTALL.md#clone-the-source-code).

Let me know what you find. So far I have learned that Windows Defender is totally random.
