### ISSUE TITLE
Cant find the Aardvark and Swarm addons

### ISSUE THREAD

**Issue by Walkerbo** [casperstorm/ajour#184]
_**Describe the bug**_
Hi 
I have the Aardvark and Swarm addons installed yet they do not show in the "My Addons" list.
Both of these addons do show as installed on the Twitch app.
I note that both of these addons work on both the current and classic versions.

_**To Reproduce**_
1. Install both Aardvark and Swarm addons
2. Run Ajour

_**Expected behavior**_
I expect to see the Aardvark and Swarm addons listed in the "Retail" list of installed addons.

**Screenshots**

_**Software involved**_
Please complete the following information:
1. Windows 10 x64
2. Ajour version: [e.g. "0.3.5
3. Addons - Aardvark - Swarm - Retail

_**Additional context**_

_**Log Output**_
13:50:00.069 [ajour][DEBUG] Ajour 0.3.5 has started.
13:50:00.096 [ajour_core::config][DEBUG] loading config
13:50:00.096 [ajour_core::theme][DEBUG] loading user themes
13:50:00.096 [ajour_core::utility][DEBUG] checking for application update
13:50:00.111 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
13:50:00.968 [ajour::gui::update][DEBUG] Message::Parse
13:50:00.968 [ajour::gui::update][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "C:\\Program Files (x86)\\World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        ignored: {
            Retail: [],
            Classic: [],
        },
        release_channels: {
            Retail: {},
            Classic: {},
        },
    },
    theme: None,
    column_config: V2 {
        columns: [
            ColumnConfigV2 {
                key: "title",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "local",
                width: Some(
                    153,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "remote",
                width: Some(
                    141,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "status",
                width: Some(
                    185,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "channel",
                width: Some(
                    85,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "author",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    110,
                ),
                hidden: true,
            },
        ],
    },
    window_size: Some(
        (
            1293,
            815,
        ),
    ),
    scale: None,
    backup_directory: None,
}
13:50:00.968 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\Interface/AddOns"
13:50:00.969 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_classic_\\Interface/AddOns"
13:50:00.969 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
13:50:00.969 [ajour::gui::update][DEBUG] Message::NeedsUpdate(None)
13:50:00.969 [ajour_core::parse][DEBUG] retail - parsing addons folder
13:50:00.969 [ajour_core::parse][DEBUG] classic - parsing addons folder
13:50:00.969 [ajour_core::parse][DEBUG] classic - 50 folders in AddOns directory to parse
13:50:00.970 [ajour_core::parse][DEBUG] retail - 274 folders in AddOns directory to parse
13:50:01.239 [ajour_core::parse][DEBUG] retail - 274 fingerprints: 274 cached, 0 calculated, 0 added, 0 removed
13:50:01.277 [ajour_core::parse][DEBUG] retail - 220 successfully parsed from '.toc'
13:50:01.277 [ajour_core::parse][DEBUG] retail - 0 addons with tukui id
13:50:01.277 [ajour_core::parse][DEBUG] retail - 0 addons applied with tukui id package metadata
13:50:01.277 [ajour_core::parse][DEBUG] retail - 220 unique fingerprints to check against curse api
13:50:01.278 [ajour_core::parse][DEBUG] classic - 50 fingerprints: 50 cached, 0 calculated, 0 added, 0 removed
13:50:01.291 [ajour_core::parse][DEBUG] classic - 49 successfully parsed from '.toc'
13:50:01.291 [ajour_core::parse][DEBUG] classic - 0 addons with tukui id
13:50:01.291 [ajour_core::parse][DEBUG] classic - 0 addons applied with tukui id package metadata
13:50:01.291 [ajour_core::parse][DEBUG] classic - 49 unique fingerprints to check against curse api
13:50:01.664 [ajour_core::parse][DEBUG] classic - 25 exact fingerprint matches against curse api
13:50:01.664 [ajour_core::parse][DEBUG] classic - 25 addons applied with fingerprint metadata
13:50:01.664 [ajour_core::parse][DEBUG] classic - 25 addons with curse id
13:50:02.109 [ajour_core::parse][DEBUG] retail - 129 exact fingerprint matches against curse api
13:50:02.109 [ajour_core::parse][DEBUG] retail - 129 addons applied with fingerprint metadata
13:50:02.109 [ajour_core::parse][DEBUG] retail - 129 addons with curse id
13:50:02.873 [ajour_core::parse][DEBUG] classic - 25 addons applied with curse id package metadata
13:50:02.873 [ajour_core::parse][DEBUG] classic - 25 addons successfully parsed
13:50:02.874 [ajour::gui::update][DEBUG] Message::ParsedAddons(classic, 25 addons)
13:50:03.106 [ajour_core::parse][DEBUG] retail - 128 addons applied with curse id package metadata
13:50:03.106 [ajour_core::parse][DEBUG] retail - 129 addons successfully parsed
13:50:03.110 [ajour::gui::update][DEBUG] Message::ParsedAddons(retail, 129 addons)
13:50:05.918 [ajour::gui::update][DEBUG] Interaction::FlavorSelected(classic)
13:50:22.215 [ajour::gui::update][DEBUG] Interaction::FlavorSelected(retail)
13:50:38.470 [ajour::gui::update][DEBUG] Interaction::Expand(AckisRecipeList_Alchemy)
13:50:44.409 [ajour::gui::update][DEBUG] Interaction::Expand(AckisRecipeList_Alchemy)
13:56:52.338 [ajour::gui::update][DEBUG] Interaction::Settings
13:56:53.012 [ajour::gui::update][DEBUG] Interaction::Settings

**Comment by casperstorm** [comment]
Hi @Walkerbo,

Currently Ajour does not work if any of the files in the an addon have been modified after installation. Reason is rely on comparing a fingerprinting towards CurseForge. I would assume the two mentioned addons have been modified, because if I download I do see them in Ajour.

<img width="884" alt="Screenshot 2020-10-02 at 08 06 19" src="https://user-images.githubusercontent.com/2248455/94892886-2eaab400-0486-11eb-8eb2-1b1bb53c280e.png">

I'll close this, but if you still can't get it to work feel free to reopen.
