### ISSUE TITLE
Mass release channel switch

### ISSUE THREAD

**Issue by Darhel** [casperstorm/ajour#185]
Its possible to add mass release channel switch button, to switch all addons at one click? 
Thanks anyway for great software.

**Comment by casperstorm** [comment]
Thank you so much for contributing with a feature request.

We talked about adding this, but I decided it was too niche.
For now you'll have to do it per addon, but that will however be saved so you only have to do it once.

I'll might reconsider it once we are more feature complete, but for now this will not be added to the roadmap.
