### ISSUE TITLE
What to do with non-matched addons?

### ISSUE THREAD

**Issue by casperstorm** [casperstorm/ajour#19]
If a addon does not have either a `curse_id`, `wowi_id` or `tuk_id` I can't match it against any API. What to do with those, visually?

Example:
<img width="500" alt="Screenshot 2020-08-14 at 15 53 15" src="https://user-images.githubusercontent.com/2248455/90256667-539b8700-de46-11ea-8e07-04e6c86f94b5.png">

Notice: `AngryNotes` and `AddonSkins`. They don't have any id's to any repository so i've just added `-` to the remote version for now.

Do you have any input, @mlablah?

**Comment by mlablah** [comment]
I think there are two issues at play.
1) How should unrecognized addons be displayed?
2) Should we only try and match addons using their ID from the toc file, if one is present?

Regarding #1 I think your solution of adding "-" to the second column is fine. Though I think the columns could use some titles. Eg. "Your version" and "Latest version" or something similar.

Regarding #2 I noticed that Angry Notes is hosted on Curseforge (https://www.curseforge.com/wow/addons/angry-notes). Maybe as a fall back, if no ID's are present, do a textual search based on Title (without web colors). 

Do the APIs (curse/wowi/tukui) support that?

**Comment by casperstorm** [comment]
> Regarding #1 I think your solution of adding "-" to the second column is fine. Though I think the columns could use some titles. Eg. "Your version" and "Latest version" or something similar.

I'll create a separate issue on this, and make that happen.

> Regarding #2 I noticed that Angry Notes is hosted on Curseforge (https://www.curseforge.com/wow/addons/angry-notes). Maybe as a fall back, if no ID's are present, do a textual search based on Title (without web colors).

Yeah, so right now i am using https://addons-ecs.forgesvc.net/api/v2/addon/2382 for curse, where `2382` is an id found in the `.toc` file. That API, as far as i know, only works with that API. However later I would make sense to have a fallback solution with another API where i can search for a addon by slug/name.
