### ISSUE TITLE
Window size issues with scaling on Linux

### ISSUE THREAD

**Issue by tarkah** [casperstorm/ajour#190]
**Describe the bug**
I noticed that when I have scaling applied (for example, 1.20) and I close the application and then re-open, the window size increases by that 20%. Same goes when scale is < 1.0, window size shrinks each time.

**To Reproduce**
1. On linux, increase / decrease scale
2. Close window
3. Reopen window
4. Repeat

**Expected behavior**
Window size is consistent between sessions

**Software involved**
Please complete the following information:
 - OS: Linux (Solus OS)
 - Ajour version: 0.3.5

**Additional context**
Totally caused by this, which was a workaround to get things playing nicely on Windows, but obviously has different behaviour on linux. Though it's unknown if its just a problem on Gnome based DE or Plasma as well... Does this happen on mac?

https://github.com/casperstorm/ajour/blob/442e9b9963d5b94315d5170ec4a2c9393b1379de/src/gui/update.rs#L913-L917

I can fix this w/ conditional compilation, we just need to test on each platform / multiple linux DEs to make sure we understand where it's happening.

**Comment by tarkah** [comment]
So actually, the issue isn't with the width / height adjustment above, this works the same on linux as well, I confirmed the window size saved to the config is the same regardless of scale for the same window size.

It seems like what is happening is when the app first launches, it loads the correct window size. But then the scale gets applied, which for some reason on linux, causes a resize event to occur. Which then goes to the `Message::RuntimeEvent(iced_native::Event::Window` and then sets the window size incorrectly this time, because in reality the size hasn't changed, but the scale offset screws it up. So then when we launch AGAIN, that messed up size takes effect, and then the whole cycle repeats itself.

Weird this "resize" message comes across on first bootup, but not when scale change occurs by the user. Not quite sure how to tackle this one currently

**Comment by tarkah** [comment]
Ahh, so the "random" resize event on bootup doesn't seem related to the scale setting at all. Even on 1.0 scale, it still comes across right after the app is launched. Need to figure out how to ignore this message on linux.

**Comment by tarkah** [comment]
Somewhat related but unrelated... the scale isn't perfectly rounded off. It got saved as `0.9999999999999992`. So even at "1.0" scale, the windows slowly resizes over time if I keep closing / opening the app.

**Comment by mlablah** [comment]
Adding comment made by Bykow a while ago on Discord, who suggested a fix for the rounding errors caused by our use of floats.

```A trick to avoid that would be using u_16 (or u_8 or u_32 depending or your level of paranoia :wink: ) with natural numbers and then simply use a division of 10 to render it.```

In other words. Instead of storing the scale factor as a float. Keep it as an integer and only convert it to float (and divide by 10) before it is applied. With the current allowed values being between 0.5 and 2, that means migrating to 5-20 and adding/subtracting 1 instead to the integer value instead.

**Comment by tarkah** [comment]
Ahh yes, thanks for linking that here. That should definitely be folded in to whatever future fix we apply here (if not before).

**Comment by tarkah** [comment]
@mlablah I've kept the scale as f64 as to not break our config file, but still was able to resolve the issue by "rounding" it to 1 decimal place...

```rust
ajour.scale_state.scale = ((prev_scale + 0.1).min(2.0) * 10.0).round() / 10.0;
```

Definitely learned something about floating point arithmetic :package: 

And I also found a fix for the underlying issue I was having, so yay!
