### ISSUE TITLE
Dynamic WoW Install Path Resolution

### ISSUE THREAD

**Issue by ianmarmour** [casperstorm/ajour#194]
**Is your feature request related to a problem? Please describe.**
When adding your world of Warcraft folder if you select the interface addon folder or the _retail or _classic folders the app will not work. I assume this leads to user confusion.

**Describe the solution you'd like**
Make best effort attempts at determining path resolution from relative paths.

**Describe alternatives you've considered**
Use a popup modal to inform the user of an invalid directory or restrict the input locations in some way.

**Additional context**
This isn't a major concern but it does seem like a nice UX improvement to the program.

**Comment by mlablah** [comment]
@ianmarmour : Agreed. This would improve the UX.

Put another way:
If the path the user has chosen ends with either one of these:
```
/(_retail_|_classic_)/Interface/AddOns
/(_retail_|_classic_)/Interface
/(_retail_|_classic_)
```

Truncate that part before we start joining to it here:
https://github.com/casperstorm/ajour/blob/442e9b9963d5b94315d5170ec4a2c9393b1379de/crates/core/src/config/mod.rs#L46

Tip: ignore case when testing for the above strings.

**Comment by casperstorm** [comment]
We should add the logic to this function:

https://github.com/casperstorm/ajour/blob/442e9b9963d5b94315d5170ec4a2c9393b1379de/src/gui/update.rs#L242

This is where (L250) we save the path. Before that we need to have the correct path.

**Comment by Histre** [comment]
Mac OS 10.15.6,  Install 0.3.5 would not recognize file path and showed no addons were installed from any file path selected.

**Comment by casperstorm** [comment]
@Histre this issue is fixed in https://github.com/casperstorm/ajour/pull/198.
It will go out in this week.
