### ISSUE TITLE
No update without available alpha version on alpha release channel

### ISSUE THREAD

**Issue by Dairyman** [casperstorm/ajour#199]
**Describe the bug**
Will not show available update when addon release channel is set to alpha, current version is an outdated stable version. And the addon has not any alpha versions OR has alpha versions but no beta.

**To Reproduce**
1. Set an Addon with a stable update, without an alpha or beta version to alpha

**Expected behavior**
Displays that an update is available.

**Software involved**
Please complete the following information:
 - OS: macOS 10.15.7
 - Ajour version: 0.3.5

**Comment by Ruffz** [comment]
It seems similar of what I've encountered #186

**Comment by casperstorm** [comment]
I'll try to reproduce this later today. Thanks both.

**Comment by Ruffz** [comment]
"Auctionator" addon actually permit to reproduce the issue

Set to "Alpha" show Local & Remote version "Alpha 347 (3 days ago)"  = Click "Update" install "Alpha 347"
then
Set to "Beta" show Local version "Alpha 347 (3 days old)" & Remote version "8.3.4 (17 Hours Ago)" = Click "Update" install "8.3.4"
then
Set to "Stable" show Local & Remote version "8.3.4 (17 Hours Ago)" = Click "Update" install "8.3.4" again
then
Set to "Beta" show Local & Remote version "8.3.4 (17 Hours Ago)" = Click "Update" install 8.3.4 again
then
Set to "Alpha" show Local & Remote version "8.3.4 (17 Hours Ago)" = Click "Update" install "Alpha 347" again


After a while "Alpha" stop showing & installing "Alpha 347",  but "Beta" always show "Update" even when "8.3.4" is already installed via "Stable"

**Comment by casperstorm** [comment]
Fixed in #208. Will be released in the next release.

**Comment by Ruffz** [comment]
"fix: selects stable if newer than alpha " ignore Beta release, happened today with Moveanything addon, I had to set it on Beta to get the "Update".
