### ISSUE TITLE
Commandline Support / Switches

### ISSUE THREAD

**Issue by sim7tynine** [casperstorm/ajour#200]
**Is your feature request related to a problem? Please describe.**
Just a wish since i backup and start my WoW Data with a PowerShell Script.

**Describe the solution you'd like**
I would like to have an option in the commandline for example to call options directly when starting the app. For example "ajour.exe /updateall" so i dont need to click manually :)

**Additional context**
Btw. its a super fast small client, really love it

**Comment by casperstorm** [comment]
We have recently split Ajour into a core- and a gui-package with exactly this purpose; using the core of Ajour without a GUI (for CLI like you mention) or with a third party GUI. More work is still needed, but we are going to get this functionality eventually.
