### ISSUE TITLE
appimage does not work "execv error"

### ISSUE THREAD

**Issue by somesortofrescuetoaster** [casperstorm/ajour#202]
**Describe the bug**
When trying to run the ajour.AppImage file:
$ ./ajour.AppImage 
execv error: No such file or directory

**To Reproduce**
1. Download ajour.AppImage
2. $ chmod a+x ajour.AppImage
3. $ ./ajour.AppImage

**Expected behavior**
should start ajour

**Software involved**
Please complete the following information:
 - OS: ubuntu 20.04
 - Ajour version: 0.3.5

**Comment by tarkah** [comment]
Interesting. I tested on a fresh live image of Ubuntu 20.04 and it worked. Let me try to figure out why that error would be occuring.

**Comment by tarkah** [comment]
Just to confirm, you're downloading the AppImage from the 0.3.5 release, not one of the older files uploaded in the discord?

**Comment by somesortofrescuetoaster** [comment]
Correct.  0.3.5 from the releases page.

**Comment by casperstorm** [comment]
I just re-tested and I can confirm the image works on a fresh Manjaro installation.

**Comment by somesortofrescuetoaster** [comment]
Is there something stupid I am doing?  From what I understand of appimage, you just need to make it executable to run it.   Though I have no idea what the "execv error: No such file or directory" is trying to tell me.

I've tested it on my three different ubuntu 20.04 systems: my desktop that I actually play wow on, my laptop, and my office VM at my location of work.

**Comment by tarkah** [comment]
Yeah I'm scratching my head at how it's not working for you, and not just on one system, but 3. And also using the same distro that I've successfully tested on from a Live Image (no updates / additional packages installed). So weird.

And yeah, I'm just downloading -> making executable -> running.

**Comment by tarkah** [comment]
@somesortofrescuetoaster can you check to see if a ~/.config/ajour/ajour.log file exists? If so, can you paste the contents here. I doubt it will, but just in case it's launching and crashing on startup

**Comment by tarkah** [comment]
My only other thought is that the download is corrupted from GitHub. I've actually seen this happen before. Can you tell me what the md5sum of the file is?

**Comment by tarkah** [comment]
Another thing I found... It seems like `AppImage` may not work if you don't have FUSE installed, check this out:

https://github.com/AppImage/AppImageKit/wiki/FUSE#install-fuse

**Comment by somesortofrescuetoaster** [comment]
0.4 worked.  The regular version worked on my wow desktop pc, but not my laptop.  The opengl version worked on my laptop.

**Comment by tarkah** [comment]
Glad it's now working! 

`4ee890e292df7d4b5b2a0ffafb6b8772` matches my md5sum for 0.3.5, so I am a little lost on why it wasn't working but now 0.4.0 is?? We changed nothing about the `AppImage` generation process. Anyway, it's working so I'm going to go ahead and close this now.
