### ISSUE TITLE
Ajour not recognizing Mod - "TradeSkillMaster_AppHelper"

### ISSUE THREAD

**Issue by mia-elora** [casperstorm/ajour#207]
**Describe the bug**
One of the installed mods I had on Twitch/Curse, TradeSkillMaster_AppHelper, does not show in the mod list of Ajour.

**To Reproduce**
1. Install mod in appropriate folder.
2. Open Ajour, scratch head.

**Expected behavior**
I expected the mod to show up in the list with the other 50+ mods I have installed, currently.

**Screenshots**
Screenshots available on request.

**Software involved**
Please complete the following information:
 - OS: Win10
 - Ajour version: 0.4.0 (and earlier releases)
 - Mod: TradeSkillMaster_AppHelper ver. 4.0.8 - Retail 

**Additional context**
     Note that TradeSkillMaster_AppHelper requires the primary TradeSkillMaster Mod to function.  They are listed as separate mods in the curse database, and were listed as separate mods in Twitch UI.

**Log Output**
20:51:27.694 [ajour][DEBUG] Ajour 0.4.0 has started.
20:51:27.695 [ajour::gui][DEBUG] antialiasing: true
20:51:27.702 [ajour_core::config][DEBUG] loading config
20:51:27.702 [ajour_core::utility][DEBUG] checking for application update
20:51:27.702 [ajour_core::theme][DEBUG] loading user themes
20:51:27.702 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
20:51:27.960 [ajour::gui::update][DEBUG] Message::Parse
20:51:27.960 [ajour::gui::update][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "C:\\Program Files (x86)\\World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        ignored: {
            Retail: [],
        },
        release_channels: {
            Retail: {},
        },
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: Some(
        (
            1080,
            1856,
        ),
    ),
    scale: Some(
        1.3000000000000003,
    ),
    backup_directory: Some(
        "C:\\Program Files (x86)\\World of Warcraft\\Ajour Backup",
    ),
}
20:51:27.960 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\Interface/AddOns"
20:51:27.961 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_classic_\\Interface/AddOns"
20:51:27.961 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
20:51:27.961 [ajour_core::parse][DEBUG] retail - parsing addons folder
20:51:27.961 [ajour_core::parse][DEBUG] classic - parsing addons folder
20:51:27.961 [ajour_core::parse][DEBUG] retail - 186 folders in AddOns directory to parse
20:51:27.964 [ajour::gui::update][ERROR] Message::ParsedAddons(classic) - Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_classic_\\Interface/AddOns"
20:51:27.964 [ajour::gui::update][DEBUG] Message::LatestBackup(None)
20:51:28.145 [ajour_core::parse][DEBUG] retail - 186 fingerprints: 186 cached, 0 calculated, 0 added, 0 removed
20:51:28.169 [ajour_core::parse][DEBUG] retail - 186 successfully parsed from '.toc'
20:51:28.169 [ajour_core::parse][DEBUG] retail - 0 addons with tukui id
20:51:28.169 [ajour_core::parse][DEBUG] retail - 0 addons applied with tukui id package metadata
20:51:28.169 [ajour_core::parse][DEBUG] retail - 186 unique fingerprints to check against curse api
20:51:28.169 [ajour::gui::update][DEBUG] Message::NeedsUpdate(None)
20:51:28.462 [ajour_core::parse][DEBUG] retail - 53 exact fingerprint matches against curse api
20:51:28.463 [ajour_core::parse][DEBUG] retail - 53 addons applied with fingerprint metadata
20:51:28.463 [ajour_core::parse][DEBUG] retail - 53 addons with curse id
20:51:28.652 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(8582 addons in catalog)
20:51:28.826 [ajour_core::parse][DEBUG] retail - 53 addons applied with curse id package metadata
20:51:28.826 [ajour_core::parse][DEBUG] retail - 53 addons successfully parsed
20:51:28.828 [ajour::gui::update][DEBUG] Message::ParsedAddons(retail, 53 addons)
20:51:37.418 [ajour::gui::update][DEBUG] Interaction::Expand(TradeSkillMaster)

**Comment by casperstorm** [comment]
Hi @mia-elora,

The reason TradeSkillMaster_AppHelper is not shown is because the TSM client populates a database inside the TSM_AppHelper addon folder. And currently Ajour does not support any modifications to addon folders.

The reason Ajour does not currently support modified addon folders is that we rely on a fingerprinting system so when you modify a folder, or the content inside, it generates a new fingerprint which the API don't recognises (because who knows what you have changed).   

Eventually we will roll out a feature which will handle this, but for now it is not something we plan to support right around the corner.
