### ISSUE TITLE
Catalog Sort by Date Added

### ISSUE THREAD

**Issue by NoobTaco** [casperstorm/ajour#210]
Would it be possible to add a sort by date added? I love to browse the addons sections of Curse and Wowinterface to see what addons have been added or updated. Would be nice to do that from the addon.

**Comment by mlablah** [comment]
This might require adding support for optional/reordered columns to the catalog as well. 

If we do that it would make sense to make `Description`, `Source` and `# Downloads` optional as well (though on by default).

One obstacle to that is that we don't currently cache `dateCreated`, `dateReleased` or `dateModified` attributes in the catalog json.

**Comment by KestrelWild** [comment]
+1
