### ISSUE TITLE
Catalog Downloading state getting stuck

### ISSUE THREAD

**Issue by jimnordb** [casperstorm/ajour#215]
**Describe the bug**
Catalog - installing Addon with missing stable channel causing it to halt on "downloading" state

15:48:23.294 [ajour::gui::update][DEBUG] Message::ParsedAddons(classic, 52 addons)
15:48:28.732 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Catalog)
15:49:37.538 [ajour::gui::update][DEBUG] Interaction::CatalogInstall(Curse, classic, 399223)
15:49:37.657 [ajour::gui::update][ERROR] No stable file found for curse id 399223

The addon i tried to install.
https://www.curseforge.com/wow/addons/softres/files

**To Reproduce**
Catalog -> Search "Softres" > Install the one with about 2k Downloads by clicking "Classic"

**Expected behavior**
Should leave downloading state

**Screenshots**
![image](https://user-images.githubusercontent.com/17293360/95472141-f5d97600-0982-11eb-84f0-5236ac6f0a0e.png)

**Software involved**
Windows 10 - 2004
Ajour 0.4.0 Release

**Log Output**
[ajour.log](https://github.com/casperstorm/ajour/files/5348562/ajour.log)

**Comment by tarkah** [comment]
Thanks for the bug report! Great catch. This will be an easy fix.
