### ISSUE TITLE
Add WoWInterface as an addon source

### ISSUE THREAD

**Issue by Walkerbo** [casperstorm/ajour#224]
_**Is your feature request related to a problem? Please describe.**_
I have to update addons that are exclusive to WoWInterface manually.

_**Describe the solution you'd like**_
If possible I would like to have WoWInterface included as an addon source.

**Comment by cynthiawoodard** [comment]
+1

**Comment by casperstorm** [comment]
I'll look into adding wowinterface addons. Can you link the exclusive addons just so I have them to test with?

**Comment by KestrelWild** [comment]
These are two I recently realized were only wowinterface:

https://www.wowinterface.com/downloads/info21263-AltzUIforBFA.html

https://www.wowinterface.com/downloads/info16068-RealUI.html

**Comment by Walkerbo** [comment]
Another one that is exclusive to wowinterface 
https://www.wowinterface.com/downloads/info7158

**Comment by casperstorm** [comment]
> Another one that is exclusive to wowinterface
> https://www.wowinterface.com/downloads/info7158

That one is on Curse: https://www.curseforge.com/wow/addons/quartz
