### ISSUE TITLE
Add wow-pro support

### ISSUE THREAD

**Issue by SkunkGuru** [casperstorm/ajour#228]
hi,
is possible to support wow-pro addon ?

https://www.wow-pro.com/addon/

great job !

**Comment by SkunkGuru** [comment]
Hi,
i see that now wow-pro is found on curse  ( https://www.curseforge.com/wow/addons/wow-pro )
but site says "IMPORTANT - THE VERSION ON CURSE.COM DOES NOT HAVE ALL THE ADDONS!
In order for our addon and it's community to thrive, we need people to visit our website, WoW-Pro.com."

You should link directly on that site

**Comment by mlablah** [comment]
> i see that now wow-pro is found on curse ( https://www.curseforge.com/wow/addons/wow-pro )
> but site says "IMPORTANT - THE VERSION ON CURSE.COM DOES NOT HAVE ALL THE ADDONS!
> In order for our addon and it's community to thrive, we need people to visit our website, WoW-Pro.com."
> 
> You should link directly on that site
The description on that CurseForge link has been updated. It now directs people to a discord server for the latest updates. This is not something we can use as a source for updates or new installs inside Ajour. 

But even if the wow-pro.com website had an API similar to what CurseForge, WowInterface or TukUI have, it would be a lot of effort for us to support a single addon which is already available, in some form elsewhere. Effort we would rather spend on improving or TukUI support, and adding WoWinterface support.
