### ISSUE TITLE
Set default preferred release type

### ISSUE THREAD

**Issue by KestrelWild** [casperstorm/ajour#231]
Would love to have the ability to set my preferred release type for all addons as beta, or at least, for all newly installed addons.

**Comment by casperstorm** [comment]
Hi @KestrelWild,

I talked about this feature a [little while ago](https://github.com/casperstorm/ajour/issues/185) so I am just gonna quote myself:

> We talked about adding this, but I decided it was too niche.
For now you'll have to do it per addon, but that will however be saved so you only have to do it once.
>
> I'll might reconsider it once we are more feature complete, but for now this will not be added to the roadmap.

We are a little further now, so I did note it down in my personal notes 🙂
