### ISSUE TITLE
Global setting to automatically select actual latest version

### ISSUE THREAD

**Issue by tordenflesk** [casperstorm/ajour#236]
**Is your feature request related to a problem? Please describe.**
Manually going through every addon to check whether there's an alpha/beta available and determine if it's newer than the release version is incredibly tedious.

**Describe the solution you'd like**
Drop-down to select globally preferred release type, and recognize newer release/beta versions as upgrades to an alpha version

**Describe alternatives you've considered**
CurseBreaker does this.

**Comment by casperstorm** [comment]
I added this feature to the [roadmap](https://github.com/casperstorm/ajour/projects/2#card-47250433) since it was requested a few times prior to this: https://github.com/casperstorm/ajour/issues/185, https://github.com/casperstorm/ajour/issues/231.
