### ISSUE TITLE
Export/Backup Addons as list

### ISSUE THREAD

**Issue by Urganot** [casperstorm/ajour#238]
**Is your feature request related to a problem? Please describe.**
When Backing Up my interface, it takes a long time because of the file size.
Copying my interface to a new pc is really time-consuming.

**Describe the solution you'd like**
A solution I could see is to generate a list of all addons and backing this up. this will drastically reduce the file size. Ofc the "WTF"-folder needs to be kept as is.
Ajour should also be able to export/import this list to easily send someone else the addon list.

**Comment by AltBridge** [comment]
Identical to https://github.com/casperstorm/ajour/issues/172

**Comment by casperstorm** [comment]
Closed in favor for the previously mentioned.
