### ISSUE TITLE
Addons shown that should be hidden

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#24]
Ajour attempts to present a list of addons with exactly 1 entry per downloaded addon. This means some filtering needs to take place in order to hide "sub addons" that only function as library/helper addons.

Today Ajour decides which addons should be shown in the list based on whether or not the toc file contains a row with: "## Version:"

This is a good first approximation, however...

A few addon authors don't have a Version line in their toc file, resulting in rare false negatives. Eg. Details!, Kui Nameplates, NameplateCooldowns and WorldQuestTracker.

Worse still is that many more addons have Version lines in the toc files of their library/helper addons, resulting in many false positives. Eg. Healbot, NeatPlates, Altoholic, SilverDragon, AtlasLoot, Grid2, TitanPanel and WeakAuras.

To address this last issue I propose a second rule to filter additional addons:
If an addon has a version, only show it if none of its linked addons have titles that are substrings of its own title.

Eg. don't show AtlasLoot_Cataclysm because it's linked to AtlasLoot which is a substring of AtlasLoot_Cataclysm.

It's not a perfect fix, since it will hide some addons that are separate downloads (eg. DBM-BrokenIsles), but the resulting list should be much closer to a 1-1 match.

**Comment by casperstorm** [comment]
I've updated the logic. This should hopefully yield a much better result: https://github.com/casperstorm/ajour/pull/25/commits/dd128c48ad436719cd89a556cb41420e444e57ff#diff-2daeb214043bf0d7e2c578ea98678a20R147-R158
