### ISSUE TITLE
Unable to load list of currently installed addons

### ISSUE THREAD

**Issue by ascott18** [casperstorm/ajour#240]
**Describe the bug**
Upon opening the app, it displays "Loading... currently parsing addons" for a few seconds, followed by "You have no <retail/classic> addons". It used to work, and I most certainly do have many addons installed.

**To Reproduce**
Open the app

**Expected behavior**
List of installed addons is loaded.

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.4.1

**Log Output**
```
17:26:34.687 [ajour][INFO] Ajour 0.4.1 has started.
17:26:34.689 [ajour::gui][DEBUG] antialiasing: true
17:26:34.702 [ajour_core::config][DEBUG] loading config
17:26:34.702 [ajour_core::utility][DEBUG] checking for application update
17:26:34.702 [ajour_core::theme][DEBUG] loading user themes
17:26:34.703 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
17:26:35.374 [ajour::gui::update][DEBUG] Message::Parse
17:26:35.374 [ajour::gui::update][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "C:\\Games\\World Of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        ignored: {
            Retail: [],
            Classic: [],
        },
        release_channels: {},
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: Some(
        (
            900,
            823,
        ),
    ),
    scale: None,
    backup_directory: None,
}
17:26:35.374 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Games\\World Of Warcraft\\_retail_\\Interface/AddOns"
17:26:35.374 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Games\\World Of Warcraft\\_classic_\\Interface/AddOns"
17:26:35.374 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
17:26:35.374 [ajour::gui::update][DEBUG] Message::NeedsUpdate(None)
17:26:35.376 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(974 addons in catalog)
17:26:35.379 [ajour_core::parse][DEBUG] retail - parsing addons folder
17:26:35.379 [ajour_core::parse][DEBUG] classic - parsing addons folder
17:26:35.379 [ajour_core::parse][DEBUG] classic - 114 folders in AddOns directory to parse
17:26:35.379 [ajour_core::parse][DEBUG] retail - 224 folders in AddOns directory to parse
17:26:35.572 [ajour_core::parse][DEBUG] retail - 224 fingerprints: 224 cached, 0 calculated, 0 added, 0 removed
17:26:35.588 [ajour_core::parse][DEBUG] retail - 172 successfully parsed from '.toc'
17:26:35.588 [ajour_core::parse][DEBUG] retail - 0 addons with tukui id
17:26:35.588 [ajour_core::parse][DEBUG] retail - 0 addons applied with tukui id package metadata
17:26:35.588 [ajour_core::parse][DEBUG] retail - 172 unique fingerprints to check against curse api
17:26:35.599 [ajour_core::parse][DEBUG] classic - 114 fingerprints: 114 cached, 0 calculated, 0 added, 0 removed
17:26:35.612 [ajour_core::parse][DEBUG] classic - 114 successfully parsed from '.toc'
17:26:35.612 [ajour_core::parse][DEBUG] classic - 0 addons with tukui id
17:26:35.612 [ajour_core::parse][DEBUG] classic - 0 addons applied with tukui id package metadata
17:26:35.612 [ajour_core::parse][DEBUG] classic - 114 unique fingerprints to check against curse api
17:26:38.892 [ajour::gui::update][ERROR] Message::ParsedAddons(classic) - invalid type: null, expected struct File at line 1 column 24149
17:26:57.989 [ajour::gui::update][ERROR] Message::ParsedAddons(retail) - invalid type: null, expected struct File at line 1 column 60

```

**Comment by ascott18** [comment]
Similar to #239, but I'm not getting any errors on failed API calls to tukui.org and do not have any TukUI addons installed at all.

**Comment by ejtbrown** [comment]
Seeing the same thing. Last line from the log is

```
20:16:57.502 [ajour::gui::update][ERROR] Message::ParsedAddons(retail) - invalid type: null, expected struct File at line 1 column 61
```

Present addon list is:
Ace3
AckisRecipeList
Altoholic
Altoholic_Achievements
Altoholic_Agenda
Altoholic_Characters
Altoholic_Grids
Altoholic_Guild
Altoholic_Search
Altoholic_Summary
AstralKeys
Auctionator
Bartender4
BattlePetBreedID
BindPad
Broker_CombatDuration
Broker_Money
'!BugGrabber'
CollectionShop
Coordinates
CT_BarMod
CT_BottomBar
CT_BuffMod
CT_Core
CT_ExpenseHistory
CT_Library
CT_MailMod
CT_MapMod
CT_PartyBuffs
CT_RaidAssist
CT_Timer
CT_UnitFrames
CT_Viewport
DataStore
DataStore_Achievements
DataStore_Agenda
DataStore_Auctions
DataStore_Characters
DataStore_Containers
DataStore_Crafts
DataStore_Currencies
datastore_garrisons
DataStore_Garrisons
DataStore_Inventory
DataStore_Mails
DataStore_Pets
DataStore_Quests
DataStore_Reputations
DataStore_Spells
DataStore_Stats
DataStore_Talents
DBM-AntorusBurningThrone
DBM-AQ20
DBM-AQ40
DBM-Argus
DBM-Azeroth
DBM-Azeroth-BfA
DBM-BaradinHold
DBM-BastionTwilight
DBM-BlackrockFoundry
DBM-BlackTemple
DBM-BlackwingDescent
DBM-Brawlers
DBM-BrokenIsles
DBM-BWL
DBM-CastleNathria
DBM-Challenges
DBM-ChamberOfAspects
DBM-Core
DBM-CrucibleofStorms
DBM-DefaultSkin
DBM-DMF
DBM-Draenor
DBM-DragonSoul
DBM-EmeraldNightmare
DBM-EternalPalace
DBM-Firelands
DBM-GarrisonInvasions
DBM-GUI
DBM-HeartofFear
DBM-HellfireCitadel
DBM-Highmaul
DBM-Hyjal
DBM-Karazhan
DBM-MC
DBM-MogushanVaults
DBM-Nighthold
DBM-Nyalotha
DBM-Outlands
DBM-Pandaria
DBM-Party-BfA
DBM-Party-Shadowlands
DBM-Scenario-MoP
DBM-Serpentshrine
DBM-SiegeOfOrgrimmarV2
DBM-SpellTimers
DBM-StatusBarTimers
DBM-Sunwell
DBM-TerraceofEndlessSpring
DBM-TheEye
DBM-ThroneFourWinds
DBM-ThroneofThunder
DBM-TimelessIsle
DBM-TombofSargeras
DBM-TrialofValor
DBM-Uldir
DBM-WorldEvents
DBM-ZuldazarRaid
DeathNote
Fortress
GarajalAnnounce
Grail
Grail-Achievements
Grail-NPCs-_classic_
Grail-NPCs-_classic_-deDE
Grail-NPCs-_classic_-enUS
Grail-NPCs-_classic_-esES
Grail-NPCs-_classic_-esMX
Grail-NPCs-_classic_-frFR
Grail-NPCs-_classic_-itIT
Grail-NPCs-_classic_-koKR
Grail-NPCs-_classic_-ptBR
Grail-NPCs-_classic_-ruRU
Grail-NPCs-_classic_-zhCN
Grail-NPCs-_classic_-zhTW
Grail-NPCs-_retail_
Grail-NPCs-_retail_-deDE
Grail-NPCs-_retail_-enUS
Grail-NPCs-_retail_-esES
Grail-NPCs-_retail_-esMX
Grail-NPCs-_retail_-frFR
Grail-NPCs-_retail_-itIT
Grail-NPCs-_retail_-koKR
Grail-NPCs-_retail_-ptBR
Grail-NPCs-_retail_-ruRU
Grail-NPCs-_retail_-zhCN
Grail-NPCs-_retail_-zhTW
Grail-Quests-_classic_
Grail-Quests-_classic_-deDE
Grail-Quests-_classic_-enUS
Grail-Quests-_classic_-esES
Grail-Quests-_classic_-esMX
Grail-Quests-_classic_-frFR
Grail-Quests-_classic_-itIT
Grail-Quests-_classic_-koKR
Grail-Quests-_classic_-ptBR
Grail-Quests-_classic_-ruRU
Grail-Quests-_classic_-zhCN
Grail-Quests-_classic_-zhTW
Grail-Quests-deDE
Grail-Quests-enUS
Grail-Quests-esES
Grail-Quests-esMX
Grail-Quests-frFR
Grail-Quests-itIT
Grail-Quests-koKR
Grail-Quests-ptBR
Grail-Quests-_retail_
Grail-Quests-_retail_-deDE
Grail-Quests-_retail_-enUS
Grail-Quests-_retail_-esES
Grail-Quests-_retail_-esMX
Grail-Quests-_retail_-frFR
Grail-Quests-_retail_-itIT
Grail-Quests-_retail_-koKR
Grail-Quests-_retail_-ptBR
Grail-Quests-_retail_-ruRU
Grail-Quests-_retail_-zhCN
Grail-Quests-_retail_-zhTW
Grail-Quests-ruRU
Grail-Quests-zhCN
Grail-Quests-zhTW
Grail-Reputations
Grail-Reputations-_classic_
Grail-Reputations-_retail_
Grail-Rewards
Grail-When
HandyNotes
HandyNotes_Achievements
HandyNotes_BattleForAzerothAchievments
HandyNotes_VisionsOfNZoth
LibSharedMedia-3.0
LoadIT
Loremaster
__MACOSX
MethodDungeonTools
MoveAnything
MythicDungeonTools
NeedToKnow
NPCScan
Omen
Pawn
Postal
Prat-3.0
Prat-3.0_Libraries
QuickMark
RaidAssist
Recount
Rematch
RepairBroker
SellJunk
Simulationcraft
WeakAuras
WeakAurasArchive
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates
ZPerl
ZPerl_ArcaneBar
ZPerl_CustomHighlight
ZPerl_Options
ZPerl_Party
ZPerl_PartyPet
ZPerl_Player
ZPerl_PlayerBuffs
ZPerl_PlayerPet
ZPerl_RaidAdmin
ZPerl_RaidFrames
ZPerl_RaidHelper
ZPerl_RaidMonitor
ZPerl_RaidPets
ZPerl_Target
ZPerl_TargetTarget

**Comment by Zenrage** [comment]
I am getting the same issue;

Constant refreshing pulls up different addons (not all) and then sometimes it doesnt pull up anything.  Something may have changed in the prepatch.

**Comment by casperstorm** [comment]
This is a CurseForge issue. The API is getting hammered which causes it to return the wrong responses.
