### ISSUE TITLE
Highlight addon row on catalog view

### ISSUE THREAD

**Issue by t03r1cht** [casperstorm/ajour#241]
**Is your feature request related to a problem? Please describe.**
I find it hard to keep track which row in the catalog row my cursor is currently positioned on. When I want to download the addon I need to cautiously move my cursor over to the Retail/Classic download button.

**Describe the solution you'd like**
Visual indication (e.g. changing the color) of the row which is currently focused or let me reorder the Catalog colums like in the My Addons view so I can directly put the Downloads column next to the Addon Name column.

**Comment by casperstorm** [comment]
This is a great idea, and something i've had in mind for sometime.
Problem is executing it with the current setup and ui framework we use.

I'll keep it ind mind, because UX wise it is needed.

**Comment by xPucTu4** [comment]
I just came here to post about this. On wide monitors the using maximized window is a bit challenging.

**Comment by casperstorm** [comment]
> Currently the header row supports cell highlight on mouse over. It should not be that hard to extend it down for each row.

Feel free to take a stab at it and send us a PR with your suggestion. It would indeed be a nice to have a good solution for this.
