### ISSUE TITLE
Details! Damage Meter is not showing up as installed

### ISSUE THREAD

**Issue by ManiacBunny** [casperstorm/ajour#242]
**Describe the bug**
The addon Details! Damage Meter is not showing up in my list of installed addons.

**Screenshots**
[Image of my addon list that does not show Details!](https://i.imgur.com/kFJBHIq.png)

[Image of my addon folder to show Details! is installed](https://i.imgur.com/czCHC3n.png)

[Image of the catalog tab saying Details! is not installed](https://i.imgur.com/pND8mg2.png)

**Software involved**
 - OS: Windows 10
 - Ajour version: 0.4.1
 - (if applicable) Addon name, flavor (classic or retail) and version: Details! Damage Meter (retail)

**Log Output**
See attached file
[ajour.log](https://github.com/casperstorm/ajour/files/5377436/ajour.log)

**Comment by casperstorm** [comment]
Related to #239.
API's are currently being hammered. More information in above issue.
