### ISSUE TITLE
Ajour panics and crashes at startup when no VRAM is available to allocate to.

### ISSUE THREAD

**Issue by kiraleos** [casperstorm/ajour#243]
**Describe the bug**
Ajour panics and crashes at startup when no VRAM is available to allocate to.

**To Reproduce**
1. Fill up VRAM either artificially or by opening up many GPU processes (e.g On my system with a 1050 2GB, just having Discord, Firefox and WoW open, the VRAM fills up).
2. Launch Ajour

**Expected behavior**
Ajour launches in software rendering mode, or another workaround.

**Software involved**
Please complete the following information:
 - OS: Arch Linux, Kernel 5.8.14
 - Ajour version: 0.4.1

**Log Output**
`
13:27:00.583 [ajour][INFO] Ajour 0.4.1 has started.
13:27:00.583 [ajour::gui][DEBUG] antialiasing: true
13:27:00.605 [ajour_core::config][DEBUG] loading config
13:27:00.605 [ajour_core::utility][DEBUG] checking for application update
13:27:00.605 [ajour_core::theme][DEBUG] loading user themes
13:27:00.606 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
13:27:00.727 [panic][ERROR] thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: AllocationError(OutOfMemory(Device))': /home/akis/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.6/src/device/mod.rs:324
   0: log_panics::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530:17
   2: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437:5
   3: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85:14
   4: core::option::expect_none_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:1269:5
   5: wgpu_core::device::Device<B>::create_buffer
   6: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_buffer_mapped
   7: wgpu_device_create_buffer_mapped
   8: wgpu::Device::create_buffer_mapped
   9: wgpu::Device::create_buffer_with_data
  10: wgpu_glyph::pipeline::Pipeline<()>::new
  11: iced_wgpu::backend::Backend::new
  12: <iced_wgpu::window::compositor::Compositor as iced_graphics::window::compositor::Compositor>::new
  13: ajour::gui::run
  14: ajour::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52:13
      std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348:40
      std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325:15
      std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394:14
      std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:51:25
  17: main
  18: __libc_start_main
  19: _start
`

**Comment by tarkah** [comment]
@kiraleos as a test, can you try to pass `--aa false` as a command line option for Ajour when launching and see if it still crashes when VRAM is full?

**Comment by kiraleos** [comment]
@tarkah The outcome is exactly the same with `--aa false`, logs are the same aswell. Sorry for the late reply.

**Comment by mlablah** [comment]
[ajour.log](https://github.com/casperstorm/ajour/files/5433076/ajour.log)
I'm attaching an example of the same error from a Windows user.

**Comment by tarkah** [comment]
@kiraleos can you try the opengl build and report if that works instead?

**Comment by kiraleos** [comment]
@tarkah The opengl build works. I confirmed it by runnning the normal build, it crashed, then the opengl build launched without a hiccup. The question is, should this issue be marked as closed?

**Comment by tarkah** [comment]
Awesome! Thanks for confirming. I think we are safe to. The opengl build is our compatability build and we are directing all users having issues launching Ajour to it, which is working for them
