### ISSUE TITLE
Support or suppress addon menu icon declarations in addon title

### ISSUE THREAD

**Issue by Seputaes** [casperstorm/ajour#246]
**Describe the bug**
Addons support special syntax in the `toc` file for stuff like colors (eg, ElvUI's title is `|cff1784d1ElvUI|r`). Ajour [already handles this](https://github.com/casperstorm/ajour/blob/6b4bc3aae8d8e344e7919379c175779f44b9f2f2/crates/core/src/parse.rs#L761). However, the new addon menu in WoW appears to also support icons now, and that syntax isn't handled by Ajour.

**To Reproduce**
1. Install an addon which utilizes the new icon syntax in the addon's `toc` file. (eg. All the Things v2.0.9)
2. Refresh the addons list in Ajour
3. Note the title of the addon.

**Expected behavior**
Either the icon syntax is suppressed for the title, or an icon is displayed in Ajour, as in the WoW Addon menu.

**Screenshots**
![Screenshot at 17-18-26](https://user-images.githubusercontent.com/441469/96058896-519f7580-0e41-11eb-8fbf-a24a93ff79e1.png)
![Screenshot at 17-26-08](https://user-images.githubusercontent.com/441469/96059287-5dd80280-0e42-11eb-8f7c-4e4636d6873b.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.4.1
 - (if applicable) Addon name, flavor (classic or retail) and version: All the Things 2.0.9, Retail

Example commit: https://github.com/DFortun81/AllTheThings/commit/18aeb73eb18151c523a73fe87ce9115f581d806a

**Additional context**
N/A

**Log Output**
N/A, no errors or records related to this.

**Comment by nickbayley** [comment]
To add to this.

![image](https://user-images.githubusercontent.com/2527831/96102661-ae953d00-0ece-11eb-8f2c-7bf0f62f8a86.png)

I don't see this problem when I have All The Things Classic installed in the classic interface folder.

![image](https://user-images.githubusercontent.com/2527831/96102938-ffa53100-0ece-11eb-8b48-6273f8cc8ac6.png)

Nor with All The Things Retail when in the retail interface folder. However I see the same when I stick ATT Classic in retail (I manually copied it there).

**Comment by casperstorm** [comment]
Thanks, i'll make sure to update our toc parser.
Normally showing the title from toc is a last resport, because we shows the API title instead. This could be related to the API being slammed (#239).
