### ISSUE TITLE
Catalog - add columns for version/game version

### ISSUE THREAD

**Issue by mattpson** [casperstorm/ajour#247]
Having columns that shows remote version and/or game version in the Catalog view would be very helpful to find out that the addon you want to install is supported by the game version that you are running. 

(Patch days is horrible)

**Comment by mlablah** [comment]
@mattpson thank you for the feature request. It's something we would like to add in the near future.

It has already been requested in #216 so I will close this issue. You can keep track on our progress using that other issue. :)
