### ISSUE TITLE
Pressing refresh shows a different number of installed addons (sometimes)

### ISSUE THREAD

**Issue by mattpson** [casperstorm/ajour#249]
**Describe the bug**
With Ajour started pressing "refresh" on the "My Addons" page sometimes misses quite a few addons. I have 22 addons installed currently but upon refreshing it reports 16, 11, 22, 22, 14 (5 refreshes).

**To Reproduce**
Press "refresh".  

**Expected behavior**
I expected all my addons to show every time.

**Software involved**
Ajour version 0.4.1 on MacOS Catalina (10.15.7).

**Log Output**

10:36:35.804 [ajour::gui::update][DEBUG] preparing to parse addons in "/Volumes/Pson disk 1/Applications/World of Warcraft/_retail_/Interface/AddOns"
10:36:35.804 [ajour::gui::update][DEBUG] preparing to parse addons in "/Volumes/Pson disk 1/Applications/World of Warcraft/_classic_/Interface/AddOns"
10:36:35.804 [ajour_core::parse][DEBUG] retail - parsing addons folder
10:36:35.804 [ajour_core::parse][DEBUG] classic - parsing addons folder
10:36:35.804 [ajour_core::parse][DEBUG] classic - 56 folders in AddOns directory to parse
10:36:35.804 [ajour_core::parse][DEBUG] retail - 89 folders in AddOns directory to parse
10:36:35.804 [ajour::gui::update][DEBUG] Message::LatestBackup(Some(2020-10-14T10:17:29))
10:36:35.805 [ajour_core::parse][DEBUG] classic - 56 fingerprints: 56 cached, 0 calculated, 0 added, 0 removed
10:36:35.808 [ajour_core::parse][DEBUG] classic - 56 successfully parsed from '.toc'
10:36:35.808 [ajour_core::parse][DEBUG] classic - 1 addons with tukui id
10:36:35.809 [ajour_core::parse][DEBUG] retail - 89 fingerprints: 89 cached, 0 calculated, 0 added, 0 removed
10:36:35.814 [ajour_core::parse][DEBUG] retail - 89 successfully parsed from '.toc'
10:36:35.814 [ajour_core::parse][DEBUG] retail - 2 addons with tukui id
10:36:36.372 [ajour_core::parse][DEBUG] classic - 1 addons applied with tukui id package metadata
10:36:36.372 [ajour_core::parse][DEBUG] classic - 55 unique fingerprints to check against curse api
10:36:36.584 [ajour_core::parse][TRACE] classic - partial fingerprint found:
	Curse ID: 3077307
	File Name: DBM-Core-1.13.60-98-g433abf7-classic
	Modules (Name - Local Fingerprint - Remote Fingerprint)
	DBM-Core - 25525757 - 4138207400
	DBM-GUI - 742080737 - 742080737
	DBM-Party-Classic - 1921621243 - 1921621243
	DBM-AQ20 - 2401073170 - 2401073170
	DBM-AQ40 - 2179362801 - 2179362801
	DBM-Azeroth - 1957678194 - 1957678194
	DBM-BWL - 2688678686 - 2688678686
	DBM-MC - 2952444568 - 2952444568
	DBM-Onyxia - 4178088498 - 4178088498
	DBM-Naxx - 2401891874 - 2401891874
	DBM-ZG - 973105483 - 973105483
	DBM-DefaultSkin - 1158327563 - 1158327563
	DBM-StatusBarTimers - 2323637428 - 2323637428
10:36:36.584 [ajour_core::parse][TRACE] classic - partial fingerprint found:
	Curse ID: 3062310
	File Name: TBO ADDON PACK
	Modules (Name - Local Fingerprint - Remote Fingerprint)
	DBM-AQ20 - 2401073170 - 3399317793
	DBM-AQ40 - 2179362801 - 548268224
	DBM-Azeroth - 1957678194 - 3513896587
	DBM-BWL - 2688678686 - 3436812693
	DBM-Core - 25525757 - 1068657324
	DBM-GUI - 742080737 - 3049076417
	DBM-MC - 2952444568 - 1044964614
	DBM-Naxx - 2401891874 - 735218219
	DBM-Onyxia - 4178088498 - 3185024549
	DBM-Party-Classic - 1921621243 - 3388570709
	DBM-ZG - 973105483 - 522798315
	ClassicLootAssistant - 0 - 4141794195
	DBM-DefaultSkin - 1158327563 - 1158327563
	DBM-StatusBarTimers - 2323637428 - 2323637428
	NauticusClassic - 0 - 1344655960
	NovaWorldBuffs - 651479183 - 790465760
	RCLootCouncil_Classic - 1546880498 - 1546880498
	ThreatClassic2 - 4070329451 - 4070329451
10:36:36.584 [ajour_core::parse][TRACE] classic - partial fingerprint found:
	Curse ID: 2999196
	File Name: Prat-3.0-3.8.26-1-g5e7950a-classic
	Modules (Name - Local Fingerprint - Remote Fingerprint)
	Prat-3.0_Libraries - 4133380122 - 4133380122
	Prat-3.0 - 432406224 - 3036566319
10:36:36.584 [ajour_core::parse][DEBUG] classic - 21 exact fingerprint matches against curse api
10:36:36.584 [ajour_core::parse][DEBUG] classic - 21 addons applied with fingerprint metadata
10:36:36.584 [ajour_core::parse][DEBUG] classic - 21 addons with curse id
10:36:36.833 [ajour_core::parse][DEBUG] classic - 20 addons applied with curse id package metadata
10:36:36.833 [ajour_core::parse][DEBUG] classic - 22 addons successfully parsed
10:36:36.833 [ajour::gui::update][DEBUG] Message::ParsedAddons(classic, 22 addons)
10:36:36.922 [ajour_core::parse][DEBUG] retail - 2 addons applied with tukui id package metadata
10:36:36.922 [ajour_core::parse][DEBUG] retail - 87 unique fingerprints to check against curse api
10:36:37.196 [ajour_core::parse][DEBUG] retail - 20 exact fingerprint matches against curse api
10:36:37.196 [ajour_core::parse][DEBUG] retail - 20 addons applied with fingerprint metadata
10:36:37.196 [ajour_core::parse][DEBUG] retail - 20 addons with curse id
10:36:37.506 [ajour_core::parse][DEBUG] retail - 20 addons applied with curse id package metadata
10:36:37.506 [ajour_core::parse][DEBUG] retail - 22 addons successfully parsed
10:36:37.506 [ajour::gui::update][DEBUG] Message::ParsedAddons(retail, 22 addons)

10:36:39.063 [ajour::gui::update][DEBUG] preparing to parse addons in "/Volumes/Pson disk 1/Applications/World of Warcraft/_retail_/Interface/AddOns"
10:36:39.063 [ajour::gui::update][DEBUG] preparing to parse addons in "/Volumes/Pson disk 1/Applications/World of Warcraft/_classic_/Interface/AddOns"
10:36:39.063 [ajour_core::parse][DEBUG] retail - parsing addons folder
10:36:39.063 [ajour_core::parse][DEBUG] classic - parsing addons folder
10:36:39.064 [ajour_core::parse][DEBUG] classic - 56 folders in AddOns directory to parse
10:36:39.064 [ajour::gui::update][DEBUG] Message::LatestBackup(Some(2020-10-14T10:17:29))
10:36:39.064 [ajour_core::parse][DEBUG] retail - 89 folders in AddOns directory to parse
10:36:39.065 [ajour_core::parse][DEBUG] classic - 56 fingerprints: 56 cached, 0 calculated, 0 added, 0 removed
10:36:39.068 [ajour_core::parse][DEBUG] classic - 56 successfully parsed from '.toc'
10:36:39.068 [ajour_core::parse][DEBUG] classic - 1 addons with tukui id
10:36:39.068 [ajour_core::parse][DEBUG] retail - 89 fingerprints: 89 cached, 0 calculated, 0 added, 0 removed
10:36:39.073 [ajour_core::parse][DEBUG] retail - 89 successfully parsed from '.toc'
10:36:39.073 [ajour_core::parse][DEBUG] retail - 2 addons with tukui id
10:36:39.627 [ajour_core::parse][DEBUG] classic - 1 addons applied with tukui id package metadata
10:36:39.627 [ajour_core::parse][DEBUG] classic - 55 unique fingerprints to check against curse api
10:36:39.821 [ajour_core::parse][TRACE] classic - partial fingerprint found:
	Curse ID: 3077307
	File Name: DBM-Core-1.13.60-98-g433abf7-classic
	Modules (Name - Local Fingerprint - Remote Fingerprint)
	DBM-Core - 25525757 - 4138207400
	DBM-GUI - 742080737 - 742080737
	DBM-Party-Classic - 1921621243 - 1921621243
	DBM-AQ20 - 2401073170 - 2401073170
	DBM-AQ40 - 2179362801 - 2179362801
	DBM-Azeroth - 1957678194 - 1957678194
	DBM-BWL - 2688678686 - 2688678686
	DBM-MC - 2952444568 - 2952444568
	DBM-Onyxia - 4178088498 - 4178088498
	DBM-Naxx - 2401891874 - 2401891874
	DBM-ZG - 973105483 - 973105483
	DBM-DefaultSkin - 1158327563 - 1158327563
	DBM-StatusBarTimers - 2323637428 - 2323637428
10:36:39.821 [ajour_core::parse][DEBUG] classic - 17 exact fingerprint matches against curse api
10:36:39.821 [ajour_core::parse][DEBUG] classic - 17 addons applied with fingerprint metadata
10:36:39.821 [ajour_core::parse][DEBUG] classic - 17 addons with curse id
10:36:40.049 [ajour_core::parse][DEBUG] classic - 16 addons applied with curse id package metadata
10:36:40.050 [ajour_core::parse][DEBUG] classic - 18 addons successfully parsed
10:36:40.050 [ajour::gui::update][DEBUG] Message::ParsedAddons(classic, 18 addons)
10:36:40.177 [ajour_core::parse][DEBUG] retail - 2 addons applied with tukui id package metadata
10:36:40.177 [ajour_core::parse][DEBUG] retail - 87 unique fingerprints to check against curse api
10:36:40.560 [ajour_core::parse][DEBUG] retail - 12 exact fingerprint matches against curse api
10:36:40.560 [ajour_core::parse][DEBUG] retail - 12 addons applied with fingerprint metadata
10:36:40.560 [ajour_core::parse][DEBUG] retail - 12 addons with curse id
10:36:40.772 [ajour_core::parse][DEBUG] retail - 12 addons applied with curse id package metadata
10:36:40.772 [ajour_core::parse][DEBUG] retail - 14 addons successfully parsed
10:36:40.772 [ajour::gui::update][DEBUG] Message::ParsedAddons(retail, 14 addons)

**Comment by Ruffz** [comment]
It's, I think, a Curse API bug which occurs also on Twitch client
May be due to the quantity of updates it receive

**Comment by casperstorm** [comment]
This is caused by the API being slammed, and it has been for the last day.
I'll close in favor for: https://github.com/casperstorm/ajour/issues/239
