### ISSUE TITLE
Sometimes the version of GTFO is wrong

### ISSUE THREAD

**Issue by mattpson** [casperstorm/ajour#251]
**Describe the bug**
Upon my testing with #249 sometimes Ajour reports the wrong version of GTFO addon. Most of the times it reports 4.56 which is the one installed but for some reason it sometimes says that r524-alpha is installed locally.

**To Reproduce**
Refresh

**Expected behavior**
I expected it to be the same version reported upon refreshing the list-

**Screenshots**
![Screenshot 2020-10-15 at 11 10 51](https://user-images.githubusercontent.com/15263602/96103647-43e8ff00-0ed8-11eb-8389-0dce3dd2267b.png)

**Software involved**
Ajour 0.4.1 on MacOS catalina (10.15.7)

**Additional context**
The .toc file for GTFO is stating the correct version:

```
## Interface: 80300
## Title: GTFO
## Notes: GTFO, you're dying!
## Author: Zensunim of Dragonblight/Myzrael
## Version: 4.56
## DefaultState: Enabled
## SavedVariables: GTFOData
```

(I removed the rest of the lines containing the files)

**Comment by nickbayley** [comment]
![image](https://user-images.githubusercontent.com/2527831/96104094-519a8680-0ed0-11eb-81f1-c6b9e0d3cf72.png)

I see something similar with `AdiBags - Zone Items`. Although local and remote are the same in my case. Also seeing the same as you describe in #249.

**Comment by mattpson** [comment]
Got it with DBM-TimelessIsle.

![Screenshot 2020-10-15 at 11 42 59](https://user-images.githubusercontent.com/15263602/96110080-a98cb980-0edf-11eb-9842-9eabbb7c1634.png)

**Comment by casperstorm** [comment]
#239.
