### ISSUE TITLE
AppImage fails to run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [casperstorm/ajour#262]
Please build on a system no newer than Ubuntu xenial so that it can run on all still-supported distribution releases.

```
AppRun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9210/AppRun)
```

Reference and detailed test error log:
https://github.com/AppImage/appimage.github.io/pull/2368

**Comment by mlablah** [comment]
@probonopd Thank you for raising this issue and pointing out a solution. I have now updated our workflow to use Ubuntu 16.04 for our AppImage builds going forward. Future releases will use that. Closing the issue.
