### ISSUE TITLE
addons sharedmedia & gladiatorlossa2 update state

### ISSUE THREAD

**Issue by sod** [casperstorm/ajour#263]
**Describe the bug**
Not really a bug. More ill behaved addons I guess?

**To Reproduce**
Install these two addons:
* https://www.curseforge.com/wow/addons/sharedmedia (stable)
* https://www.curseforge.com/wow/addons/gladiatorlossa2 (stable)

Every time I hit "Refresh" there is another result. It sometimes reports none as updated, sometimes one of them, sometimes both:

![image](https://user-images.githubusercontent.com/905328/96359604-16d56000-1115-11eb-97d4-c90c99fb775e.png)

In case of sharedmedia I guess the issue may be, that the toc file in the download `3.1.0 - r192` reads `## Version: 3.1.0-191`?
Gladiatorlossa2, I have no idea though.

**Software involved**
 - OS: "Windows 10"
 - Ajour version: 0.4.1

**Log Output**
https://gist.github.com/sod/da99ebc561278fd7d53f0dc03448cb88

**Comment by sod** [comment]
The twitch client has exactly the same issue with those two addons. So maybe it's an curseforge api issue.

**Comment by casperstorm** [comment]
It is a CurseForge API issue. It has been going on since pre-patch hit.

There's not really anything I can do other than wait it out. Sucks.

Thanks for reporting though.
