### ISSUE TITLE
Link to the Website and/or Github Project in the Settings menu

### ISSUE THREAD

**Issue by leon-paul-hart** [casperstorm/ajour#267]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a link to the website and/or the Github repository somewhere in the application for quick access.

**Describe the solution you'd like**
Possibly in the Settings menu or a separate "About" section there could be a link with some text telling users where to download latest version and/or how to participate in the project, on the off chance that the download update option breaks or didn't work. Sometimes I might want to go to the project site to check the latest development information out regardless of if there is a new version available or not.

Could also maybe make the version number in the app a link to the Github repository version notes?

**Describe alternatives you've considered**
Could just continue to google the project or bookmark the website and go through the home page links but I'm a developer myself, I love a great app User Experience :P Unfortunately I don't know Rust yet...

**Additional context**

**Comment by Ruffz** [comment]
That was added in Ajour 0.3.4 (If I correctly understood your request), just click an addon name to expand options, which include direct link to the addon's website.
