### ISSUE TITLE
Backup handling for release channels

### ISSUE THREAD

**Issue by Neralus** [casperstorm/ajour#270]
**Is your feature request related to a problem? Please describe.**
Ajour settings allows only to get the latest version from the selected channel. Some addon developers do not use alpha or beta channels which mean ajour would never show an update is available, even though it is on a higher channel.

**Describe the solution you'd like**
There should be a fallback mechanic to check for updates. e.g. if alpha is selected and there are no alpha version, check for beta version instead, if no beta versions check for stable ones.

**Additional context**
This simple mechanic would not work for irregularly updated addons, e.g. higher version being pushed directly to stable and not to beta/alpha but this may be a bit more complex in regards to detection.

**Comment by casperstorm** [comment]
There is a fallback logic in place. Currently the logic works as following:
* If you select `Stable` you will always get latest `Stable`.
* If you select `Beta` you will get latest `Beta` unless `Stable` is newer.
* If you select `Alpha` you will get latest `Alpha` unless `Beta`/`Stable` is newer.

Isn't this what you mean?

**Comment by Neralus** [comment]
In general yes but it didn't seem to work for addons where a channel is completely unused,
e.g. the Addon Plexus, it has beta version but no alphas.

If i set the channel to alpha and refresh or restart ajour, it will show that there is no update.
If i switch to beta channel then it shows me there is an update available.

This behavior lead me to think there is no fallback logic in place and it only uses the selected channel, but it seems there may just be an issue with channels that have no version at all.

**Comment by casperstorm** [comment]
So thats an edge-case.
I'll fix that.
