### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by s-e-p** [casperstorm/ajour#272]
Starting program (ajour.exe) gives window with light gray bar across top; hovering mouse over right corner in bar shows pale purple button, no text.  Clicking brings up several outlines of controls or something, still no text.  Clicking again goes back to just the gray bar.  I suppose I could try building from source and debugging, but figured I'd see if this is a known problem.

Running the ajour-opengl.exe version seems to work.

Windows 10 Pro, build 19041.508

06:06:52.104 [ajour][INFO] Ajour 0.4.1 has started.
06:06:52.105 [ajour::gui][DEBUG] antialiasing: true
06:06:52.114 [ajour_core::config][DEBUG] loading config
06:06:52.114 [ajour_core::utility][DEBUG] checking for application update
06:06:52.114 [ajour_core::theme][DEBUG] loading user themes
06:06:52.115 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
06:06:52.494 [ajour::gui::update][DEBUG] Message::Parse
06:06:52.494 [ajour::gui::update][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: None,
        flavor: Retail,
    },
    addons: Addons {
        ignored: {},
        release_channels: {},
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: None,
    scale: None,
    backup_directory: None,
}
06:06:52.494 [ajour::gui::update][DEBUG] addon directory is not set, showing welcome screen
06:06:52.494 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
06:06:52.494 [ajour::gui::update][DEBUG] Message::NeedsUpdate(None)
06:06:54.236 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(8654 addons in catalog)
06:06:58.963 [ajour::gui::update][DEBUG] Interaction::Settings
06:07:10.931 [ajour::gui::update][DEBUG] Interaction::Settings

**Comment by casperstorm** [comment]
Can you try [OpenGL](https://github.com/casperstorm/ajour/releases/download/0.4.1/ajour-opengl.exe) version of Ajour? Is it same behaviour?

**Comment by s-e-p** [comment]
Ah, updated my report at same time you asked.  Yes, opengl version works.

**Comment by casperstorm** [comment]
Awesome the OpenGL version works then.
The "normal" build has a pretty high requirement of DX12 or Vulkan on Windows so it might be the reason you can't properly run it.
