### ISSUE TITLE
support add third party source

### ISSUE THREAD

**Issue by qyh214** [casperstorm/ajour#273]
**Is your feature request related to a problem? Please describe.**
Want to support adding third party sources by yourself.

**Describe the solution you'd like**
some addons is on github/gitlab/or other git repository.for example https://github.com/siweia/NDui.

we can add them as source to update addons.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by casperstorm** [comment]
We have had a few suggesting this feature so i've added it to our inbox in the [Roadmap](https://github.com/casperstorm/ajour/projects/2#card-47742628).

I'll close this issue for now, and then you can follow along on the Roadmap. Thanks.
