### ISSUE TITLE
Ajour not identifying all installed addons

### ISSUE THREAD

**Issue by Walkerbo** [casperstorm/ajour#275]
_**Describe the bug**_
The Ajour app does not identify all of my installed addons.
https://www.curseforge.com/wow/addons/collect_me
https://www.curseforge.com/wow/addons/gnosis
https://www.curseforge.com/wow/addons/hidetalkinghead
https://www.curseforge.com/wow/addons/larger-macro-icon-selection

All of these addons are housed on Curse

_**To Reproduce**_
Install these addons then hit refresh

_**Expected behavior**_

_**Screenshots**_
<img width="1249" alt="Screenshot 2020-10-21 120329" src="https://user-images.githubusercontent.com/35990554/96661446-cc174a80-1397-11eb-8493-74580630944d.png">

_**Software involved**_
Windows 10 64bit

_**Log Output**_
[ajour.log](https://github.com/casperstorm/ajour/files/5412633/ajour.log)

**Comment by casperstorm** [comment]
CurseForge API is not working correctly so Ajour gets wrong data from time to time. 

More in #239.
