### ISSUE TITLE
Barrels o' Easy always shown as needing Update

### ISSUE THREAD

**Issue by vttale** [casperstorm/ajour#277]
**Describe the bug**
The Barrels o' Easy addon always shows as needing an update, even immediately after updating. 

Honestly I don't even care about this particular addon, but thought it probably pointed to an issue that could end up affecting other addons.

**To Reproduce**
1. Select Retail addons, then Refresh
2. Barrels o' Easy is shown as Local: BarrelsOEasy- and Remote: BarrelsOEasy (visually the same, if not strictly so).
3. Click Update under status, changes to Downloading then Completed.
3. Refresh again, Status changes back to Update

**Expected behavior**
Updating the addon should not show it as needing updates until there is a new update available.

**Software involved**
Please complete the following information:
 - Windows 10
 - Ajour 0.4.2.
 - Barrels o' Easy, Retail

**Additional context**
I was on 0.4.1 but 0.4.2 just came out and I tried that.  The problem remains, and seems to be worse now.  There are now several addons telling me that I need to Update or Repair immediately after performing that action, and all with the same Local and Remote version strings. 

**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.
I will followup with a comment on this, since I am writing this report on a different computer than the one where Ajour is running.    I can say that the messages from UpdateFingerprint are pretty sus, because they partially (though not entirely) overlap with items that claim they need repair.

**Comment by casperstorm** [comment]
Should be fixed in #280 :)
