### ISSUE TITLE
Support modified addons

### ISSUE THREAD

**Issue by Walkerbo** [casperstorm/ajour#279]
**_**Describe the solution you'd like**_**
When I have to edit a lua file to get it working again, 90001 broke so many addons that community users provided fixes before the author provided an updated version.
Any edited addons disappear from the list of installed addons, and the only way to bring them back is to reinstall which then breaks it again.

**_**Describe alternatives you've considered**_**
If the addon is installed but edited if it could still be displayed as installed, we can then place it on ignore.

**_**Additional context**_**
It would also be helpful if we could see which repository the addon is hosted by, such as curse, wowinterface, github, and in cases where that addon is managed on multiple repositories can we select the prefered repository.

**Comment by casperstorm** [comment]
If you are on Windows then you can try this build and confirm if it works: [ajour-rc2.zip](https://github.com/casperstorm/ajour/files/5426036/ajour-rc2.zip)
Should detect your modified addons as unknowns.

**Comment by casperstorm** [comment]
Out now in 0.4.4.

**Comment by Walkerbo** [comment]
Thanks for that; it is working
