### ISSUE TITLE
Addons without versions in toc files

### ISSUE THREAD

**Issue by casperstorm** [casperstorm/ajour#28]
So right now we dependent on addons having a `## Version: x.x.x` in their .toc file. And example from BigWigs:

```
## Interface: 80300
## Title: BigWigs
## Notes: Modular, lightweight, non-intrusive approach to boss encounter warnings.
## Version: v184.4
```
However a few addons does not have any version, meaning they won't appear in Ajour. An example is Details!:

```
## Interface: 80300
## Title: Details! Damage Meter
## Notes: Essential tool to impress that chick in your raid.
## SavedVariables: _detalhes_global
## SavedVariablesPerCharacter: _detalhes_database
## OptionalDeps: Ace3, LibSharedMedia-3.0, LibWindow-1.1, LibDBIcon-1.0, NickTag-1.0, LibDataBroker-1.1, LibItemUpgradeInfo-1.0, LibGroupInSpecT-1.1, LibCompress, LibGraph-2.0
#@no-lib-strip@
Libs\libs.xml
#@end-no-lib-strip@
```

However, while investigating this specific issue I found that Details! actually has it's [version written in one of its library toc files](https://github.com/Tercioo/Details-Damage-Meter/blob/master/Libs/LibTranslit/LibTranslit-1.0.toc#L7). So we could make some logic were we handle speciale cases like this, with a proper failure plan if something goes on.

**Comment by mlablah** [comment]
Adding notes from our discussion to the issue:
Some addons have a CHANGES.txt file. The last string in the first line of that file contains a tag for the release. This seems to match the version of the addon in the curse api. So conceivably it could be used as a fallback "local version" in case the toc file doesn't contain a "## Version:" line.

Out of 5 addons that are missing version in toc, 2 have it in a CHANGES.txt. So this would at most be a partial fix.

These have it:
Details!
World Quest Tracker

These do not:
AngryKeystones
Kui Nameplates
Nameplate Cooldowns

**Comment by WeaponMan** [comment]
One could guess the version from the url of downloaded addon and add that to the toc or seperate file/database and when there is no version in toc/seperate record to get the version just offer update to the user.

**Comment by casperstorm** [comment]
> One could guess the version from the url of downloaded addon and add that to the toc or seperate file/database and when there is no version in toc/seperate record to get the version just offer update to the user.

1. We start by parsing the addons from disk, and then we talk to the repositories to check for new versions. If we have no local version, we dont know when a specific addon is updatable or not.
2. If we edit the toc file, we also edit what Wow sees. I would like to avoid changing "the truth" which is the toc files.
3. If we show addons without versions in Ajour we will see a lot of "sub-addons". Many addons comes with 3, 4, ... n additional folders which we try to hide with logic.
Currently the logic to detect a "parent" addon looks like this:
https://github.com/casperstorm/ajour/blob/7afa05953c7c7536e638b405f333e4398b74e432/src/addon.rs#L154-L172

**Comment by casperstorm** [comment]
I'll close this down for now. The decision we have taken is that an addon is required to have a version specified in the toc file. Does the addon not have this, Ajour will not show it.

I would recommend people to take a look at the [wiki](https://github.com/casperstorm/ajour/wiki/Addons-with-known-issues) where we have collected a list of addons with known issues.
