### ISSUE TITLE
Self Updater

### ISSUE THREAD

**Issue by emin** [casperstorm/ajour#283]
Hi,

The self-update feature is a must, it's even a little weird that the updater program can't update itself :) I know it's a little different than what it does, it's architectural change maybe or separate updater program in it to update itself. But overall it seems it's a required feature, other than that I love the simplicity of the program.

**Comment by casperstorm** [comment]
I agree it is needed, and as you can see from the [Roadmap](https://github.com/casperstorm/ajour/projects/2#card-46568938) the feature is in progress, and has been for some time.
