### ISSUE TITLE
Some addons say Unknown

### ISSUE THREAD

**Issue by jwilliam87** [casperstorm/ajour#289]
Attached file to show the issue.

![aaa](https://user-images.githubusercontent.com/65428974/96910713-e15ea880-146d-11eb-81d6-9355b8d79b6d.jpg)

**Comment by casperstorm** [comment]
Give this a go and let me know how it looks: [Uploading ajour-rc2.zip…]()

**Comment by dstaley** [comment]
@casperstorm Having the same issue with rc2, only with one addon though:

![image](https://user-images.githubusercontent.com/88163/96947937-4c71a480-1499-11eb-9993-e6c5180be1e9.png)

I installed it fresh from Twitch just to make sure there weren't any modifications.

**Comment by tsposato** [comment]
I have a similar issue with 0.4.4 for some of my addons.
![image](https://user-images.githubusercontent.com/27261670/97017544-c8ebac80-1599-11eb-83b6-048bbc7a01e6.png)

**Comment by casperstorm** [comment]
It happens if our API does not know the addon/version. You can try deleting the addon an reinstall from the catalog to see if that fixes it.

Another reason could be they are locally modified.

**Comment by dstaley** [comment]
Deleting and reinstalling Combuctor from Ajour results in the same error. Interestingly, when I download it from Ajour it gets stuck on the "Hashing" status. I'm not sure if that's related, but I figured I'd mention it.

**Comment by casperstorm** [comment]
> Deleting and reinstalling Combuctor from Ajour results in the same error. Interestingly, when I download it from Ajour it gets stuck on the "Hashing" status. I'm not sure if that's related, but I figured I'd mention it.

Aha, strange. I'll look into it. 
Thanks for reporting.

**Comment by tsposato** [comment]
> It happens if our API does not know the addon/version. You can try deleting the addon an reinstall from the catalog to see if that fixes it.
> 
> Another reason could be they are locally modified.

Interesting I'll try, I thought because it was reading the Local version and Author in most cases that it at least knew about the addon just not how to update it.

**Comment by casperstorm** [comment]
This will be fixed in #315.
