### ISSUE TITLE
Ajour MacOS developer cannot be verified

### ISSUE THREAD

**Issue by lukzmu** [casperstorm/ajour#293]
**Describe the bug**
Downloading a new version of Ajour always throws errors about malware, as the developer cannot be verified.

**To Reproduce**
1. Download new version of Ajour
2. Open Ajour

**Expected behavior**
Should run without problems

**Screenshots**
![Ajour](https://i.imgur.com/3lHVMb7.png)

**Software involved**
Please complete the following information:
 - OS: MacOS Catalina 
 - Ajour version: Any

**Comment by casperstorm** [comment]
I have no signed it. I wrote down the solution in the [faq](https://github.com/casperstorm/ajour#faq).

> Instead of double clicking it, right click and choose "Open". That should successfully open Ajour.
