### ISSUE TITLE
Addon not showing update available

### ISSUE THREAD

**Issue by KestrelWild** [casperstorm/ajour#302]
Still seeing instances where the update status of addons on Ajour doesn't match what Curse sees. Curse has a beta2 file update available for this addon. Ajour doesn't see it.

![2020-10-25 14_13_23-Twitch](https://user-images.githubusercontent.com/10617817/97115409-f4bb7f00-16cc-11eb-9ddc-8411223270f2.png)

**Comment by casperstorm** [comment]
That is because that update is 38 min old, from writing this post. And it was 15 min old when you wrote it.
Ajour well refresh from Curse every 3 hours, so at max you will have to wait that.

**Comment by KestrelWild** [comment]
OO my bad! I didn't realize there was a refresh timer. Makes sense. Sorry and thanks :)
