### ISSUE TITLE
Install addon from github repo

### ISSUE THREAD

**Issue by joukevandermaas** [casperstorm/ajour#306]
**Is your feature request related to a problem? Please describe.**
Sometimes addons stop being maintained by the original author, and people fork the repo and make fixes. It would be nice if we can install addons from these github repos and have Ajour manage them.

**Describe the solution you'd like**
Users click a button, then enter a URL to a git repo. Ajour clones the repo into the appropriate directory, and when there are new commits, pulls the repo to update the addon. 

I would be fine if this required people to have git installed on their computer first (for Windows).

**Describe alternatives you've considered**
Alternatively it could use the github API to download the source instead. This approach means that the user doesn't need to have git installed and Ajour doesn't have to use git apis. The advantage of using git is that it would work for *any* git repo, not just Github ones.

**Additional context**
This was prompted by [DialogKey](https://github.com/TonyRaccoon/wow-dialogkey) which hasn't been updated in a year. Fixes have been made in [other repos](https://github.com/Kayakflo/wow-dialogkey) but I do not want to manually install these if I don't have to.

In general, I worry that the wow addon system is too centrally managed and being able to install from a git clone would decentralize it.

**Comment by casperstorm** [comment]
I would like to add this feature, @joukevandermaas.
There is, however, a few things we want to get done first but meanwhile I'll try to think of an elegant way we can integrate this. 

Can't promise you a ETA for now.

**Comment by joukevandermaas** [comment]
Sounds great, if you think it is valuable that is enough for me 😄 I understand it may not be the easiest feature. Let me know if there is anything I can do to help (I do not know Rust, so I cannot implement it myself, sadly).
