### ISSUE TITLE
missing field `tag_name` error message on startup

### ISSUE THREAD

**Issue by slabstone** [casperstorm/ajour#311]
**Describe the bug**
Error message on startup: `missing field tag_name at line 1 column 248`
The message disappears after addon list is loaded, does not appear on refresh.

**To Reproduce**
1. Run `ajour.exe`

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/4430708/97216064-53b8eb00-17d6-11eb-9c71-3885b5ee5953.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10 2004
 - Ajour version: 0.4.4

**Log Output**
https://pastebin.com/6mt0EmiT

**Comment by casperstorm** [comment]
Do you by any chance use Pihole or anything else that block access to certain sites? I am asking because what seems to fail there is this call: https://api.github.com/repos/casperstorm/ajour/releases/latest

**Comment by slabstone** [comment]
I'm not using Pihole, I have no problem accessing this URL.

**Comment by slabstone** [comment]
Seems to be fine now, maybe some temporary problem between me and GitHub.

**Comment by tarkah** [comment]
@slabstone I'm going to leave this open, as we shouldn't let anything fail when that request fails. It's not really mission critical checking for an update to the application, so it should just silently fail and not hold anything else up

**Comment by tarkah** [comment]
Closing, after investigating, this error won't appear anymore on development branch due to changes from the self update feature. We should be good here.
