### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by nerzhul** [casperstorm/ajour#314]
**Is your feature request related to a problem? Please describe.**
On twitch app (RIP), we can see (quite ugly) changelog on some mods. It's anoying to don't have this here, i like to know what modders improved :)

**Describe the solution you'd like**

Can you add some changelog for mods, i don't know how you can fetch it, but for some you may obtain it from the current API or if it's some git sources, maybe get the latest release tag.

**Describe alternatives you've considered**

A first step may be, if you have a repository, a link to the repository releases page ?

**Additional context**
N/A

**Comment by casperstorm** [comment]
Hi @nerzhul,
Ajour has support for changelogs! If you press the version number in `Local` or `Remote` you will be able to see it. I have attatched a little gif to show it. It's a hidden gem.

A little note on the text: often its a mix between markdown and html which im trying to clean up with some simple regex replaces patterns so it will never be super perfect, but i feel it gets the jobs done. 

Let me know what you think.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2248455/97277388-b642d300-1838-11eb-9ff0-ebfee3e0ad84.gif)

**Comment by nerzhul** [comment]
oh yeah sorry, i didn't saw that, very very nice, thanks

**Comment by casperstorm** [comment]
> oh yeah sorry, i didn't saw that, very very nice, thanks

No worries! It is quite hidden but also something only few people are using so I think it make sense. My reason for placing it on the versions was that it then made sense what changelog you were looking at.
