### ISSUE TITLE
Don't Delete Authors' Working Copies

### ISSUE THREAD

**Issue by Hekili** [casperstorm/ajour#316]
**Is your feature request related to a problem? Please describe.**

Ajour recognizes my "working copy" folder of my addon and wants to update it.  The update process involves deleting everything, redownloading, and replacing what was there.  When this happens, any of my .gitignored notes get deleted and are unrecoverable via the Recycle Bin.

**Describe the solution you'd like**

Ajour could recognize an active git repository in a folder and opt not to replace it, add a layer of confirmation, or treat it as an invalid version of the addon and ignore it.

**Describe alternatives you've considered**

Not clicking Update All unless I want to have another very bad day.

**Additional context**

N/A

**Comment by casperstorm** [comment]
Hi @Hekili,

Sorry you had this experience with Ajour.
We actually have an ignore feature which you can use going forward. You can ignore an addon by pressing the title and then the button is in the lower right side of the details view.

An ignored addon won't be updated through `Update all`.

I was thinking that we could look into adding some logic which would pre-ignore certain addons, for example addons which is a git repository. However that would require us to [run a git command](https://gist.github.com/brettinternet/0d2225ffb6b224c515643f630a65b463) in each folder and that feels a little invasive. It would also mean that we would need git available on the host.

Also, now that I have the opportunity: Thank you for your addon Hekili. It's awesome.

**Comment by Hekili** [comment]
Makes sense.  Not sure how I overlooked the Ignore button, but it has now been clicked.  Thanks.

I can understand the hesitation to run a git command.  Thanks for the quick response.  Take care!

**Comment by tarkah** [comment]
@Hekili To chime in on this, Ajour doesn't overwrite folders that are symlinked, it will first break the link then create the new folder. So if you want some extra protection, put your folder behind a symlink. See #255 for context to this.

**Comment by Hekili** [comment]
Ah, that explains why my Retail folder was safe (symlinked) but I got caught by a Beta update (target of symlink).

I'll move to a new location and symlink both that way.  Thanks for the note.

**Comment by Caerdon** [comment]
@casperstorm - what if you just checked for the existence of a .git folder?  No git command needed in that case.

**Comment by Caerdon** [comment]
Symlinks have been problematic because the Mac WoW client, at least, was deleting them constantly.

**Comment by ascott18** [comment]
@casperstorm any thoughts on @Caerdon's suggestion of just checking for a `.git` folder? I believe this is what the old Curse Client/Twitch Client did to detect developer copies of addons.

With 4+ different WoW installs (retail, retail PTR, classic, TBC beta) for a person who has 10+ addons, this would be really, really nice to have.

**Comment by casperstorm** [comment]
> @casperstorm any thoughts on @Caerdon's suggestion of just checking for a `.git` folder? I believe this is what the old Curse Client/Twitch Client did to detect developer copies of addons.
> 
> With 4+ different WoW installs (retail, retail PTR, classic, TBC beta) for a person who has 10+ addons, this would be really, really nice to have.

That could work, @ascott18. Will put it on my todo list and take a look at it later.
