### ISSUE TITLE
State stuck on "Hashing" when installing existing addon

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#325]
**Describe the bug**
I am using Ajour 0.5.0 from the Development branch.

If an addon is already installed but either:
a) unrecognized or 
b) recognized as a curse or tukui addon

And the user then installs it from catalog to:
a) "fix" it being unrecognized or
b) switch from using one source to the other for that addon.

Then the status of the installation gets stuck on "Hashing", and there are two entries in the "My Addons" list. The old one with status "Completed", and a new one with status "Hashing".

If the addon was previously installed from tukui, the cache entry in addons.yml does not get removed.

After refreshing the list of addons, the duplicate entry is removed, but the source will be listed as "TukUI" due to entry in addons.yml.

**To Reproduce**
1. Prerequisite: Install addon that is available at both sources from either one of them. E.g. AddonSkins from TukUI. 
2. Go to catalog and install the addon from the other source (curse).
3. Observe that the status gets stuck on "Hashing" and there are now 2 entries in the My Addons list.
4. After refreshing there is only 1 entry but it is recognized as a TukUI addon despite being installed from curse due to leftover cache entry in addons.yml.

OR

1. Prerequisite: have an unrecognized addon in the list (I used Atlas with a modified toc file to break fingerprint match).
2. Go to catalog and install the addon from curse.
3. Observe that the status gets stuck on "Hashing" and there are now 2 entries in the My Addons list.
4. After refreshing there is only 1 entry and it is correctly sourced to Curse due to lack of leftover cache entry in addons.yml.

**Expected behavior**
Two options come to mind:
1) (Preferred option) Completely replace the existing folders that are unrecognized or matched to another source and end up with a single new entry that has state "Completed" in the "My Addons" list without having to refresh and matched to correct source.

2) Be told that the addon could not be installed due to folders conflict. Tell the user which folders would need to be removed to install the addon. (remember to bust the cache)

**Screenshots**
Example screenshot using a version of Atlas with a modified toc to prevent fingerprint match. And then installing Atlas via catalog from Curse. Same thing happens when installing recognized addon from alternate source:
![screenshot](https://user-images.githubusercontent.com/68285419/97801574-19b87080-1c3e-11eb-8742-c60c266db17e.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.5.0 from development branch.

**Log Output**
Example log using a version of Atlas with a modified toc to prevent fingerprint match. And then installing Atlas via catalog from Curse. Same thing happens when installing recognized addon from alternate source:
[ajour.log](https://github.com/casperstorm/ajour/files/5470672/ajour.log)

**Comment by tarkah** [comment]
Closed by #330
