### ISSUE TITLE
Settings: Vertical alignment of text in settings is off [Linux]

### ISSUE THREAD

**Issue by hatch8889** [casperstorm/ajour#332]
Text labels in settings are vertically misaligned and being cropped.

OS Linux (Manjaro 20.1.2), Xfce4
Ajour 0.5.0 (also happening in earlier versions)

![Ajour-Screenshot_2020-11-03_10-45-00](https://user-images.githubusercontent.com/51282287/97970873-780e5c00-1dc2-11eb-8912-48a092f73b9e.png)

**Comment by casperstorm** [comment]
In #349 i've fixed so the `Select Directory` buttons won't break, however the vertical issue is not something we can control. Maybe try with another default system font and report back if that fixed the issue. I can't reproduce it on my Manjaro build at least (using default fonts).
