### ISSUE TITLE
Choice of which folders to back up (AddOns/WTF)

### ISSUE THREAD

**Issue by nagha95** [casperstorm/ajour#340]
**Is your feature request related to a problem? Please describe.**
Currently the backup process includes both the AddOns and WTF folders, which combined together can be up to at least a few hundred MB large. This results in a few problems:

- The zipping/backup process takes a while to complete
- Backups can eat up a decent amount of storage space
- If using automatic folder cloud backup (i.e. OneDrive, Google Drive, Dropbox), it can take a while to upload on weak connections and also counts against your cloud storage capacity

**Describe the solution you'd like**
I'd love the ability to choose what to back up by separating the AddOns & WTF folders:

- Implement a checklist for which folders to back up: AddOns, WTF or both.

**Describe alternatives you've considered**
None.

**Additional context**
I personally only need to back up my WTF folder and don't need to keep a backup of my AddOns folder (can always redownload).

The AddOns folder is huge (at least a few hundred MB) especially with RaiderIO installed (which obviously the majority have), while the WTF folder is typically only around ten MB.

I sync my whole backup directory to my Google Drive (using Google Backup & Sync) and currently to upload my WTF folders alone without AddOns, I would need to manually unzip and extract the WTF backups.

**Comment by tarkah** [comment]
@nagha95 I've added this feature in #347. This will be available on the next release. Here is a screenshot of what it looks like...

![image](https://user-images.githubusercontent.com/10239377/98575673-5273cd80-226e-11eb-92d5-f66891a75b29.png)

**Comment by nagha95** [comment]
Awesome, thank you! :)
