### ISSUE TITLE
Chocolatey packages are now "trusted".

### ISSUE THREAD

**Issue by kwilliams1987** [casperstorm/ajour#343]
Not sure how else to contact you about this, but just wanted to let you know that both the `ajour` and `ajour-opengl` packages are marked as trusted.

This means once they pass automated validation they are immediately available for download without human moderation.

Coupled with the increased frequency of my update check script you should have a maximum latency of about 7h from publishing a new version on Github for it to be available via Chocolatey.

Please close/delete this feature when you've read it. :)

**Comment by casperstorm** [comment]
Awesome! Thanks again for the work.
