### ISSUE TITLE
Add addon icons to My Addons and to Catalog

### ISSUE THREAD

**Issue by Trits** [casperstorm/ajour#346]
**Is your feature request related to a problem? Please describe.**
I find it hard to orientate in the list of addons without addon icons  or some sort of visual help to more quickly know what addon I am looking at. And what is it's purpose.

**Describe the solution you'd like**
Please add addon icons as new column similar to Addon name or status (position can be changed and can be disabled). 
This would maybe need to enlarge line height, so the images/icons are easy to see.  

**Additional context**
Example from WowUp:
![image](https://user-images.githubusercontent.com/10000498/98514407-afb95000-2269-11eb-9bb7-83202e40cf22.png)
Example from Twitch:
![image](https://user-images.githubusercontent.com/10000498/98514460-c495e380-2269-11eb-8ca8-981440985b95.png)

**Comment by casperstorm** [comment]
Hi @Trits.
Ajour is trying to be as performant and minimalistic as possible. I only want to show the bare minimum and instead focus on making everything super fast. There is a overhead when fetching multiple images, displaying them etc. and it is something I have chosen does not fit into Ajours vision.

**Comment by Trits** [comment]
Ok, understandable. Thanks for the explanation. If you want (it might be a bad idea): Maybe you can use colored dots for different addon categories or different approach to differentiate the lines visually?

**Comment by casperstorm** [comment]
> Ok, understandable. Thanks for the explanation. If you want (it might be a bad idea): Maybe you can use colored dots for different addon categories or different approach to differentiate the lines visually?

Oh this is actually not a bad idea. This could be fun to explore a little!
UX and UI is VERY important for me, so just because I wont add images I would very much like to ways of improve in some other way. Let me know if you have an idea, mockup etc.

**Comment by Trits** [comment]
Thanks :). I can maybe later try to do some mockups.

Regarding the images: I think they can be done to be fast/not slow down the app (maybe not minimalistic). But I am not familiar with Rust and the libraries you use. And it would need to use some sort of caching mechanism and asynchronous fetching. That sounds like a lot of work, and as I mentioned before - similar UI/UX improvement can be done with different approach.
