### ISSUE TITLE
Buttons sometimes stuck in their highlighted state

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#35]
It's sometimes possible to move the mouse away from the application, and have the state of a button get "stuck" in the moused over appearance.

Ways to reproduce:
Mouse over the "Refresh" button, and then quickly move the pointer up. Or mouse over a "Delete" button and move mouse to the right. 

Since it does not always happen, I think it is caused by the application only registering mouse positions inside the app.

**Comment by casperstorm** [comment]
This is now fixed in https://github.com/hecrj/iced/pull/496. Awaiting the merge so we can update the crate in Ajour.
