### ISSUE TITLE
Resizing Addon Column in Catalog

### ISSUE THREAD

**Issue by braddyb7** [casperstorm/ajour#353]
**Describe the bug**
When in the Catalog, some addon names are too long for the Addon column to display correctly. When attempting to resize the column to make it bigger, the column to the right decreases in size instead. Attempting to decrease the width of the Addon column causes the next column to increase in size. This only affects the Addon column, regardless of its location.

**To Reproduce**
1. Go to Catalog
2. Click on the right edge of the addon column header to resize the column and drag the mouse left or right
3. Column to the right of the Addon column will resize instead

**Expected behavior**
Addon column should increase or decrease in size

**Screenshots**
Before attempting to increase size of Addon column:
![image](https://user-images.githubusercontent.com/439144/98984481-2d0aec00-251a-11eb-8cd3-94a1679642dd.png)

After attempting to increase size of addon column:
![image](https://user-images.githubusercontent.com/439144/98984504-3300cd00-251a-11eb-94da-5115e96ad655.png)

**Software involved**
 - OS: Windows 10 2004
 - Ajour version: 0.5.1 (first noticed in 0.5.0)

**Comment by casperstorm** [comment]
Could you try closing Ajour and delete `%APPDATA%\ajour\ajour.yml` and boot Ajour again to see if it still happens?

**Comment by braddyb7** [comment]
> Could you try closing Ajour and delete `%APPDATA%\ajour\ajour.yml` and boot Ajour again to see if it still happens?

That has indeed fixed the problem.
