### ISSUE TITLE
List of addons not completely sorted

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#36]
The addon list looks sorted alphabetically (good), but there are some exceptions leading me to think it might not be sorted by the title as it is displayed, but as it is listed in the toc file.

See attached examples.
![abc1](https://user-images.githubusercontent.com/68285419/90953016-47c44c00-e468-11ea-9812-3d583b93a532.PNG)
![abc2](https://user-images.githubusercontent.com/68285419/90953017-485ce280-e468-11ea-87b5-31cc072bbaab.PNG)

**Comment by casperstorm** [comment]
Good catch, i was indeed sorting by id (foldername) and not title.
