### ISSUE TITLE
Do not allow empty categories

### ISSUE THREAD

**Issue by Mazwak** [casperstorm/ajour#360]
Problem :

Categories are tied to an API (curse, wowi), but the APIs do not always share the same name.

So if you select API1 and a category from API2, the addon list ends empty, without much feedback on why.

Solution :

1) Make it so the combo only shows categories from the selected API

2) Rename categories so they are the same in both API

**Comment by Mazwak** [comment]
I think solution 2 would be somewhat easier. It might even be done during collection of the JSON file served to clients.

What are you thoughts ?

**Comment by mlablah** [comment]
Your work on this issue (solution 1) is now live with Ajour 0.5.2 - Thank you for your contribution @Mazwak!
