### ISSUE TITLE
ReShade bug.

### ISSUE THREAD

**Issue by Dajova** [casperstorm/ajour#362]
**Describe the bug**
Seems to pickup ReShade installation where there is none. Neither on WoW installation or Ajour itself (even tested to move it around and still it comes up).

**To Reproduce**
1. Have the ReShade program installed anywhere.
2. Download Ajour.
3. Bug happens. *At least i think thats the steps, cus this was with a fresh copy.*
4. The window for ReShade does not go away whatsoever.
5. And when you try to do anything in the ReShade window whatsoever, it completely stalls the program and have to restart it.

**Expected behavior**
ReShade should *NOT* appear like this.

**Screenshots**
![image](https://i.imgur.com/eVoYVUQ.pngurl)
![image2](https://i.imgur.com/h7jglSq.png)
*Don't mind the area on the right, that's from RTSS (which frankly shouldnt pop up either, but w/e).*

**Software involved**
 - OS: Win10 Pro
 - Ajour version: 0.5.1

**Additional context**
I have never seen this happen. Ever. Normally you should tell ReShade to install itself into a game, not the other way around.

**Log Output**
[ajour.log](https://github.com/casperstorm/ajour/files/5555783/ajour.log)

**Comment by casperstorm** [comment]
This is a issue you should redirect towards ReShade.
It is ReShade attaching, so it's their logic which fails.
