### ISSUE TITLE
Certain github repositories output an error message

### ISSUE THREAD

**Issue by eburkey** [casperstorm/ajour#365]
Certain github repositories output an error message instead of downloading. One example is https://github.com/phriked/AstralKeys

The error message is "missing field 'tag_name' at line 4 column 1" for the above URL.

A friend had the same error on Windows 10.

**Screenshots**
![2020-11-18-173953_1920x1080_scrot](https://user-images.githubusercontent.com/74691627/99609673-389c5e00-29c5-11eb-8c14-1c74f613dd4f.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10 and Linux
 - Ajour version: 0.5.1

**Log Output**
17:39:08.632 [ajour][INFO] Ajour 0.5.1 has started.
17:39:08.632 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        ignored: {
            Retail: [],
            Classic: [],
        },
        release_channels: {
            Classic: {},
            Retail: {},
        },
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: Some(
        (
            958,
            1057,
        ),
    ),
    scale: None,
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
}
17:39:08.632 [ajour::gui][DEBUG] antialiasing: true
17:39:08.665 [ajour_core::utility][DEBUG] checking for application update
17:39:08.665 [ajour_core::theme][DEBUG] loading user themes
17:39:08.666 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
17:39:08.727 [ajour::gui::update][DEBUG] Message::CachesLoaded(error: false)
17:39:08.727 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
17:39:08.730 [ajour::gui::update][DEBUG] Message::Parse
17:39:08.730 [ajour::gui::update][DEBUG] preparing to parse addons in "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns"
17:39:08.730 [ajour::gui::update][DEBUG] preparing to parse addons in "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_ptr_/Interface/AddOns"
17:39:08.730 [ajour::gui::update][DEBUG] preparing to parse addons in "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_beta_/Interface/AddOns"
17:39:08.730 [ajour::gui::update][DEBUG] preparing to parse addons in "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_classic_/Interface/AddOns"
17:39:08.730 [ajour::gui::update][DEBUG] preparing to parse addons in "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_classic_ptr_/Interface/AddOns"
17:39:08.730 [ajour_core::parse][DEBUG] Retail - parsing addons folder
17:39:08.730 [ajour_core::parse][DEBUG] Retail PTR - parsing addons folder
17:39:08.730 [ajour_core::parse][DEBUG] Retail Beta - parsing addons folder
17:39:08.730 [ajour_core::parse][DEBUG] Classic - parsing addons folder
17:39:08.730 [ajour_core::parse][DEBUG] Classic PTR - parsing addons folder
17:39:08.730 [ajour_core::parse][DEBUG] Retail - 29 folders in AddOns directory to parse
17:39:08.730 [ajour_core::parse][DEBUG] Classic - 21 folders in AddOns directory to parse
17:39:08.730 [ajour_core::parse][DEBUG] Retail - 29 fingerprints: 29 cached, 0 calculated, 0 added, 0 removed
17:39:08.731 [ajour::gui::update][ERROR] Message::ParsedAddons(Retail Beta) - Addon directory not found: "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_beta_/Interface/AddOns"
17:39:08.731 [ajour::gui::update][ERROR] Message::ParsedAddons(Retail PTR) - Addon directory not found: "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_ptr_/Interface/AddOns"
17:39:08.731 [ajour::gui::update][ERROR] Message::ParsedAddons(Classic PTR) - Addon directory not found: "/home/evan/.lutris/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_classic_ptr_/Interface/AddOns"
17:39:08.731 [ajour_core::parse][DEBUG] Classic - 21 fingerprints: 21 cached, 0 calculated, 0 added, 0 removed
17:39:08.733 [ajour_core::parse][DEBUG] Classic - 21 addon folders successfully parsed from '.toc'
17:39:08.733 [ajour_core::parse][DEBUG] Classic - 0 cached entries
17:39:08.733 [ajour_core::parse][DEBUG] Classic - 21 unique fingerprints to check against curse api
17:39:08.733 [ajour_core::parse][DEBUG] Retail - 29 addon folders successfully parsed from '.toc'
17:39:08.733 [ajour_core::parse][DEBUG] Retail - 1 cached entries
17:39:08.733 [ajour_core::parse][DEBUG] Retail - 27 unique fingerprints to check against curse api
17:39:08.923 [ajour::gui::update][DEBUG] Message::LatestRelease(Some("0.5.1"))
17:39:09.500 [ajour_core::parse][DEBUG] Retail - 8 curse packages fetched
17:39:09.500 [ajour_core::parse][DEBUG] Retail - 0 tukui packages fetched
17:39:09.667 [ajour_core::parse][DEBUG] Retail - 3 wowi packages fetched
17:39:09.688 [ajour_core::parse][DEBUG] Classic - 8 curse packages fetched
17:39:09.688 [ajour_core::parse][DEBUG] Classic - 0 tukui packages fetched
17:39:09.890 [ajour_core::parse][DEBUG] Classic - 2 wowi packages fetched
17:39:09.890 [ajour_core::parse][DEBUG] Classic - 0 git packages fetched
17:39:09.890 [ajour_core::parse][DEBUG] Classic - 8 addons built from curse packages
17:39:09.890 [ajour_core::parse][DEBUG] Classic - 0 addons built from tukui packages
17:39:09.890 [ajour_core::parse][DEBUG] Classic - 0 addons built from wowi packages
17:39:09.890 [ajour_core::parse][DEBUG] Classic - 0 addons built from git packages
17:39:09.890 [ajour_core::parse][DEBUG] Classic - 0 unknown addon folders
17:39:09.890 [ajour_core::parse][DEBUG] Classic - 8 addons successfully parsed
17:39:09.891 [ajour::gui::update][DEBUG] Message::ParsedAddons(Classic, 8 addons)
17:39:09.913 [ajour_core::parse][DEBUG] Retail - 1 git packages fetched
17:39:09.914 [ajour_core::parse][DEBUG] Retail - 8 addons built from curse packages
17:39:09.914 [ajour_core::parse][DEBUG] Retail - 0 addons built from tukui packages
17:39:09.914 [ajour_core::parse][DEBUG] Retail - 0 addons built from wowi packages
17:39:09.914 [ajour_core::parse][DEBUG] Retail - 1 addons built from git packages
17:39:09.914 [ajour_core::parse][DEBUG] Retail - 0 unknown addon folders
17:39:09.914 [ajour_core::parse][DEBUG] Retail - 9 addons successfully parsed
17:39:09.915 [ajour::gui::update][DEBUG] Message::ParsedAddons(Retail, 9 addons)
17:39:11.691 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(15527 addons in catalog)
17:39:14.899 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Install)
17:39:17.282 [ajour::gui::update][DEBUG] Interaction::InstallAddon(Retail, Source)
17:39:17.499 [ajour::gui::update][ERROR] missing field `tag_name` at line 4 column 1

**Comment by eburkey** [comment]
Another example: https://github.com/DengSir/tdBattlePetScript

**Comment by casperstorm** [comment]
Hi @eburkey,

Reason they don't work is that none of the authors of those repos has published a release of their addon.
Take a look at https://github.com/Hekili/hekili or https://github.com/DeadlyBossMods/DeadlyBossMods/ to see how it looks with a proper release.

The once you linked have only tagged their commit, and not bundled it togeter. A solution would be to create a issue at those repos and ask them to do a proper GitHub release. You could point them to the two i mentioned if they want to see how its done.

I'll also update Ajour later to give the user a little more info about this, because right now it does seem like a bug.

**Comment by eburkey** [comment]
@casperstorm After looking at a few repos last night I wondered if that was the problem. Thanks for the answer!
