### ISSUE TITLE
Doesnt exit right away

### ISSUE THREAD

**Issue by pmo** [casperstorm/ajour#366]
Not really an important issue, I have just noticed that when you try to exit on windows 10 machines, it becomes unresponsive for a while and then it looks like it crashes instead of shutting down. But it still has the intended effect.

**Comment by casperstorm** [comment]
We have not been able to recreate this. Could you send us your ajour.log and ajour.yml files?

**Comment by pmo** [comment]
Where do i find those two files?

**Comment by pmo** [comment]
`15:07:14.132 [ajour][INFO] Ajour 0.5.2 has started.
15:07:14.133 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "F:\\World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        ignored: {
            Retail: [],
            Classic: [],
        },
        release_channels: {
            Retail: {},
            Classic: {},
        },
    },
    theme: Some(
        "Dark",
    ),
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: None,
    scale: None,
    backup_directory: Some(
        "F:\\World of Warcraft\\backup",
    ),
    backup_addons: true,
    backup_wtf: true,
    hide_ignored_addons: false,
}
15:07:14.133 [ajour::gui][DEBUG] antialiasing: true
15:07:14.142 [ajour_core::utility][DEBUG] checking for application update
15:07:14.142 [ajour_core::theme][DEBUG] loading user themes
15:07:14.143 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
15:07:14.504 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
15:07:14.504 [ajour::gui::update][DEBUG] Message::CachesLoaded(error: false)
15:07:14.504 [ajour::gui::update][DEBUG] Message::LatestRelease(Some("0.5.2"))
15:07:14.510 [ajour::gui::update][DEBUG] Message::Parse
15:07:14.511 [ajour::gui::update][DEBUG] preparing to parse addons in "F:\\World of Warcraft\\_retail_\\Interface/AddOns"
15:07:14.511 [ajour::gui::update][DEBUG] preparing to parse addons in "F:\\World of Warcraft\\_ptr_\\Interface/AddOns"
15:07:14.511 [ajour::gui::update][DEBUG] preparing to parse addons in "F:\\World of Warcraft\\_beta_\\Interface/AddOns"
15:07:14.511 [ajour::gui::update][DEBUG] preparing to parse addons in "F:\\World of Warcraft\\_classic_\\Interface/AddOns"
15:07:14.512 [ajour::gui::update][DEBUG] preparing to parse addons in "F:\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
15:07:14.512 [ajour_core::parse][DEBUG] Retail - parsing addons folder
15:07:14.512 [ajour_core::parse][DEBUG] Classic PTR - parsing addons folder
15:07:14.512 [ajour_core::parse][DEBUG] Retail Beta - parsing addons folder
15:07:14.512 [ajour_core::parse][DEBUG] Classic - parsing addons folder
15:07:14.512 [ajour_core::parse][DEBUG] Retail PTR - parsing addons folder
15:07:14.512 [ajour_core::parse][DEBUG] Classic - 2 folders in AddOns directory to parse
15:07:14.512 [ajour_core::parse][DEBUG] Retail - 31 folders in AddOns directory to parse
15:07:14.513 [ajour_core::parse][DEBUG] Classic - 2 fingerprints: 2 cached, 0 calculated, 0 added, 0 removed
15:07:14.514 [ajour::gui::update][ERROR] Message::ParsedAddons(Classic PTR) - Addon directory not found: "F:\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
15:07:14.514 [ajour::gui::update][ERROR] Message::ParsedAddons(Retail PTR) - Addon directory not found: "F:\\World of Warcraft\\_ptr_\\Interface/AddOns"
15:07:14.514 [ajour::gui::update][ERROR] Message::ParsedAddons(Retail Beta) - Addon directory not found: "F:\\World of Warcraft\\_beta_\\Interface/AddOns"
15:07:14.514 [ajour::gui::update][DEBUG] Message::LatestBackup(Some(2020-11-19T14:46:50))
15:07:14.515 [ajour_core::parse][DEBUG] Retail - 31 fingerprints: 31 cached, 0 calculated, 0 added, 0 removed
15:07:14.515 [ajour_core::parse][DEBUG] Classic - 2 addon folders successfully parsed from '.toc'
15:07:14.515 [ajour_core::parse][DEBUG] Classic - 0 cached entries
15:07:14.515 [ajour_core::parse][DEBUG] Classic - 2 unique fingerprints to check against curse api
15:07:14.518 [ajour_core::parse][DEBUG] Retail - 31 addon folders successfully parsed from '.toc'
15:07:14.518 [ajour_core::parse][DEBUG] Retail - 0 cached entries
15:07:14.518 [ajour_core::parse][DEBUG] Retail - 31 unique fingerprints to check against curse api
15:07:14.921 [ajour_core::catalog][DEBUG] Successfully fetched and parsed https://github.com/casperstorm/ajour-catalog/releases/latest/download/tukui.json
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 2 curse packages fetched
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 0 tukui packages fetched
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 0 wowi packages fetched
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 0 git packages fetched
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 2 addons built from curse packages
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 0 addons built from tukui packages
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 0 addons built from wowi packages
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 0 addons built from git packages
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 0 unknown addon folders
15:07:15.356 [ajour_core::parse][DEBUG] Classic - 2 addons successfully parsed
15:07:15.358 [ajour::gui::update][DEBUG] Message::ParsedAddons(Classic, 2 addons)
15:07:15.524 [ajour_core::parse][DEBUG] Retail - 20 curse packages fetched
15:07:15.832 [ajour_core::catalog][DEBUG] Successfully fetched and parsed https://github.com/casperstorm/ajour-catalog/releases/latest/download/wowi.json
15:07:15.981 [ajour_core::parse][DEBUG] Retail - 1 tukui packages fetched
15:07:16.136 [ajour_core::catalog][DEBUG] Successfully fetched and parsed https://github.com/casperstorm/ajour-catalog/releases/latest/download/curse.json
15:07:16.189 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(15543 addons in catalog)
15:07:16.246 [ajour_core::parse][DEBUG] Retail - 3 wowi packages fetched
15:07:16.246 [ajour_core::parse][DEBUG] Retail - 0 git packages fetched
15:07:16.246 [ajour_core::parse][DEBUG] Retail - 20 addons built from curse packages
15:07:16.246 [ajour_core::parse][DEBUG] Retail - 1 addons built from tukui packages
15:07:16.246 [ajour_core::parse][DEBUG] Retail - 0 addons built from wowi packages
15:07:16.246 [ajour_core::parse][DEBUG] Retail - 0 addons built from git packages
15:07:16.246 [ajour_core::parse][DEBUG] Retail - 0 unknown addon folders
15:07:16.246 [ajour_core::parse][DEBUG] Retail - 21 addons successfully parsed
15:07:16.247 [ajour::gui::update][DEBUG] Message::ParsedAddons(Retail, 21 addons)
15:07:18.543 [ajour::gui::update][DEBUG] Interaction::ModeSelected(About)
15:07:21.861 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Settings)
`

**Comment by pmo** [comment]
```
---
wow:
  directory: "F:\\World of Warcraft"
  flavor: Retail
addons:
  ignored:
    Classic: []
    Retail: []
  release_channels:
    Retail: {}
    Classic: {}
theme: Dark
column_config:
  V1:
    local_version_width: 150
    remote_version_width: 150
    status_width: 85
window_size: ~
scale: ~
backup_directory: "F:\\World of Warcraft\\backup"
backup_addons: true
backup_wtf: true
```

**Comment by pmo** [comment]
[ajour.log](https://github.com/casperstorm/ajour/files/5577747/ajour.log)

**Comment by pmo** [comment]
[ajour.yml.txt](https://github.com/casperstorm/ajour/files/5577750/ajour.yml.txt)

**Comment by pmo** [comment]
for me its every time i close it down, it becomes unresponsive then closes.

**Comment by casperstorm** [comment]
See https://github.com/casperstorm/ajour/issues/453.
Will close this issue in favor of above.
