### ISSUE TITLE
Updating Classic Addon from wrong source

### ISSUE THREAD

**Issue by lauenchr** [casperstorm/ajour#371]
**Describe the bug**
Before I discovered Ajour I manually installed the GatherMate2 addon from this source:
https://www.curseforge.com/wow/addons/gathermate2-classic

Now I use Ajour and it told me the addon was updated (which is correct).
However it used WoWInterface as a source to update it (https://www.wowinterface.com/downloads/info21293) and installed a Shadowlands-Prepatch version of the addon which then throws tons of lua errors within the game.

**To Reproduce**
1. Install the classic version of the addon (url above) outside of Ajour
2. Start Ajour
3. Update the addon with ajour

**Expected behavior**
Only update addons with the according game version.
If it was possible to change the source - that would also be sufficient.

**Screenshots**
![image](https://user-images.githubusercontent.com/47520341/99807066-3958ff80-2b3f-11eb-931f-2b7c0411d5b6.png)
![image](https://user-images.githubusercontent.com/47520341/99807166-5ee60900-2b3f-11eb-8223-989319f35ebd.png)

**Software involved**
Please complete the following information:
 - OS: Win 10
 - Ajour version: 0.5.1
 - WoW Classic

**Comment by mlablah** [comment]
Hello @lauenchr - Thank you for reporting this issue!

I have tried to reproduce the error using your description.

I downloaded the addon from the curseforge link you provided. This is how it appears in my Ajour afterwards:
![image](https://user-images.githubusercontent.com/68285419/99846083-03833d80-2b76-11eb-9b16-ed75e787950e.png)

It was able to match it against CurseForge (not WoWInterface) and showed no available update.

I then tried forcing an update anyway (via `Force update` in the addon details), which didn't affect the addon. It is still being listed as a CurseForge addon with no available updates and with the same version I manually installed:
![image](https://user-images.githubusercontent.com/68285419/99846217-3af1ea00-2b76-11eb-97ab-25b625a81f96.png)
![image](https://user-images.githubusercontent.com/68285419/99846227-3f1e0780-2b76-11eb-9d4d-9ae962ef2fdb.png)

It could be that you have some metadata for the addon leftover from a previous installation via the Ajour catalog, which wasn't cleared if you deleted the addon outside of Ajour (I'm just speculating here 🙂).

Would you mind attaching the `addons.yml` file from ajour config folder? By default it should be located here: `%appdata%\ajour\cache\addons.yml`?

**Comment by lauenchr** [comment]
Had to zip it because github.
[addons.zip](https://github.com/casperstorm/ajour/files/5580354/addons.zip)
I took a look inside and indeed it is the only addon that is listed there and the repository is specifically set to WowI.
Can I just delete the entry or do I need to take other precautions?

**Comment by lauenchr** [comment]
Update: temp backupped the file and removed the entry. Started the client and curse is correctly used. The force update did work as well. I am unsure how the constellation came to be. I am closing the issue and will reopen it if I encounter the issue again with further infos hopefully
