### ISSUE TITLE
WoWInterface only addon ImpliedTarget not found in catalog

### ISSUE THREAD

**Issue by Walkerbo** [casperstorm/ajour#374]
_**Describe the bug**_
The ImpliedTarget addon is not available through the catalog.
https://www.wowinterface.com/downloads/info17648-ImpliedTarget.html

_**To Reproduce**_
Open the catalog and type in ImpliedTarget.

_**Expected behavior**_
The ImpliedTarget addon should be found.

_**Software involved**_
Windows 10
Ajour version 0.5.2

**Comment by casperstorm** [comment]
Remember to change source to WoWInterface, then you should be able to see it!

<img width="1069" alt="Screenshot 2020-11-21 at 06 34 46" src="https://user-images.githubusercontent.com/2248455/99868552-bfb72500-2bc3-11eb-9d0b-fac702c4cc25.png">

**Comment by Walkerbo** [comment]
Doh, I cant believe I didn't work that out.    :)

**Comment by casperstorm** [comment]
> Doh, I cant believe I didn't work that out.    :)

No worries, please let me know if there's anything else!
