### ISSUE TITLE
Windows 10 - Invalid digital signature

### ISSUE THREAD

**Issue by Robbllle** [casperstorm/ajour#375]
**Describe the bug**
Windows 10 SmartScreen prevents installing the app. With the dev mode active it says the digital signature is invalid. Is this intended?

**Expected behavior**
Installer has a valid digital signature.

**Screenshots**
![image](https://user-images.githubusercontent.com/74823859/99878902-e0559e00-2c08-11eb-96c9-a3d621977e1b.png)

**Software involved**
 - OS: Windows 10 Pro, Version 20H2, Build 19042.630
 - Ajour version: 0.5.2 dowloaded from Github

**Comment by casperstorm** [comment]
See https://github.com/casperstorm/ajour/issues/193#issuecomment-703287870

I'll close this for now.
