### ISSUE TITLE
Ajour crash on open (Mac OS X 10.13.6)

### ISSUE THREAD

**Issue by susan-montooth** [casperstorm/ajour#384]
**Describe the bug**
Ajour-opengl crashes immediately when opened on MacOS X 10.13.6 (late 2013 iMac)

**To Reproduce**
1. Download and install ajour-opengl.dmg (previously tried non-opengl version which crashed much faster)
2. Right-click app and select Open
3. See "Ajour quit unexpectedly" error

**Expected behavior**
No crash

**Screenshots**
n/a

**Software involved**
Please complete the following information:
 - OS: [e.g. "Mac OS X 10.13.6"]
 - Ajour version: 1.0.0
 - (if applicable) n/a

**Additional context**
I realize supporting older OS and hardware is not a reasonable ask! Thanks for your work. Attaching the log from the crash dialog.
[ajour-crash.txt](https://github.com/casperstorm/ajour/files/5580207/ajour-crash.txt)

**Log Output**
12:54:00.402 [ajour][INFO] Ajour 0.5.2 has started.
12:54:00.403 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: None,
        flavor: Retail,
    },
    addons: Addons {
        ignored: {},
        release_channels: {},
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: None,
    scale: None,
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
    hide_ignored_addons: false,
}
12:54:00.403 [ajour::gui][DEBUG] antialiasing: false
12:54:00.431 [ajour_core::utility][DEBUG] checking for application update
12:54:00.431 [ajour_core::theme][DEBUG] loading user themes
12:54:00.435 [ajour_core::fs::theme][DEBUG] loaded 0 user themes

**Comment by casperstorm** [comment]
Closed in favor for #153. It seems like it's the same crash on the same platform.
