### ISSUE TITLE
Windows interface/wtf backup unusable on Mac

### ISSUE THREAD

**Issue by pldimarco** [casperstorm/ajour#385]
**Describe the bug**
Backing up the interface and wtf folders on windows produces a zip file that is usable on windows. But when I copy that file over a Mac, it extracts in a very weird way. It is doing weird things with the directory structure. I manually created a zip on Windows, using 7zip, of the interface and wtf folders and that worked fine. See picture for example extracted files on Mac.

**To Reproduce**
1. Create a backup on Windows
2. Copy zip file to Mac
3. Extract zip file

**Expected behavior**
The extracted directory should look like the source directories.

**Screenshots**
![Screen Shot 2020-11-23 at 8 33 10 AM](https://user-images.githubusercontent.com/6627983/99968366-0bee9a80-2d67-11eb-90aa-184a69d038a7.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10/MacOS 10.15.7
 - Ajour version: 0.5.2
 - (if applicable) Addon name, flavor (classic or retail) and version: N/A

**Additional context**
None

**Log Output**
```
08:39:38.845 [ajour::gui::update][DEBUG] Interaction::Backup
08:39:39.754 [ajour::gui::update][DEBUG] Message::BackupFinished(08:39:38)
```

**Comment by casperstorm** [comment]
I've just reproduced this. Must be a issue with going from `\` to `/`. But we can't be supposed to manually handle that, it must be a flag or option we can use. I have attached a .zip which when unpacked on Windows i borked.

Maybe @tarkah knows something?
 
[ajour_backup_2020-11-23_16-29-24.zip](https://github.com/casperstorm/ajour/files/5584015/ajour_backup_2020-11-23_16-29-24.zip)

**Comment by tarkah** [comment]
Weird, this must be an upstream bug as I confirmed we are using the API for the `zip` library correctly... I'll try to see if I can find anything upstream.

**Comment by tarkah** [comment]
For the life of me I couldn't find any upstream issue related to this. @pldimarco are you able to attach the backup here so I can take a closer look at the zip file and test on linux and macos.

**Comment by casperstorm** [comment]
> For the life of me I couldn't find any upstream issue related to this. @pldimarco are you able to attach the backup here so I can take a closer look at the zip file and test on linux and macos.

The zip I posted above does not work for me on macOS.

**Comment by tarkah** [comment]
Ok, just tested on linux and get the same issue. I tested with one of my own backups from windows and it's messed up on linux as well. Linux -> Windows backups work fine.

I'll see if replacing the path separators from `\` on windows to `/` solves the problem and works for both directions.

**Comment by svasek** [comment]
The [.zip file specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) states:

> 4.4.17.1 The name of the file, with optional relative path. The path stored MUST not contain a drive or device letter, or a leading slash. All slashes MUST be forward slashes '/' as opposed to backwards slashes '\' for compatibility with Amiga and UNIX file systems etc. If input came from standard input, there is no file name field.

**Comment by tarkah** [comment]
@svasek thanks! Crazy the library wouldn't normalize that under the hood since that's a hard zip spec
