### ISSUE TITLE
Upload to crates.io

### ISSUE THREAD

**Issue by sovareign** [casperstorm/ajour#388]
**Is your feature request related to a problem? Please describe.**
I installed the program via cargo and updating through the app does not work because of a missing AppImage environment variable (obvious, since I'm not using the AppImage). To update the crate I have to run `cargo install` again with the GitHub Repo link.

**Describe the solution you'd like**
Basically what the title already says. Make ajour available on crates.io to make it easier to find and update the package.

**Describe alternatives you've considered**
The reason I have it installed through cargo is because I don't like AppImages. So I personally would also be content if this program was available through flatpak (or snap).

**Comment by casperstorm** [comment]
Would love to put it on crates.io but right now we are targeting `iced` by a rev:
https://github.com/casperstorm/ajour/blob/307ba399713fa455e3bf3668873166caad23a17e/Cargo.toml#L23-L25

We can't put it up before we use a proper release from `iced` and their recent is from april, however it's still active developed so I think its just a matter of asking them to make a release so we can then publish to crates.

**Comment by tarkah** [comment]
@sovareign this is now possible! I've published our `0.5.4-rc.1` version. Since its a prerelease, you'll need to specific the version such as:

```
cargo install ajour --version 0.5.4-rc.1
```

**Comment by tarkah** [comment]
Note that the "self update" feature won't work since you're running on linux and we only publish the `.AppImage`. You can just update with cargo though :)
