### ISSUE TITLE
Display changelog for addons

### ISSUE THREAD

**Issue by milan-stojanovic** [casperstorm/ajour#394]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to view changelog of each addon, I would like to see what has changed in each new version (if addon supports it).

**Describe the solution you'd like**
Viewing details of specific addon should allow for an option to view changelog for that addon (if it supports changelog, I believe this depends on the source of the addon).

Example from CurseForge:
![Screenshot 2020-11-27 235926](https://user-images.githubusercontent.com/10252583/100488123-9ee35800-310c-11eb-807e-73270bdff891.png)

**Comment by casperstorm** [comment]
You can view changelog by clicking the remote or local version :-)

**Comment by Neurotoxin001** [comment]
> You can view changelog by clicking the remote or local version :-)

In 0.5.4 I can't. It just opens addon info.

**Comment by Neurotoxin001** [comment]
Can you reopen this issue?
