### ISSUE TITLE
Systray support

### ISSUE THREAD

**Issue by tarkah** [casperstorm/ajour#397]
Add support for minimizing to systray

**Comment by tarkah** [comment]
We've decided to not support this feature as it adds too much platform specific complexity to Ajour and can not be implemented in a optimal way due to the limitations of the GUI framework we are using.

**Comment by casperstorm** [comment]
> Feels bad man, was just about to request this.

You can use a .ps1 script to make wrap it with tray support:
https://github.com/ajour/ajour/wiki/Adding-System-Tray-capabilities-to-Ajour-with-PowerShell-script

**Comment by Drake356** [comment]
> 
> 
> > Feels bad man, was just about to request this.
> 
> You can use a .ps1 script to make wrap it with tray support:
> https://github.com/ajour/ajour/wiki/Adding-System-Tray-capabilities-to-Ajour-with-PowerShell-script

This is pretty big and awesome. This should definitely be linked on the main github page and website because it pretty much makes the auto update feature usable and useful to most of us that like to keep inactive or background programs on the system tray and keep more active programs on taskbar.

**Comment by tarkah** [comment]
@Drake356 heads up, we are rolling out an official sys tray for Ajour. See here #615. There's a couple small upstream blockers but hopefully we can rollout in the next couple weeks.
