### ISSUE TITLE
Improve search matching

### ISSUE THREAD

**Issue by ascott18** [casperstorm/ajour#398]
**Is your feature request related to a problem? Please describe.**
Searching the catalog for "handynotes shadowlands" return zero results. Searching for "handynotes: shadowlands" returns two results.

**Describe the solution you'd like**
Search should ignore punctuation when determining matches.

**Additional context**
![image](https://user-images.githubusercontent.com/5017521/100526247-e94fed80-317b-11eb-8924-b89bb8155fde.png)
![image](https://user-images.githubusercontent.com/5017521/100526252-ee14a180-317b-11eb-8444-c5353d186901.png)

**Comment by tarkah** [comment]
Our filter logic is SUPER basic right now. All we do is convert everything to lowercase and check if the search term is contained in the title.

We should implement some sort of fuzzy search to handle this better.

**Comment by tarkah** [comment]
@casperstorm in doing a fuzzy match, we will generate a score from the match. We obviously need to set a filter threshold on this. But we can also sort by this. When a user types into the search bar, would it makes sense to override the current sort and instead sort by the fuzzy match score?

**Comment by casperstorm** [comment]
> @casperstorm in doing a fuzzy match, we will generate a score from the match. We obviously need to set a filter threshold on this. But we can also sort by this. When a user types into the search bar, would it makes sense to override the current sort and instead sort by the fuzzy match score?

I think it would, yes. Great idea @tarkah. Also a funny task.

**Comment by tarkah** [comment]
@ascott18 I finally got around to implementing this. See how it works with my purposely misspelled search. This will be added with #419 and should be available in the next prerelease. 

As of 0.5.4 you can go into settings and set your self update channel to Beta and get this once we push out the next pre-release if you want it a bit faster than waiting for whenever we push out 0.5.5

![image](https://user-images.githubusercontent.com/10239377/101555183-f3889d80-396c-11eb-8993-d8b023fd30f5.png)
