### ISSUE TITLE
Support updating weak auras from wago.io

### ISSUE THREAD

**Issue by athei** [casperstorm/ajour#401]
Many players nowadays have more weak auras than actual add-ons. Keeping them updated requires manual intervention or the usage of yet another add-on manager ( https://weakauras.wtf ).

It would be nice if this functionality could be integrated into ajour. [Cursebreaker](https://github.com/AcidWeb/CurseBreaker) does support updating weak auras.

**Comment by nerzhul** [comment]
it could a very very powerful feature
