### ISSUE TITLE
Add a button to clear WoW cache in the settings

### ISSUE THREAD

**Issue by Blixtmen** [casperstorm/ajour#402]
C:\Program Files (x86)\World of Warcraft\_retail_\Cache
C:\Program Files (x86)\World of Warcraft\_retail_\GPUCache
C:\Program Files (x86)\World of Warcraft\_classic_\Cache
C:\Program Files (x86)\World of Warcraft\_classic_\GPUCache

These eventually start drastically increasing load times, it would be a great QOL addition if you could clear them from inside of ajour!

Edit: Bonus points if it shows how large the folders are

**Comment by mlablah** [comment]
Thank you @Blixtmen for using Ajour and making this request. 

Unfortunately we don't think a feature to delete WoW's cache folders from within Ajour is something that would be used by a significant portion of our users and would like to keep the app as clean and simple as possible.
