### ISSUE TITLE
Instant closing of app.

### ISSUE THREAD

**Issue by Bulkathas** [casperstorm/ajour#406]
**Describe the bug**
Program closes after launching it, doesn't do so with OpenGL version but has worse text appearance on OpenGL version.

**To Reproduce**
1. Double click executable (forced Admin mode - same result)
2. Wait
3. Begins to open (white box)
4. Closes out.

**Expected behavior**
App opens, UI shows, operates as needed to update addons and change settings.

**Screenshots**

**Software involved**
Please complete the following information:
 - OS: Windows 10 20h2 fully updated.
 - Ajour version: 0.5.3
 

**Additional context**
As stated above - works if I use OpenGL but not standard version, haven't had any other issues with software on same PC which should have more than sufficient specifications to run Ajour.
**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.

18:44:18.556 [ajour][INFO] Ajour 0.5.3 has started.
18:44:18.557 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "C:\\World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        ignored: {
            Classic: [],
            Retail: [],
            RetailBeta: [],
        },
        release_channels: {
            RetailBeta: {},
            Retail: {},
            Classic: {},
        },
    },
    theme: Some(
        "Alliance",
    ),
    column_config: V3 {
        my_addons_columns: [
            ColumnConfigV2 {
                key: "title",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "local",
                width: Some(
                    150,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "remote",
                width: Some(
                    150,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "status",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "channel",
                width: Some(
                    85,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "author",
                width: Some(
                    85,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    110,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "date_released",
                width: Some(
                    110,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    110,
                ),
                hidden: true,
            },
        ],
        catalog_columns: [
            ColumnConfigV2 {
                key: "addon",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "description",
                width: Some(
                    205,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    30,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "num_downloads",
                width: Some(
                    105,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    105,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "date_released",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "install",
                width: Some(
                    85,
                ),
                hidden: false,
            },
        ],
    },
    window_size: Some(
        (
            1920,
            1017,
        ),
    ),
    scale: Some(
        1.2,
    ),
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
    hide_ignored_addons: false,
}
18:44:18.558 [ajour::gui][DEBUG] antialiasing: true
18:44:18.564 [ajour_core::utility][DEBUG] checking for application update
18:44:18.564 [ajour_core::theme][DEBUG] loading user themes
18:44:18.565 [ajour_core::fs::theme][DEBUG] loaded 0 user themes

**Comment by casperstorm** [comment]
Do you have a screenshot of how the OpenGL version look?
And do you mind posting what GPU and CPU you have?

**Comment by casperstorm** [comment]
See https://github.com/casperstorm/ajour/issues/453.
Will close this issue in favor of above.
