### ISSUE TITLE
Remote release channel is "50 years ago" for every addon

### ISSUE THREAD

**Issue by slabstone** [casperstorm/ajour#414]
**Describe the bug**
Remote release channel "Stable" says "50 years ago" for every addon. It worked before, maybe related to Twitch/Curse/Overwolf shenanigans.

**To Reproduce**
1. Open Ajour
2. Click on any addon to show addon info

**Expected behavior**
Actual addon update date

**Screenshots**
[Imgur](https://imgur.com/QMmzmEM)

**Software involved**
Please complete the following information:
 - OS: Windows 10 2004
 - Ajour version: 0.5.3
 - Addon name, flavor (classic or retail) and version: any retail addon, for example Auctionator 9.0.0.8

**Additional context**
n/a

**Log Output**
https://pastebin.com/bjgE9qiG

**Comment by illum1n4ti** [comment]
Only with CurseForge. WoWinterface doing fine

**Comment by Dylan-DPC** [comment]
Can confirm. i'm enjoying the "truly classic experience" 
![image](https://user-images.githubusercontent.com/12371125/101247589-c17ffd00-371a-11eb-9099-bcad6aa4237c.png)

**Comment by casperstorm** [comment]
It's our middleware API which is currently giving us wrong data.
I'm on it right now. Sorry for the troubles.

**Comment by mlablah** [comment]
API now returning correct filedates for each addon's "latest release".

**Comment by Dreamjammer** [comment]
Still seeing this for half my addons. :\

**Comment by StanoRiga** [comment]
same here. seems not fixed

**Comment by Neurotoxin001** [comment]
https://www.curseforge.com/wow/addons/blizzmove
https://www.curseforge.com/wow/addons/auctionator
These broken for me, no stable releases, but it on curseforge.
