### ISSUE TITLE
Sorting Changed?

### ISSUE THREAD

**Issue by Brightbrown** [casperstorm/ajour#422]
**Describe the bug**
"Ignore" items flow to the top under "Update"

**Expected behavior**
They sort to the bottom of the list as they did in 0.5.3

**Screenshots**

**Software involved**
macOSX

![Screen Shot 2020-12-08 at 8 28 59 PM](https://user-images.githubusercontent.com/43913875/101585411-b55f9e00-39ad-11eb-9588-f259ff24d663.jpg)

**Comment by casperstorm** [comment]
Thanks for reporting this @Brightbrown. I've fixed it in https://github.com/casperstorm/ajour/pull/423.

**Comment by Brightbrown** [comment]
thank you!
