### ISSUE TITLE
Application no resizable on wayland since 0.5.4

### ISSUE THREAD

**Issue by nerzhul** [casperstorm/ajour#427]
**Describe the bug**
Application window no resizable on wayland since 0.5.4

**To Reproduce**
Launch app on wayland, try to resize, you cannot

It worked on 0.5.3

**Expected behavior**
We should ensure resizing works

**Screenshots**
![Capture d’écran du 2020-12-10 16-04-15](https://user-images.githubusercontent.com/119752/101789262-5f9c0a80-3b01-11eb-8a05-76f20d7f8e98.png)

Also the maximize doesn't work neither

**Software involved**
Please complete the following information:
 - OS: Archlinux
 - Ajour version: 0.5.4

**Additional context**

**Log Output**
I take a look but there is no error or warning, only valid info

**Comment by tarkah** [comment]
I'll look to see what dependencies updates in our Cargo.lock file since 0.5.3. I'm sure one of them is related to wayland and has an upstream regression. If so, we can lock it back to the old version.

**Comment by tarkah** [comment]
While I look into that, can you see if the `opengl` version works with wayland?

**Comment by nerzhul** [comment]
how can i use it ?

**Comment by casperstorm** [comment]
> how can i use it ?

cargo build --release --no-default-features --features opengl

**Comment by mlablah** [comment]
This might be related to the new minimum window size shipped with 0.5.4.

From the screenshot it looks like ajour is close to, if not exactly at 600x300 pixels, which is also the new minimum allowed window size.

@nerzhul in the ajour.yml - what does it say your window_size is? There should be a section looking something like this:
```
window_size:
  - 600
  - 300
```

**Comment by tarkah** [comment]
@nerzhul can you report if the opengl version works for resizing? I didn't see anything immediate that stood out in the dependencies, so it's probably something directly in the GUI framework we use as we updated to a new release of it, but I'll have to dig through some of the commits to figure out where this could be happening.

**Comment by lub** [comment]
I have the same problem with sway (a Wayland compositor).

`cargo build --release --no-default-features --features opengl` doesn't fix it for me.

**Comment by tarkah** [comment]
@lub thanks for testing! Since you're running from source, can you try commenting out the following line and seeing if the problem still occurs?

https://github.com/casperstorm/ajour/blob/67884abb8594e461ce6efee7d7c46f2182065bbc/src/gui/mod.rs#L839

**Comment by lub** [comment]
@tarkah that seems to fix it even with `cargo build --release`

**Comment by tarkah** [comment]
Cool, I had a suspicion that was the cause. So weird it prevents any resizing at all when it's only supposed to enforce a minimum. I'll open an issue upstream to hopefully have this resolved.

@casperstorm how do you want to handle this for now?

**Comment by casperstorm** [comment]
I think we should disable `min_size` for Linux until it has been fixed upstream.
I can make a PR for this.

**Comment by tarkah** [comment]
This fix will be available as of 0.6.1-rc.1 which will be available later today
