### ISSUE TITLE
No changelog for addons in 0.5.4

### ISSUE THREAD

**Issue by Neurotoxin001** [casperstorm/ajour#430]
**Describe the bug**
There is no changelog anymore

**To Reproduce**
1. Click on addon version
2. Addon info opens
3. And no changelog

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.5.4

**Comment by casperstorm** [comment]
This has changed recently.
I decided to remove the ability to press the versions, and instead create a button under details of an addon called `Changelog`.

**Comment by Neurotoxin001** [comment]
> I decided to remove the ability to press the versions, and instead create a button under details of an addon called Changelog.

But now it opens the curse website and I can't read changelog right in the Ajour...

**Comment by casperstorm** [comment]
> > I decided to remove the ability to press the versions, and instead create a button under details of an addon called Changelog.
> 
> But now it opens the curse website and I can't read changelog right in the Ajour...

Excatly. For now, you can't read changelogs in Ajour. Here's the reason I choose to change the system:

1. UX/UI wasn't on point. Without the ability to make a tooltip it was hard for users to understand why you **sometimes** could click the version to see changelog.
2. Parsing issues. The format each changelog came in was different, and parsing it wasn't easy. There would always be wrong linebreaks, symbols leftover, and wrong indentations.
3. Addons without changelog felt strange.

I would very much like to have changelogs directly in Ajour, but i'll have to find a solution to all above before i can implement it directly into the app.
