### ISSUE TITLE
Create an app bundle during release for macOS

### ISSUE THREAD

**Issue by athei** [casperstorm/ajour#431]
On macOS it is very uncommon to start UI applications from the command line. In order to avoid this UI friction ajour should be released as an app bundle for macOS.

One could use [cargo-bundle](https://github.com/burtonageo/cargo-bundle) in order to do so.

**Comment by casperstorm** [comment]
Each release already have a bundled macOS application. Notice `ajour.dmg` and `ajour-opengl.dmg` found in the latest release: https://github.com/casperstorm/ajour/releases.

If you want to build it your self, please take a look here: https://github.com/casperstorm/ajour/blob/master/INSTALL.md#macos

**Comment by athei** [comment]
May bad. I downloaded the wrong file then. Thanks.

**Comment by casperstorm** [comment]
> May bad. I downloaded the wrong file then. Thanks.

To elaborate a little, why that file is available.
We use it when you do a self-update. Then Ajour pulls the binary (the file you downloaded) and replaces the binary inside the .app file.
