### ISSUE TITLE
Ajour window title become inactive

### ISSUE THREAD

**Issue by Neurotoxin001** [casperstorm/ajour#441]
**Describe the bug**
Ajour window title become inactive when I click on any addon to open addon info

**To Reproduce**
1. Click on any addon to open addon info
2. Try to click on close button (x) or move Ajour window clicking on window title
3. You can't until you alt-tab to some other window and then go back to Ajour

**Software involved**
Please complete the following information:
 - OS: Windows 10 LTSC 1809
 - Ajour version: 0.6.0

**Comment by mlablah** [comment]
@Neurotoxin001 Thanks for reporting this. We can't reproduce this on our end. Could you please attach a copy of the ajour.log file from this folder %appdata%\ajour on your machine, after reproducing the error (step 1)?

**Comment by Neurotoxin001** [comment]
Idk what is this has been but now I can't reproduce it too…
