### ISSUE TITLE
[weakaura] missing field `username`

### ISSUE THREAD

**Issue by jimnordb** [casperstorm/ajour#442]
**Describe the bug**
Stuck at parsing weakauras

**To Reproduce**
1. Go to "My Weakauras"
2. Click on dropdown on right side
3. Select my username
4. Get stuck

**Expected behavior**
Show weakauras

**Screenshots**
![image](https://user-images.githubusercontent.com/17293360/102757205-41d86c00-4371-11eb-9b37-27c65c9f3cae.png)

**Software involved**
Windows 10 20H2
WoW Classic
Ajour 0.6.0

**Log Output**
```
09:37:58.456 [ajour::gui::update][DEBUG] Message::ParsedAddons(Classic, 63 addons)
09:37:58.794 [ajour_core::catalog][DEBUG] Successfully fetched and parsed https://github.com/casperstorm/ajour-catalog/releases/latest/download/wowi.json
09:37:59.195 [ajour_core::catalog][DEBUG] Successfully fetched and parsed https://github.com/casperstorm/ajour-catalog/releases/latest/download/curse.json
09:37:59.242 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(15671 addons in catalog)
09:38:03.107 [ajour::gui::update][DEBUG] Interaction::ModeSelected(MyWeakAuras(Classic))
09:38:08.333 [ajour::gui::update][DEBUG] Message::WeakAurasAccountSelected(**HIDDEN**)
09:38:08.643 [ajour][ERROR] Failed to parse WeakAuras
09:38:08.643 [ajour][ERROR] caused by: missing field `username` at line 1 column 1868
```

**Comment by casperstorm** [comment]
If anyone else is having this issue, i've attached a build which will fix this issue.

[ajour-username-fix.zip](https://github.com/casperstorm/ajour/files/5723564/ajour-username-fix.zip)
