### ISSUE TITLE
Ajour downloading and catalog opening really slow

### ISSUE THREAD

**Issue by KevinKloiber** [casperstorm/ajour#445]
Overall the download speed of ajour from GitHub is super slow (20 kB/s on average). Also, accessing information from the catalog tab within the window is slow.

**Comment by casperstorm** [comment]
This seems to be related to: https://github.com/casperstorm/ajour/issues/435
Issue seems to be related to your ISP not being happy about downloading files from Github. The Catalog in ajour is hosted on Github: https://github.com/casperstorm/ajour-catalog.

**Comment by KevinKloiber** [comment]
Sounds related, yes. I am also located in Germany, like the author of #435. Guess there is no way to resolve it.

**Comment by casperstorm** [comment]
I'll close it in favor for that then. A few other (german) people on our Discord has mentioned same issue so seems like it's a common thing. I think we should try to brainstorm a few different options in that issue and see what we can do about it.

Reason choose Github initially as hosting was how easy it was to automate everything, and get hosting - all for free.
