### ISSUE TITLE
Ajour app updates fail

### ISSUE THREAD

**Issue by maulyou** [casperstorm/ajour#446]
Every new Ajour version fails to update when attempted.

**Comment by casperstorm** [comment]
With what error? On which operating system? Where is Ajour placed?

**Comment by tarkah** [comment]
@maulyou this is most likely a permissions issue, especially if you saved it to Program Files in Windows. We recommend saving `ajour.exe` to `%APPDATA%\ajour\ajour.exe` and shortcutting to that or placing on the Desktop. You'll have permissions to either location and updating should work perfectly.

**Comment by maulyou** [comment]
Thanks well give it a try
