### ISSUE TITLE
Search in "My Addons" list

### ISSUE THREAD

**Issue by Eliote** [casperstorm/ajour#455]
**Is your feature request related to a problem? Please describe.**
Searching for an Addon to delete can be very annoying when you have many of then installed.

**Describe the solution you'd like**
A simple search box in the list of My Addons would really help with that.

**Comment by Canettieri** [comment]
Yes, please. This feature will help a lot. 👍🏻

Delete an addon is a terrible experience. :(

**Comment by casperstorm** [comment]
> Delete an addon is a terrible experience. :(

I agree.
Finding addons when you have a lot is not ideal. We have brainstormed a few different solutions to not clutter the UI with a search bar.

We haven't agreed on anything yet but we are talking about how to solve this problem!
