### ISSUE TITLE
Log file ignoring --data command line parameter

### ISSUE THREAD

**Issue by tonecool** [casperstorm/ajour#457]
**Describe the bug**
Log file is not created at provided command line data path which affects app portability 

**To Reproduce**
1. Delete if exists "%appdata%\ajour" folder
2. Run ajour with --data parameter (e.g. ajour.exe --data "D:\World of Warcraft\Ajour\data")
3. log file reappears at ""%appdata%\ajour\ajour.log"

**Expected behavior**
Log file should be created inside data folder in this case at "D:\World of Warcraft\Ajour\data\ajour.log"

**Software involved**
Please complete the following information:
 - OS: ["Windows 10"]
 - Ajour version: ["0.6"]

**Comment by tarkah** [comment]
Ahh yeah, I just looked and we setup the logger before we specify the custom data directory, so it uses the default instead. This will be an easy fix.
