### ISSUE TITLE
Add “Venture Plan”

### ISSUE THREAD

**Issue by yungsters** [casperstorm/ajour#459]
[Venture Plan](https://www.townlong-yak.com/addons/venture-plan) is the only addon that I use which must currently be manually installed.

I’ve seen several others on Reddit also ask about how to install this, so I think there would be interest in automated addon management.

**Describe the solution you'd like**
Support installing and upgrading Venture Plan like Ajour currently supports ElvUI as a bespoke one-off.

**Describe alternatives you've considered**
I’ve tried looking, but the addon author does not seem to make the addon available via GitHub.

**Additional context**
Addon Link: https://www.townlong-yak.com/addons/venture-plan

The author seems to also have other addons on the website which are not available on traditional repositories (e.g. CurseForge).

**Comment by casperstorm** [comment]
Currently there's no API or any version control like Github available which makes it impossible for now.
I'll keep an eye out, and try to reach out to the author if I can find his contact information.

**Comment by Mushoz** [comment]
Townlong-Yak now has an API required to track version information to poll for updates, so hopefully this will get implemented now :) Ticket that is tracking this: https://github.com/ajour/ajour/issues/512
