### ISSUE TITLE
Immediately closes when opening

### ISSUE THREAD

**Issue by aerodragon83** [casperstorm/ajour#460]
As the title says. I built a new pc, installed WoW, launched wow (to produce the addons folder), moved ElvUI into said folder, downloaded Ajour to get the rest. Try to open it, immediately closes

**Expected behavior**
Works on my old PC still, get addons

**Software involved**
Please complete the following information:
 - OS: Windows 10 Pro
 - Ajour version: Newest off website and github, both don't open
 - retail, version 9.0.2.36949

**Additional context**

**Log Output**
00:10:06.129 [ajour][INFO] Ajour 0.6.0 has started.
00:10:06.130 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: None,
        flavor: Retail,
    },
    addons: Addons {
        global_release_channel: Stable,
        ignored: {},
        release_channels: {},
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: None,
    scale: None,
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
    hide_ignored_addons: false,
    self_update_channel: Stable,
    weak_auras_account: {},
}
00:10:06.130 [ajour::gui][DEBUG] antialiasing: true
00:10:06.309 [ajour_core::utility][DEBUG] checking for application update
00:10:06.309 [ajour_core::theme][DEBUG] loading user themes
00:10:06.310 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
00:10:06.325 [panic][ERROR] thread 'main' panicked at 'Unable to query surface formats: ERROR_INITIALIZATION_FAILED': C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.6.5\src\window.rs:402
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: BaseThreadInitThunk
  30: RtlUserThreadStart

**Comment by casperstorm** [comment]
See #453.
You should run then OpenGL version of Ajour. You can find it [here](https://www.getajour.com/download).
