### ISSUE TITLE
Add "LetsTimeIt/Dungeon Tools" to the catalog

### ISSUE THREAD

**Issue by CosmicCleric** [casperstorm/ajour#461]
"[LetsTimeIt/Dungeon Tools](https://github.com/LetsTimeIt/DungeonTools)" is a fork of another addon that went paywall (then retreated).

Please add this addon to your catalog, so that it can be downloaded from the Ajour app.

Thanks!

**Comment by casperstorm** [comment]
For now you can install it with `Install from URL` by entering: `https://github.com/LetsTimeIt/DungeonTools`.
Then Ajour will keep it updated.

We have a plan to add a new source later this month with a bunch of addons only available through Github.
