### ISSUE TITLE
ajour.exe CLI

### ISSUE THREAD

**Issue by stevebrinston** [casperstorm/ajour#467]
**Describe the bug**
While using the ajour.exe binary seems to function fine from within the Linux Subsystem for Windows (Ubuntu), there are no return characters at the end of each printed line. It creates a very messy output. I realize this may not be considered normal use but I wanted to automate my addon management and I have WoW installed on Windows and I prefer Linux command line to Windows Command Prompt. 

**To Reproduce**
1. Open Ubuntu bash on a Windows 10 machine.
2. Change directory to where ajour.exe is located (ie, /mnt/c/Blizzard/Ajour) 
3. Run ./ajour.exe --help
4. See messy output

**Expected behavior**
Ideally there would be a return after each line like you see when running ajour CLI from a linux system. 

**Screenshots**
https://d.pr/i/pDXFtg

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.6.1
 - Linux Subsystem for Windows https://www.microsoft.com/store/productId/9NBLGGH4MSV6

**Comment by tarkah** [comment]
Weird, I've not seen this using windows / Poweshell or on Linux. Let me test, I have WSL installed.

**Comment by tarkah** [comment]
I get the same issue as you. I don't think we should be running executables within WSL. You should use command prompt / Powershell where it works as expected. I suspect its the difference in EOL characters used by windows (CR LF)  vs Unix (LF)?

**Comment by tarkah** [comment]
If you really want to use this program within WSL, you need to use the `AppImage` version for linux:

https://github.com/casperstorm/ajour/releases/download/0.6.1/ajour.AppImage

It'll work as expected that way.

**Comment by stevebrinston** [comment]
Fair enough. Thanks for looking into it.
