### ISSUE TITLE
Support for AddOns hosted at Townlong-Yak

### ISSUE THREAD

**Issue by Walkerbo** [casperstorm/ajour#471]
_**Is your feature request related to a problem? Please describe.**_
There are a number of addons that are only available on [Townlong Yack](https://www.townlong-yak.com/addons/latest).
I have the Venture Plan addon that does appear on the MyAddons list.
Townlong Yack addons are not able to be found/installed from the catalogue.

_**Describe the solution you'd like**_
If possible can the addons that are only available from Townlong Yack be found/installed/updated through the Ajour app.

**Describe alternatives you've considered**
Currently, the only way to find/install/update the Townlong Yack addons is manually.

**Comment by tarkah** [comment]
I don't see us supporting small / personal addon repositories as this can get bloated very fast. I doubt there is even an API available for us to work with this personal "repo".

Since we support installing addons via github, I'd recommend reaching out to the developer(s) and seeing if they can also host / create releases there, which would universally support many different addon managers, including Ajour.

**Comment by Mushoz** [comment]
There is a FAQ in the Discord server hosted by the author, which states:

```
A brief FAQ regarding addon distribution:

Hey, can you upload this to CurseForge?
No, I can't access my CF account at the moment (won't consent to transfer of account information to Overwolf without knowing what that account information is). On a related note, CF's decision to continue distributing old addon versions, strip author attribution, and display a misleading "this project is abandoned" notice isn't helping things.

WoWInterface? GitHub? GitLab? Uncle Bob's Repository Site?
I have considered these options and decided that, for varying reasons, they don't adequately address what I want from a distribution channel.

But then how can I update addons with $Application ?
I am aware that this is desirable, and do plan to provide a more automation-friendly way to check for updates in the future.
In the meantime, you could bookmark the relevant addon pages (and check them periodically/if something breaks -- it's not like things are updated daily), or perhaps set up notifications for the #release-announcements channel.

Can't people just re-host $AddOn elsewhere?
There is obviously no law of physics that would prevent this from happening. It would, however, be copyright infringement, which is probably against the rules of every respectable hosting platform. Please don't -- it would make me sad, and sad me doesn't write any addon code.
```

I don't understand what those "varying reasons" are that are mentioned. However, I do know that VenturePlan is currently the most popular/used addon for mission table management in Shadowlands, so having this supported would be very welcome. On the other hand, without a working API and the fact you'd have to support small-scale addon repositories this could become messy very quickly.

Maybe it would be best to contact the developer directly. I saw in the other ticket (https://github.com/casperstorm/ajour/issues/459) that you wanted to reach out to the author. He can be contacted via his Discord server. An invite link to said server is linked here: https://www.townlong-yak.com/addons/venture-plan/tracker

**Comment by Mushoz** [comment]
Townlong-Yak now has an API required to track version information to poll for updates, so hopefully this will get implemented now :) Ticket that is tracking this: https://github.com/ajour/ajour/issues/512
