### ISSUE TITLE
Addon Fishing Buddy on CurseForge: No Updates found

### ISSUE THREAD

**Issue by FH3095** [casperstorm/ajour#483]
**Describe the bug**
For the addon [Fishing Buddy](https://www.curseforge.com/wow/addons/fishingbuddy) the curseforge release versions are detected as alpha versions.

**To Reproduce**
1. Search Fishing Buddy in Catalog and install addon
2. Switch to "My Addons" and hit refresh. FishingBuddy has now no remote versions and ajour wont detect updates.
3. Change release channel for FishingBuddy from Default to Alpha. Remote version is now displayed and updates will be detected.

**Expected behavior**
For FishingBuddy versions marked on curseforge as release should be treated as stable versions.

**Screenshots**
![FishingBuddyInCatalog](https://user-images.githubusercontent.com/29451/104126256-decc6a80-535b-11eb-9f3e-72ff01c166a8.png)
![FishingBuddyAfterRestart](https://user-images.githubusercontent.com/29451/104126262-e855d280-535b-11eb-95cb-9e436bd38985.png)
![FishingBuddyAsAlpha](https://user-images.githubusercontent.com/29451/104126279-058aa100-535c-11eb-80e3-02069665e3bd.png)

**Software involved**
Please complete the following information:
 - OS: Windows 7
 - Ajour version: 0.6.1
 - FishingBuddy retail

**Comment by mlablah** [comment]
Initial investigation: 
CurseForge fingerprint API returns an exact match for this fingerprint. The match is labeled with releaseType 1.
Wowup fingerprint api also returns an exact match, but this is labelled releaseType 3.
This explains why Ajour finds no remote version when release channel is Stable (1) but does not explain why the API responses are not aligned.

Attaching both responses.
[wowup.json.txt](https://github.com/casperstorm/ajour/files/5793451/wowup.json.txt)
[CF.json.txt](https://github.com/casperstorm/ajour/files/5793452/CF.json.txt)

**Comment by tarkah** [comment]
Yeah, for some reason the WowUp.Hub api is tagging both the stable AND beta releases as releaseType 3, which is for Alpha. The stable release should be tagged as 1.

I'll ping the dev over there to see if he can investigate why this is happening

**Comment by tarkah** [comment]
He fixed it on their backend, it now shows the release under Stable. He will monitor to make sure it doesn't revert.
