### ISSUE TITLE
Manually-installed Addons

### ISSUE THREAD

**Issue by coogie** [casperstorm/ajour#485]
**Is your feature request related to a problem? Please describe.**
Ajour doesn't support smaller addon repos to avoid adding unnecessary bloat (https://github.com/casperstorm/ajour/issues/471#issuecomment-754917886) instead supporting addon installation through Github/Gitlab releases. However, [not all addon developers distribute their addons via GH/GL](https://i.imgur.com/1HnaQeF.png), or may not be willing to add the additional steps required for it.

This still leaves an opportunity to add _some_ support for these addons in a way to reduce user friction when installing.

**Describe the solution you'd like**
A view within Ajour to manually install addons via their ZIP files.
I know that manually adding a WoW addon _isn't complex_, but it would be nice to be able to do so quickly and easily via the Ajour interface rather than unzip the addon myself and navigate to the necessary Interface folder.

**Additional context**
Potential mockup:
![ajour-manual](https://user-images.githubusercontent.com/1271105/104165378-2f41d780-53f1-11eb-8dca-9a629ca71873.png)

**Comment by casperstorm** [comment]
Thank you for taking the time reporting such a detailed missing feature, even with a mockup.
However, I do not see the need for it at this point. You hit the head of the nail right here:

> I know that manually adding a WoW addon isn't complex, but it would be nice to be able to do so quickly and easily via the Ajour interface rather than unzip the addon myself and navigate to the necessary Interface folder.

I would rather encourage addon developers to use one of the supported sources, or GitHub/Gitlab. And if they still reject it is still possible to do it manually, as you said, but Ajour will still catch it, just as Unknown.

So again; thank you so much for taking the time but unfortunately this is not in scope of Ajour right now.
