### ISSUE TITLE
Add additional info to Addon Details view

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#49]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to see more details regarding an addon in the "Details" view. Currently, only a short description is displayed.

**Describe the solution you'd like**
Suggestions:
- [x] Author
- [x] Link to addon website
- [ ] A fuller description than the one currently displayed (but truncated with link to full text (same as above) if too long)
- [ ] Release date of latest available release
- [ ] Changelog for latest available release

**Comment by casperstorm** [comment]
I am gonna continue working on this issue.
I would like to update the design a little as well, and clear up the detail view a little. It's very cluttered and orientated to the left even though we have plenty of space to the right. This can we do better.

**Comment by ChrisNolan** [comment]
Small thing, but I'd like it so when I click anywhere in the column the details view shows up, not just on the text in the column.
