### ISSUE TITLE
After latest update can't open it on windows

### ISSUE THREAD

**Issue by d3m4** [casperstorm/ajour#492]
**Describe the bug**
Can not open the app, the program starts and when it says it's parsing it crashes... The app was doing fine before the update =D Really like the app, this is my first bug report on github =X

**To Reproduce**
1. Click to open the app
2. It will show the parsing window
3. It force closes

**Expected behavior**
It to open and for us to go crazy downloading add-ons

**Screenshots**
It's closed so no

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.6.2

**Additional context**
Nothing here really, just updated, restarted pc for another reason went to open it and bam.

**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.

11:43:34.320 [ajour][INFO] Ajour 0.6.2 has started.
11:43:34.321 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "C:\\Program Files (x86)\\World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        global_release_channel: Stable,
        ignored: {
            Retail: [],
        },
        release_channels: {
            Retail: {
                "DBM-DefaultSkin": Alpha,
                "WeakAurasArchive": Alpha,
            },
        },
        delete_saved_variables: false,
    },
    theme: Some(
        "Forest Night",
    ),
    column_config: V3 {
        my_addons_columns: [
            ColumnConfigV2 {
                key: "title",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "local",
                width: Some(
                    198,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "remote",
                width: Some(
                    199,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "status",
                width: Some(
                    123,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "channel",
                width: Some(
                    85,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "author",
                width: Some(
                    85,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    110,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "date_released",
                width: Some(
                    110,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    110,
                ),
                hidden: true,
            },
        ],
        catalog_columns: [
            ColumnConfigV2 {
                key: "addon",
                width: Some(
                    394,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "description",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "num_downloads",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "date_released",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "install",
                width: Some(
                    85,
                ),
                hidden: false,
            },
        ],
        aura_columns: [],
    },
    window_size: Some(
        (
            1430,
            905,
        ),
    ),
    scale: None,
    backup_directory: Some(
        "C:\\Users\\felip\\OneDrive\\WowAddonBackup",
    ),
    backup_addons: true,
    backup_wtf: true,
    hide_ignored_addons: false,
    self_update_channel: Stable,
    weak_auras_account: {
        Retail: "57549087#2",
    },
    alternating_row_colors: true,
    language: English,
}
11:43:34.321 [ajour::gui][DEBUG] antialiasing: true
11:43:34.600 [ajour_core::utility][DEBUG] checking for application update
11:43:34.600 [ajour_core::theme][DEBUG] loading user themes
11:43:34.606 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
11:43:34.678 [ajour::gui::update][DEBUG] Message::CachesLoaded(error: false)
11:43:34.678 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
11:43:34.681 [ajour::gui::update][DEBUG] Message::Parse
11:43:34.681 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\Interface/AddOns"
11:43:34.682 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_ptr_\\Interface/AddOns"
11:43:34.682 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_beta_\\Interface/AddOns"
11:43:34.682 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_classic_\\Interface/AddOns"
11:43:34.682 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
11:43:34.682 [ajour_core::parse][DEBUG] Retail Beta - parsing addons folder
11:43:34.682 [ajour_core::parse][DEBUG] Retail - parsing addons folder
11:43:34.682 [ajour_core::parse][DEBUG] Retail PTR - parsing addons folder
11:43:34.682 [ajour_core::parse][DEBUG] Classic - parsing addons folder
11:43:34.682 [ajour_core::parse][DEBUG] Classic PTR - parsing addons folder
11:43:34.683 [ajour_core::parse][DEBUG] Retail - 89 folders in AddOns directory to parse
11:43:34.687 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail, is_installed: true)
11:43:34.687 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail Beta, is_installed: false)
11:43:34.687 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail PTR, is_installed: false)
11:43:34.687 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Classic, is_installed: false)
11:43:34.688 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Classic PTR, is_installed: false)
11:43:34.688 [ajour::gui::update][DEBUG] Message::LatestBackup(Some(2020-12-05T23:05:42))
11:43:34.696 [ajour][ERROR] Failed to parse addons
11:43:34.696 [ajour][ERROR] caused by: Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_beta_\\Interface/AddOns"
11:43:34.696 [ajour::gui::update][DEBUG] Message::ListWeakAurasAccounts(Retail, num_accounts: 1)
11:43:34.697 [ajour][ERROR] Failed to parse addons
11:43:34.697 [ajour][ERROR] caused by: Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_ptr_\\Interface/AddOns"
11:43:34.700 [ajour][ERROR] Failed to parse addons
11:43:34.700 [ajour][ERROR] caused by: Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_classic_\\Interface/AddOns"
11:43:34.703 [ajour_core::parse][DEBUG] Retail - 89 fingerprints: 89 cached, 0 calculated, 0 added, 0 removed
11:43:34.706 [ajour][ERROR] Failed to parse addons
11:43:34.706 [ajour][ERROR] caused by: Addon directory not found: "C:\\Program Files (x86)\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
11:43:34.711 [ajour_core::parse][DEBUG] Retail - 89 addon folders successfully parsed from '.toc'
11:43:34.711 [ajour_core::parse][DEBUG] Retail - 1 valid cache entries retrieved
11:43:34.711 [ajour_core::parse][DEBUG] Retail - 87 unique fingerprints to check against curse api
11:43:35.399 [ajour::gui::update][DEBUG] Message::LatestRelease(Some("0.6.3"))
11:43:35.407 [panic][ERROR] thread 'main' panicked at 'no localization found': src\localization.rs:33
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: DefSubclassProc
  22: DefSubclassProc
  23: CallWindowProcW
  24: DispatchMessageW
  25: SendMessageTimeoutW
  26: KiUserCallbackDispatcher
  27: NtUserDispatchMessage
  28: DispatchMessageW
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: BaseThreadInitThunk
  40: RtlUserThreadStart

**Comment by casperstorm** [comment]
I made a mistake in 0.6.2 RC1 which means everyone on that version is pretty much deadlocked. Sucks, and 100% my faults.
You need to download the newest (0.6.3) manually and everything should work: https://www.getajour.com/download.

SORRY!

**Comment by d3m4** [comment]
it worked out great, love the app.

cheers

**Comment by mrkhaglund** [comment]
> I made a mistake in 0.6.2 RC1 which means everyone on that version is pretty much deadlocked. Sucks, and 100% my faults.
> You need to download the newest (0.6.3) manually and everything should work: https://www.getajour.com/download.
> 
> SORRY!

As soon its downloaded to my pc, windows blocking it and tells me its not safe. No way for me to work around it 👎

**Comment by casperstorm** [comment]
> > I made a mistake in 0.6.2 RC1 which means everyone on that version is pretty much deadlocked. Sucks, and 100% my faults.
> 
> > You need to download the newest (0.6.3) manually and everything should work: https://www.getajour.com/download.
> 
> > 
> 
> > SORRY!
> 
> 
> 
> As soon its downloaded to my pc, windows blocking it and tells me its not safe. No way for me to work around it 👎 

That's because it's compiled without a trusted certificate. You can ignore it, however we are working on a certificate.
