### ISSUE TITLE
Linux: selected directory ending with \n

### ISSUE THREAD

**Issue by WeaponMan** [casperstorm/ajour#51]
When I select dir from button "Select directory" the selected path end with newline and the addons directory cannot be found.
Had to do ugly workaround to get it working:
```rust
async fn open_directory() -> Option<PathBuf> {
    // Should we use task::spawn_blocking here?
    // TODO: We should maybe make sure we can't spawn multiple windows here.
    let dialog = OpenSingleDir { dir: None };
    dialog.show().unwrap().and_then(|f| Some(PathBuf::from(&f.as_path().display().to_string().replace("\n", ""))))
}
```

**Comment by casperstorm** [comment]
Thanks for reporting this @WeaponMan,
I'll look into this tonight and see if I can clean this up a bit.

**Comment by casperstorm** [comment]
Cross-posted this issue to https://github.com/balthild/native-dialog-rs/issues/8, which is the maintainer of the crate we are using for filedialog.

**Comment by WeaponMan** [comment]
I saw, btw its zenity backend
