### ISSUE TITLE
Delete AddOn

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#6]
As a User, I want to be able to delete an installed addon.

Clicking the Delete AddOn button should remove the addon, and all the addons that is related to it via dependencies, leaving the SavedVariables intact.

Updating an addon will also trigger this action.

Pseudo code:
* Refresh data structure by executing `Parse Interface folder` (to make sure we have the latest changes).
* From data structure, determine addons with dependencies to the addon being deleted.
* Delete dependent addons and the addon the user wanted to delete.
* Refresh data structure by executing `Parse Interface folder` again (to make sure changes are propagated).

**Comment by casperstorm** [comment]
Closed by this commit https://github.com/casperstorm/ajour/commit/2d7633b1b46e1e5b7ce2b4f48ec87d8cf7f39ea1
