### ISSUE TITLE
Support light theme

### ISSUE THREAD

**Issue by casperstorm** [casperstorm/ajour#65]
This is a low priority task, but it would be easy to extend the curent `ColorPalette ` to support a light theme:

https://github.com/casperstorm/ajour/blob/d765c4675797c09bbac5af7e70c51b78f7edd991/src/gui/style.rs#L12-L23

An example of light theme colors could be: https://coolors.co/6100ee-00dac6-000000-f5f5f5-af0120-ffffff:

```rust
ColorPalette::Primary => Color::from_rgb(0.39, 0.0, 0.93),
ColorPalette::Secondary => Color::from_rgb(0.0, 0.85, 0.77),
ColorPalette::Surface => Color::from_rgb(0.96, 0.96, 0.96),
ColorPalette::OnSurface => Color::from_rgb(0.0, 0.0, 0.0),
ColorPalette::Background => Color::from_rgb(1.0, 1.0, 1.0),
ColorPalette::Error => Color::from_rgb(0.68, 0.0, 0.12),
```
Essentially the value should be saved to the `Config` and changeable though Settings. 

<img width="951" alt="Screenshot 2020-08-31 at 21 50 33" src="https://user-images.githubusercontent.com/2248455/91760664-06543f00-ebd4-11ea-8d8f-fd3dc5f72164.png">

**Comment by casperstorm** [comment]
@tarkah Depending on your mood, time etc – this could maybe be a fun for you if you were up for it. It's not really a feature which is needed but i've always thought it would be quite elegant with a theme enum in config and then the UI would reflect that.

Another thing you could help me out with is a general "optimization walkthrough" of the codebase. That would be AWESOME because I think theres quite a few places which could written in a more idiomatic Rust way. Or if theres something third you would do, just do it really. It's a big help having you onboard.

**Comment by tarkah** [comment]
Yeah, this is such an easy feature to ship and adds a lot of value to end users. I'd say you ship the application with a default theme file that includes the dark and light themes, but allows the user to add their own. That files gets de-serialized on startup and even monitored for hot reloading when changed. We can expose the themes through a drop down selection in settings and save the chosen theme name to the config file.

Maybe the default dark and light themes aren't shipped in that file and are static instead, just in case we ever have to modify `ColorPalette` in the future to guarantee they'll always work. And we can notify the user if the themes file doesn't deser properly, linking them to a wiki entry with the current theme file structure. If this is preferred, maybe its better to have a theme folder and each theme can be a different `.theme` file or something? So it's very easy to share themes and just paste them in a folder, with the name of the file being the theme name?

**Comment by casperstorm** [comment]
That sounds awesome, because then people could share themes in the future. That's of cause a feature you easily can live without but again – it just awesome to support something like that.

You can have the ball on this one, because then i'll try to keep focus on cleaning up, optimizing and have a as polished app as possible before launch. Of cause, theres no strings attached if you don't feel like it or don't have time :-)

**Comment by tarkah** [comment]
Sounds good! Go ahead and assign it to me if you'd like. I'll work on this over the next week.
