### ISSUE TITLE
App doesn't show any addon in the list

### ISSUE THREAD

**Issue by casualshammy** [casperstorm/ajour#66]
Hello.
I don't sure if this app is ready-to-use, but I can't get it working :( 
After setting path to WoW folder nothing appears in the list of addons.

Steps (on Windows 10):
1. Download latest release.
2. Launch app (even as administator), set path to WoW dir.
3. I have many addons installed, but list in the app is empty.

Maybe this app writes a log somewhere?

**Comment by casperstorm** [comment]
Hi @casualshammy,
I am sorry you had a bad first experience. This proves there is still work to be done.

- Did you select the root of the World of Warcraft folder?

In my case on Windows that would be `C:\Program Files (x86)\World of Warcraft`.
Ajour then looks at `[path-you-choose]/_retail_/Interface/AddOns` (or `_classic_` if you choose that).

Can you provide the path you provided to Ajour and also how the structure of that folder looks like?

**Comment by casualshammy** [comment]
My full path to addons folder is `D:\games\World of Warcraft\_retail_\Interface\AddOns`
I'm getting error message ("Addon folder is not found") if I select any folder except `D:\games\World of Warcraft`

![Ajour setting](https://user-images.githubusercontent.com/4965168/91967860-b7112a00-ed0b-11ea-8ec4-8effbab54e79.jpg)
![Addons folder content](https://user-images.githubusercontent.com/4965168/91968545-b4630480-ed0c-11ea-921a-5a58e923f2c7.jpg)

**Comment by casperstorm** [comment]
> My full path to addons folder is `D:\games\World of Warcraft\_retail_\Interface\AddOns`
> I'm getting error message ("Addon folder is not found") if I select any folder except `D:\games\World of Warcraft`

I havn't seen this issue before. This is very strange. Maybe it has something to do with your localization?
If you have the time, and want to help out could you then test the following for me:

* Rename your AddOns -> AddOns_org.
* Create a new folder AddOns folder.
* Copy `BGDefender` from AddOns_org to AddOns.

Refresh Ajour, or restart it. Do you see this then?

<img width="768" alt="Screenshot 2020-09-02 at 12 42 03" src="https://user-images.githubusercontent.com/2248455/91971579-b8495380-ed19-11ea-900d-8287be9ab20a.png">

**Comment by casualshammy** [comment]
Yes, I see this addon. I guess next step is to delete addons one by one? :)

**Comment by casperstorm** [comment]
> Yes, I see this addon. I guess next step is to delete addons one by one? :)

Haha, that is too much to ask for you!
A big help would be if you could zip your AddOn folder and upload it to somewere (WeTransfer or similar). Then i'll go through all the addons and figure out which one causes that behaviour.

**Comment by casualshammy** [comment]
It wasn't so hard. This addon causes issue (it is quite old, I don't use it and I can remove it, but maybe you'll find it useful):
[ChatBar.zip](https://github.com/casperstorm/ajour/files/5161818/ChatBar.zip)

**Comment by casperstorm** [comment]
> It wasn't so difficult. This addon causes issue (it is quite old, I don't use it and I can remove it, but maybe you'll find this information useful):
> [ChatBar.zip](https://github.com/casperstorm/ajour/files/5161818/ChatBar.zip)

It's a UTF-8 encoding issue. I'll push a fix soon.
Thank you so much for all the help, and for taking the time report this issue.

**Comment by casualshammy** [comment]
Ah, encoding... It' is a pain in the ass sometimes :)
Thank you for your work!
