### ISSUE TITLE
Rendering artifacts in Local version text

### ISSUE THREAD

**Issue by tarkah** [casperstorm/ajour#68]
I'm getting rendering artifacts in the Local version text. 

![image](https://user-images.githubusercontent.com/10239377/92009575-94781480-ecfd-11ea-8f20-f415db051557.png)

**Comment by tarkah** [comment]
This commit is causing it https://github.com/casperstorm/ajour/commit/1a253803639973dc18f4ada22bb4e45003426ef7

**Comment by casperstorm** [comment]
Ah, i know the cause of this. I'll fix this. Good catch.

**Comment by tarkah** [comment]
Looks like it caused by since the version of my addon has additional data in it

```diff
diff --git a/src/gui/element.rs b/src/gui/element.rs
index e791d78..6ccc383 100644
--- a/src/gui/element.rs
+++ b/src/gui/element.rs
@@ -164,7 +164,7 @@ pub fn settings_container<'a>(
 }

 pub fn addon_data_cell(addon: &'_ mut Addon, is_addon_expanded: bool) -> Container<'_, Message> {
-    let default_height = Length::Units(26);
+    let default_height = Length::Units(28);
```

**Comment by tarkah** [comment]
If I expand it to 35 units...

![image](https://user-images.githubusercontent.com/10239377/92010566-cc338c00-ecfe-11ea-8a3c-eaba8e41a49c.png)

**Comment by casperstorm** [comment]
I've fixed this with a temporary fix. If we increase the cell height it breaks (again) but I'll need more time to come up with a proper solution because in my opinion it is something `iced` should be able to handle.

When I have a proper solution I'll open a PR.

**Comment by tarkah** [comment]
Sounds good, thanks for getting this fixed. Yeah, until he gives us a way to disable text wrapping, we're out of luck here on taller rows.
