### ISSUE TITLE
Delete Config (SavedVariables)

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#7]
**Is your feature request related to a problem? Please describe.**
As a User, I want to be able to delete the config (SavedVariables) of an installed addon.

**Describe the solution you'd like**
Clicking the Delete Config button should remove all the SavedVariables associated with the addon, and all the addons that is related to it via dependencies, but leaving the addons themselves intact.

Pseudo code:
* User clicks the Delete Config button.
* Determine addons with dependencies to the addon for which config is being deleted.
* (Optionally) Present the user with list of dependent addons and allow the user to cancel the delete config operation.
* Delete SavedVariables of all dependent addons across Account, Realm and Character folders.

**Comment by gixxpunk** [comment]
I use this one for a long time. Maybe you can get some inspiration from it:

`@echo off
pushd "C:\Games\World of Warcraft\_beta_\WTF\Account"

del /s *.bak
del /s *.old

for /d %%i in (*) do (
	if exist %%i\SavedVariables\ (
		echo Account: %%i

		for %%j in ("%%i\SavedVariables\*.lua") do (
			echo %%~nj | findstr /r /i "^Blizzard_" > nul
			if errorlevel 1 (
				echo GlobalSV: %%~nj
				if not exist ..\..\Interface\AddOns\%%~nj\ (
					echo Delete: %%~nj
					del "%%j"
				)
			)
		)

		for /d %%j in ("%%i\*") do (
			for /d %%k in ("%%j\*") do (
				echo Character: %%k
				for %%l in ("%%k\SavedVariables\*.lua") do (
					echo %%~nl | findstr /r /i "^Blizzard_" > nul
					if errorlevel 1 (
						echo CharSV: %%~nl
						if not exist ..\..\Interface\AddOns\%%~nl\ (
							echo Delete: %%~nl
							del "%%l"
						)
					)
				)
			)
		)
	)
)

popd
pause`

**Comment by gixxpunk** [comment]
> @echo off
pushd "C:\Games\World of Warcraft\_beta_\WTF\Account"

del /s *.bak
del /s *.old

for /d %%i in (*) do (
	if exist %%i\SavedVariables\ (
		echo Account: %%i

		for %%j in ("%%i\SavedVariables\*.lua") do (
			echo %%~nj | findstr /r /i "^Blizzard_" > nul
			if errorlevel 1 (
				echo GlobalSV: %%~nj
				if not exist ..\..\Interface\AddOns\%%~nj\ (
					echo Delete: %%~nj
					del "%%j"
				)
			)
		)

		for /d %%j in ("%%i\*") do (
			for /d %%k in ("%%j\*") do (
				echo Character: %%k
				for %%l in ("%%k\SavedVariables\*.lua") do (
					echo %%~nl | findstr /r /i "^Blizzard_" > nul
					if errorlevel 1 (
						echo CharSV: %%~nl
						if not exist ..\..\Interface\AddOns\%%~nl\ (
							echo Delete: %%~nl
							del "%%l"
						)
					)
				)
			)
		)
	)
)

popd
pause

**Comment by casperstorm** [comment]
Thank you so much @gixxpunk – this could be very useful.
