### ISSUE TITLE
Add feature to install addons instead of only being able to update them.

### ISSUE THREAD

**Issue by kiraleos** [casperstorm/ajour#77]

**Comment by casperstorm** [comment]
Hi @kiraleos - Thanks for the suggestion.

It is a well discussed feature and at some point we will add it. Focus, however, is to do few things, but do them well.
Reason is that I don't want to add features left and right without ensuring stability and performance.

Once I am happy with the current feature set, I will add more features and this is on top of that list.
I'll leave this open for now, and create a ROADMAP/TODO file so we can reference to that in the future.

**Comment by casperstorm** [comment]
You can follow the roadmap here now: https://github.com/casperstorm/ajour/projects/2
