### ISSUE TITLE
Trim leading and trailing spaces in addon info

### ISSUE THREAD

**Issue by casualshammy** [casperstorm/ajour#79]
**Describe the bug**
![_DevPad](https://user-images.githubusercontent.com/4965168/92387310-31c3b600-f10d-11ea-8d31-7e7d09614c65.png)
DevPad is not a popular addon, but just in case.

**To Reproduce**
Install an addon with some thing like `## Title:・・・・・・・_|cffCCCC88DevPad|r` in `.toc` file, where `・` is space.

**Expected behavior**
Addon name to be shown without spaces.

**Desktop (please complete the following information):**
Windows 10
Ajour 0.2.5

**Comment by casperstorm** [comment]
Thank you (again) for reporting these issues, @casualshammy.
I'll take a look at fixing my regex to handle this later today.
