### ISSUE TITLE
Addon BtWLoadouts doesn't show remote version

### ISSUE THREAD

**Issue by the-isz** [casperstorm/ajour#82]
**Describe the bug**
The addon BtWLoadouts including its local version is detected by ajour, but the remote version only shows as "-".

**To Reproduce**
1. Download BtWLoadouts from here: https://www.curseforge.com/wow/addons/btwloadouts
2. Unpack into WoW Interface folder
3. Open ajour
4. Observe remote version shown as "-"

**Expected behavior**
Remote version should be shown (currently: v78)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.2.5

**Additional context**
There's a comment on the addon's curseforge page saying that the Twitch client always shows an available update. This might be related.

**Unrelated**
Brilliant software! I love how fast, small and simple it is :) Thank you!

**Comment by casperstorm** [comment]
Thanks for reporting this, @the-isz and thanks for the kinds words.
This issue will be fixed with #78 where I can do a better search for addons.
Eta is end of this week, it's a little big refactor but hoping to have it ready soon.

**Comment by mlablah** [comment]
I had a look at the addon on curseforge, and it appears that the author hasn't published any version with type "Release". All the ones listed under https://www.curseforge.com/wow/addons/btwloadouts/files are of type "Beta". Currently Ajour only looks for the latest "Release" build.

By itself #78 won't fix it, but we could consider making ajour look for newer beta (in addition to regular) releases, if the local version is itself a beta release.

**Comment by casperstorm** [comment]
@the-isz I've released a new version of Ajour which will show this addon. :-)

**Comment by the-isz** [comment]
Works perfectly, thank you! :)
