### ISSUE TITLE
Addons with unknown fingerprints not shown in UI

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#90]
**Describe the bug**
Addons that do not match fingerprints known to the curse api are no longer shown in the UI.

**To Reproduce**
1. Pick an addon that is currently shown in the UI (and then close ajour)
2. Edit the addons .toc file with some non-whitespace character. I chose to change the version to some lower number.
3. Delete the fingerprints.yml file to force a fingerprint recalculation on next launch.
4. Open Ajour again and see that the addon is no longer in the list.

Alternatively, use an addon that is not hosted on curseforge in the first place.

**Expected behavior**
Ajour displays all my local addons and uses alternative (legacy/offline) logic to identify local version in case the fingerprint endpoint does not return any matches.

**Screenshots**
![01-pre_modification](https://user-images.githubusercontent.com/68285419/92917182-8aa58e00-f42e-11ea-9324-b0a2563d5c70.png)
![02-modification](https://user-images.githubusercontent.com/68285419/92917192-8d07e800-f42e-11ea-9b6a-ff6142d8ec04.PNG)
![03-post_modification](https://user-images.githubusercontent.com/68285419/92917199-8e391500-f42e-11ea-940b-ab3ac42cf06e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.3.1

**Additional context**
With the release of 0.3.0 (and 0.3.1) the overall level of support for addons has increased enormously which is great! This issue is only to address that the "fallback" scenario isn't working.

**Comment by tarkah** [comment]
I noticed this as well yesterday when resolving #88.

Currently 2 API requests occur to Curse. The first is querying all fingerprints. The second queries addons with a curse id. However, instead of querying ALL non-tukui addons with curse ids, it's only querying the exact match fingerprint addons.

This should be an easy fix since we are already requesting additional package data based on curse id, we just need to layer in these addons that are falling through the gaps.

**Comment by tarkah** [comment]
@mlablah I noticed in your `.toc` screenshot this addon doesn't have `X-Curse-Project-ID` specified. This is what would be used as a fallback against the curse API if fingerprinting doesn't match (once we get that fallback working).

Are you still expecting to see the addon in Ajour if there is no tukui ID or curse ID / fingerprint for the addon?

**Comment by tarkah** [comment]
#91 partially addresses this issue in that it will now show addons that failed fingerprinting, but have a valid Curse ID that can be looked up.

I tested this by manually changing the version on an addon, which threw off it's fingerprint and deleted `fingerprints.yml` to capture this change. Previously, this addon would not show up. Now, it does show up and shows an update is available.

![notepad++_vfweaba6OE](https://user-images.githubusercontent.com/10239377/92950878-4dcb9e00-f412-11ea-896b-615eb020616a.png)
![ajour_gIwTX3ZXMd](https://user-images.githubusercontent.com/10239377/92950879-4e643480-f412-11ea-951b-1202712e9dce.png)

**Comment by mlablah** [comment]
> @mlablah I noticed in your `.toc` screenshot this addon doesn't have `X-Curse-Project-ID` specified. This is what would be used as a fallback against the curse API if fingerprinting doesn't match (once we get that fallback working).
> Are you still expecting to see the addon in Ajour if there is no tukui ID or curse ID / fingerprint for the addon?

I think in that scenario it should still be displayed (except in cases where it's determined to be a dependency of another addon). 

And the remote version can be looked up like it was in 0.2.x as well, using the title of the addon.

But if you guys think it's a bad idea to use as a final fallback measure, that's fine by me as well. :)

**Comment by tarkah** [comment]
@mlablah Just a heads up that we reverted my changes from #91 due to it potentially exposing dependency folders as Addons through the GUI. I've got some ideas on how to more gracefully handle the fallback strategies, but it's not going to make it into `0.3.4`. I'll link any future PRs here to track against this issue.

**Comment by casperstorm** [comment]
For now this has been added to the [Roadmap](https://github.com/casperstorm/ajour/projects/2#card-46592147).
Let's revisit this issue when we start working on it.
