### ISSUE TITLE
Read addon changelogs before updating

### ISSUE THREAD

**Issue by mchris2** [casperstorm/ajour#93]
**Is your feature request related to a problem? Please describe.**
I really prefer to read the changelog of every addon before I update it so I know what is actually changing.

**Describe the solution you'd like**
I can think of a few different ways this could be done. I'll list them in my preferred order, but happy for your expertise
1. If an update is available, when you click on the Remote version number the changelog will display in the expanded window
2. When you click on the addon name or remote version number the changelog will also show up underneath the summary
3. When you click on the addon name a Changelog button next to the other buttons (Force update/Ignore/Delete) that when clicked will bring a popup or expand further to show the changelog.
4. When you click on the addon name a Changelog button next to the other buttons (Force update/Ignore/Delete) that when clicked will load the changelog/addon website in your selected browser

**Describe alternatives you've considered**
N/A

**Comment by casperstorm** [comment]
This is a suggestion, @mchris2.
[Issue #49](https://github.com/casperstorm/ajour/issues/49) releates to this, and we are planning to add the changelog when provided. I have been struggling with the ux of this, so thanks for your four solutions i'll try to play a play around a little and see what works best. This should be done soon as I am currently working on that said issue.

**Comment by mlablah** [comment]
Adding the discussion we had elsewhere here:
We could make the text in the "Remote" column work as a button that opens a special changelog view beneath the addon in the list. Similar to how the other details are opened by clicking the name in the "Addon" column.
This changelog view would then be populated by whatever changelog information is returned by the curse api, however we need to figure out how we want to handle any html if present.

**Comment by mjsmagalhaes** [comment]
If makes it easier to handle the html it could just pop up a box with the changelog
