### ISSUE TITLE
Improve clarity of row titles to reflect current sort state

### ISSUE THREAD

**Issue by nicholasthie** [casperstorm/ajour#94]
**Is your feature request related to a problem? Please describe.**
I would like to see what the list is currently sorted by and in what order. Currently, you need to look at the list itself and make a guess on how it is sorted.

**Describe the solution you'd like**
* Highlight which column is currently sorting the list
* Give an indicator of the sort order (ascending/descending)

**Comment by casperstorm** [comment]
Thanks for the suggestion @nicholasthie.
I agree with you: UX wise this is needed, and would be a great addition.
