### ISSUE TITLE
Make AddOns folder search case-insensitive

### ISSUE THREAD

**Issue by J4nsen** [casperstorm/ajour#96]
**Is your feature request related to a problem? Please describe.**
I'm on Linux. Addon folder was named "Addons" instead of "AddOns", hence Ajour could not find the directory. 

**Describe the solution you'd like**
Make folder-search case-insensitive.

**Describe alternatives you've considered**
Fixed by renaming Addons to AddOns.

**Additional context**
I don't know why my Addon folder was named this way. Probably because I renamed it. I suppose this bug won't happen on Windows.

**Comment by tarkah** [comment]
I got this working through #98 . I've tested with a bunch of combinations including `InTeRFAcE/aDdONs`
