### ISSUE TITLE
Make UI Remember window size and position

### ISSUE THREAD

**Issue by Ruffz** [casperstorm/ajour#99]
_**Is your feature request related to a problem? Please describe.**_
UI size reset at startup and the window appear randomly anywhere.

_**Describe the solution you'd like**_
Make UI Remember window size and position.

**Comment by casperstorm** [comment]
Right now the window size is hardcoded to a specific value at each startup:
https://github.com/casperstorm/ajour/blob/2718634bedb75a322dc8f70be3079abdd73c9aa3/src/gui/mod.rs#L291

We should be able to add an event listener to listen to window size change and save this to our config file, and then use that size on startup. It would however require us to load the config file a little earlier than what we do know. I'll later today add this to the backlog in the [roadmap](https://github.com/casperstorm/ajour/projects/2) and then close this issue. Thank you for reporting.

**Comment by casperstorm** [comment]
I have added this feature to our roadmap - you can follow the progress of it here: https://github.com/casperstorm/ajour/projects/2#card-45378920

Thank you so much for taking the time opening these feature requests.

**Comment by Ruffz** [comment]
Thanks for this update, position saving was not possible ?

**Comment by casperstorm** [comment]
> Thanks for this update, position saving was not possible ?

@tarkah have you seen if it's possible to spawn the window at a specific x, y position?

I am unsure if it's currently supported. We will look into it.

**Comment by tarkah** [comment]
Let me dig into `winit` and `iced` real quick to see if this is possible

**Comment by tarkah** [comment]
So `winit` definitely exposes `Moved` event here: https://docs.rs/winit/0.22.2/winit/event/enum.WindowEvent.html. 

However, this isn't an event that `Iced` make available to us, plus there is no way to specify the initial position in the iced `WindowSettings`. 

This would be a really easy PR to `iced`. I'll try to tackle this in the upcoming week.

**Comment by tarkah** [comment]
Looks like someone started tackling it here: https://github.com/hecrj/iced/pull/176 but it was abandoned.

**Comment by Ruffz** [comment]
What a quick reaction, it's a pleasure to see your involvement !

Unfortunately (Windows function) éshift + close buttoné doesn't save the position, otherwise I wouldn't have bothered you
